### ISSUE TITLE
mock*.go (generated) files process undocumented

### ISSUE THREAD

**Issue by okartau** [kubernetes-sigs/node-feature-discovery#102]
Being new to project, I tried to improve gofmt/golint metrics in mock*.go files, and I was told these files are generated, and manual changes should be avoided. There is no mention of generated files in documentation, also I don't find any code in repo that deals with generation. Who/when/how generates those and what triggers need to refresh? 
Doesn't (undocumented) manual generate & commit process create a risk that mock*.so elements get out of sync?
Proposals: 
- Can we document the mock*.so files maintenance process
- Idea: Avoid storing mock* as source elements and instead
  generate such files on-the-fly when needed, if possible?

P.S.
mockapihelpers.go has few commits added which touch only small parts so seem like manually made. With manual changes, is that file now in mixed mode?

**Comment by marquiz** [comment]
AFAIU, mockapihelpers.go and mockfeaturesource.go are NOT automatically generated.  If you have fixes to those files, please create a PR. After that, we could close this issue, I think

Any comments @balajismaniam?

**Comment by marquiz** [comment]
This was fixed in #209. Mock files are now generated by running `make mock`, and, there is a note documenting this in each mock file
