### ISSUE TITLE
gRPC Health probe fails when running  with -enable-nodefeature-api

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery#1032]
When running NFD with `-enable-nodefeature-api`, the gRPC health probe fails 

```bash
Events:
  Type     Reason     Age                       From     Message
  ----     ------     ----                      ----     -------
  Warning  Unhealthy  21m (x5110 over 2d23h)    kubelet  Readiness probe failed: command "/usr/bin/grpc_health_probe -addr=:8080" timed out
  Warning  BackOff    6m9s (x16447 over 2d23h)  kubelet  Back-off restarting failed container
  Warning  Unhealthy  69s (x4053 over 2d23h)    kubelet  Liveness probe failed: command "/usr/bin/grpc_health_probe -addr=:8080" timed out
[2:49](https://kubernetes.slack.com/archives/DTRREAN6A/p1673617787536269)

[eduardo@fedora aws-kube-ci]$ kubectl --kubeconfig kubeconfig get pods -n node-feature-discovery 
NAME                          READY   STATUS             RESTARTS           AGE
gpu-feature-discovery-pnt92   1/1     Running            0                  2d23h
nfd-master-668b74498d-kj5fm   0/1     CrashLoopBackOff   1350 (2m58s ago)   2d23h
nfd-master-cd7f6d78d-gg44s    0/1     CrashLoopBackOff   1355 (108s ago)    2d23h
nfd-worker-sgbgj              1/1     Running            0                  2d23h
[2:50](https://kubernetes.slack.com/archives/DTRREAN6A/p1673617806643339)
```
Master pod is crashing due to  grpc helath probe failure

**Comment by marquiz** [comment]
Need to replace the grpc health probe with smth else. Maybe we could use `sigs.k8s.io/controller-runtime/pkg/healthz`? Suggestions for better alternatives (I'm pretty uneducated on this area)? @ArangoGutierrez @zvonkok @fmuyassarov ?

**Comment by marquiz** [comment]
Anyway, thanks for reporting this @ArangoGutierrez! We totally missed this aspect 🙄 We need to fix this and prolly backport to v0.12 branch and cut a patch release

**Comment by fmuyassarov** [comment]
not sure if it is going to make any difference, but what if we try with k8s built in gRPC health probe instead of using the utility?

**Comment by ArangoGutierrez** [comment]
https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/
Sounds good
@marquiz WDYT?

**Comment by fmuyassarov** [comment]
> not sure if it is going to make any difference, but what if we try with k8s built in gRPC health probe instead of using the utility?

actually this might not change anything

**Comment by ArangoGutierrez** [comment]
Yeah,  I will try a couple ideas this weekend and report back
