### ISSUE TITLE
Enable codecov reporting

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1033]
**What would you like to be added**:

Now that https://github.com/kubernetes/org/issues/3084 has been solved, we could enable codecov reporing in NFD. We should probably separate unit tests from the image build (Dockerfile) into a distinct prow job. An outline of sub-tasks (might be missing some)
1. Enable coverage output in Makefile `test:` target
2. Add new `presubmit-test` Prow job
   - A new test script in NFD under `scripts/test-infra/`
   - Job config in https://github.com/kubernetes/test-infra
   - Possibly remove `make test` from Dockerfile(?)
3.  Get codecov token added as a secret in the k8s test-infra cluster
4. Add codecov reporting in the NFD test-infra script (``scripts/test-infra/`)

**Why is this needed**:

Improve development process

**Comment by ArangoGutierrez** [comment]
+1

**Comment by fmuyassarov** [comment]
@marquiz do you plan to work on this ?

**Comment by marquiz** [comment]
> @marquiz do you plan to work on this ?

Feel free to help out here 😉 TBH, I don't know if I have time to take care of this in the near future

**Comment by AhmedGrati** [comment]
@marquiz I can work on it once I finish my current PR.

**Comment by fmuyassarov** [comment]
Hi @AhmedGrati. Thanks for offering help. But I had it halfway. If you don't mind let me finish it and if I don't for some reason I will let you know here.
/assign

**Comment by marquiz** [comment]
I don't think we're quite ready yet
/reopen

**Comment by ArangoGutierrez** [comment]
I think we are ready here, right @fmuyassarov
