### ISSUE TITLE
Chart for latest release is missing

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/node-feature-discovery#1043]
**What happened**:
The Chart for 0.12.1 is missing https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery
**What you expected to happen**:
The chart is published
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marquiz** [comment]
Thanks @MaxRink for the heads-up. I also noticed this last week but thought it was a temporary glitch and forgot about it over the weekend. Got it fixed by pinging folks on the artifact-hub slack channel
/close
