### ISSUE TITLE
Add support for hardware vendor detection

### ISSUE THREAD

**Issue by mnaser** [kubernetes-sigs/node-feature-discovery#1057]
**What would you like to be added**:
I think it would be good to allow NFD to discover the underlying hardware that the system is running on.  This can be useful in bare metal environments where you may have a system that's running HP hardware, or Dell hardware and you would need to run specific things on specific systems

**Why is this needed**:
In my use case, let's say I want to run `dellhw_exporter` only on systems which use Dell hardware, I don't have a way with NFD to detect this out of the box.

**Comment by marquiz** [comment]
Hmm, I'm not sure if there is such unambiguous vendor information in general, as the system can be composed of components from various vendors 🧐 But what we could probably actually do is detect dmi information from `/sys/devices/virtual/dmi/id/*`. For example, `/sys/devices/virtual/dmi/id/sys_vendor` would probably have the information you're after. We could have all the attributes from there as [raw features](https://kubernetes-sigs.github.io/node-feature-discovery/v0.12/usage/customization-guide.html#available-features) that could be consumed by NodeFeatureRules to create custom labels. We could also create present some of those as "built-in" labels that would be always created by NFD.

/help
