### ISSUE TITLE
Create extended resources with NodeFeatureRule

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1081]
**What would you like to be added**:

In addition to labels, taints (#540) and annotations (#863), support also management of extended resources with the NodeFeatureRule CRD API.

**Why is this needed**:

There are usage scenarios where people want to advertise features as extended resources instead of labels (or annotations), e.g. #1079. There has also been use cases like accounting number of network bridge interfaces (or ports, I don't remember) and GPU memory for example. We have long had experimental support for extended resources via the `-resource-labels` command line flag in nfd-master but that is very unwieldy for users (but obviously has worked as we haven't basically got any bug reports or complaints about that).

**Comment by marquiz** [comment]
ping @uniemimu @mythi @fidencio

**Comment by marquiz** [comment]
/help

On top of my head an outline/list of sub-tasks related to the implementation:

1. Extend the NodeFeatureRule CRD API and helpers
    1. Add new `extendedResources` field to NodeFeatureSpec in `pkg/apis/nfd/v1alpha1/types.go`
    2. Run `make generate` to update yamls and auto-generated code
    3. simple update of the RuleOutput type (and related methods/funcs) in `pkg/apis/nfd/v1alpha1/rule.go` to return also extended resources (in addition to labels and taints)
2. Implement support in nfd-master (not super complex as the basic infrastructure for handling extended resources is already in place)
    1. update `processNodeFeatureRule()` to return extended resources
    2. update `refreshNodeFeatures()` to correspondingly update the node status with these extended resources
3. Documentation: at least introduction.md and customization-guide.md
4. Extend e2e-tests to cover extended resources

Few extra considerations regarding "namespacing" i.e. prefixing of names of extended resources:
1. We probably want to specify a "default namespace" that gets applied if no namespace (i.e. `<namespace>/` prefix is give). Basically add a new const like `ExtendedResourceNs` in `pkg/apis/nfd/v1alpha1/annotations_labels.go`. Could be e.g. the same as with labels i.e. `feature.node.kubernetes.io` or `nfd.kubernetes.io` (dunno what would make most sense).
2. It might be best to just allow any vendor specific namespaces, but might want to deny `kubernetes.io/` and its sub-namespaces (`*.kubernetes.io/`) (not sure about this either)

**Comment by PiotrProkop** [comment]
@marquiz  @ArangoGutierrez  Another example of how it can be useful(in other words we would definitely use it!) is to expose Intel RDT `num_closid` the max amount of RDT control groups in the system (prolly -1 for default group).
