### ISSUE TITLE
Helm: add config parameter for enabling taints

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1089]
**What would you like to be added**:

A config parameter to enable taints. E.g. `master.enableTaints`

**Why is this needed**:

Support tainting with the Helm deployment.

**Comment by AhmedGrati** [comment]
@marquiz can I take care of this issue?

**Comment by marquiz** [comment]
> @marquiz can I take care of this issue?

For sure, appreciated!
