### ISSUE TITLE
Enhancement: parallelize nodes update

### ISSUE THREAD

**Issue by AhmedGrati** [kubernetes-sigs/node-feature-discovery#1096]
**What would you like to be added**:
Currently, we are updating nodes in a sequential way.
https://github.com/kubernetes-sigs/node-feature-discovery/blob/821e042dbfde7fe509a26f2215385d7302d9fb51/pkg/nfd-master/nfd-master.go#L295-L306
I think that we can optimize this step by parallelizing this process.

**Why is this needed**:
Optimization of updating nodes process, in terms of execution time.

**Comment by AhmedGrati** [comment]
If relevant, I work on it.

**Comment by marquiz** [comment]
Thanks @AhmedGrati for the proposal. I think this would be a good improvement 👍 Just need to figure out a reasonable default for the parallelism
