### ISSUE TITLE
node-feature-discovery-topology-updater failed to get kubelet config from configz endpoint: Forbidden

### ISSUE THREAD

**Issue by andrewm41** [kubernetes-sigs/node-feature-discovery#1098]
**What happened**:

I've installed v0.12.1 with helm like this:

`helm -n node-feature-discovery upgrade --install --wait node-feature-discovery . --set topologyUpdater.enable=true --set topologyUpdater.createCRDs=true --set topologyUpdater.rbac.create=true --set topologyUpdater.serviceAccount.create=true`

but got this error in all node-feature-discovery-topology-updater pods:

`F0327 15:25:37.787116       1 main.go:86] failed to get kubelet config from configz endpoint: Forbidden (user=system:serviceaccount:node-feature-discovery:node-feature-discovery-topology-updater, verb=get, resource=nodes, subresource=proxy)`

**What you expected to happen**:
node-feature-discovery-topology-updater pods are up and running

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04

**Comment by marquiz** [comment]
That's the problem that got fixed in master by #1078, I think. We could cut a quick patch release 🤔

**Comment by marquiz** [comment]
@andrewm41 see #1109
