### ISSUE TITLE
allow configuration of host paths

### ISSUE THREAD

**Issue by uhthomas** [kubernetes-sigs/node-feature-discovery#1111]
**What would you like to be added**:

The feature files and hooks directories should be configurable.

https://github.com/kubernetes-sigs/node-feature-discovery/blob/285f4253134dfcf9c719d063f49a23df6ced1477/source/local/local.go#L42-L43

**Why is this needed**:

Some operating systems, like [Talos](https://www.talos.dev/) mount `/etc/` as read-only. This means these paths cannot be used.

**Comment by marquiz** [comment]
@uhthomas what deployment method are you using? Basically you only need to adjust the `hostPath`s of the volumes in the deployment. If using Helm we could add new parameters like `worker.hooksDir` and `worker.featuresDir` be able to alter those.

**Comment by marquiz** [comment]
ping @uhthomas

**Comment by uhthomas** [comment]
Sorry, I missed this. I think this is actually okay and I was mistaken. [Talos](https://www.talos.dev/) mount everything as read-only, _except_ `/etc/kubernetes`, which is what node feature discovery uses.

Thank you for your genuine concern :)
