### ISSUE TITLE
nfd-master: config option for NFD API resync period

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1124]
**What would you like to be added**:

Add a config option for setting the NFD API controller resync period. The resync causes nfd-master to replay all NodeFeature and
NodeFeatureRule objects, being effectively a "big hammer" to reset everything. Thus, this also causes some load on the cluster, nfd-master replaying all NFD API objects and querying all nodes from the API server. Making this configurable would enable some users to better adapt nfd to their needs, e.g. by making it possible to fully disable resync.

> NOTE: only has an effect when the NodeFeature API has been enabled (with -enable-nodefeature-api).

**Why is this needed**:

User configurability. Makes it possible for users to tune NFD to their usage scenarios.

**Comment by AhmedGrati** [comment]
@marquiz Should the period be expressed in minutes or hours? Also, should it be part of the dynamically configurable options of the `nfd-master`? Curious to hear your thoughts.

**Comment by marquiz** [comment]
> @marquiz Should the period be expressed in minutes or hours?

As already commented in #1139 by @PiotrProkop it should be a Duration so that the user can specify a number plus the unit.

> Also, should it be part of the dynamically configurable options of the `nfd-master`? Curious to hear your thoughts.

Definitely so, I think. I think it is more useful to have it as a config file variable than a command line flag

**Comment by AhmedGrati** [comment]
Gotcha, I think the current implementation should be updated so.
