### ISSUE TITLE
Deprecate -resource-labels flag

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1125]
**What would you like to be added**:

Deprecate the `-resource-labels` flag of nfd-master and remove it in a future release.

**Why is this needed**:

This was a hack to experiment on extended resources. We now have support for managing extended resources via NodeFeatureRule objects which should be way more manageable and user-friendly.

**Comment by fmuyassarov** [comment]
I guess this can be closed as done?

**Comment by marquiz** [comment]
> I guess this can be closed as done?

Yes I think so. We can create a separate issue about removing it completely later on
/close
