### ISSUE TITLE
Discover node CPU hyper-threading status

### ISSUE THREAD

**Issue by okartau** [kubernetes-sigs/node-feature-discovery#113]
This is a feature that is of binary nature, and can be detected by reading /sys filesystem, so I thought I can add it as next exercise. There are two values we can add: cpu-ht-capable, cpu-ht-enabled. The question however is, in which source should we expose, existing cpuid ? It's not strictly at same level with other cpuid flags, right? should there be another source "cpu" or would this add confusion?

**Comment by okartau** [comment]
on a closer look, existing cpuid-HTT already exposes "hyperthreading enabled" part. But there seems no implementation of "CPU is hyperthreading capable" part?

**Comment by marquiz** [comment]
> on a closer look, existing cpuid-HTT already exposes "hyperthreading enabled" part. But there seems no implementation of "CPU is hyperthreading capable" part?

Is this really a relevant feature, that somebody is interested in? I.e. HT is possible but disabled. I'd probably close this for now, until somebody requires this for a real use case. WDYT?

**Comment by okartau** [comment]
agree, closing this (it was little-justified side track anyway)

**Comment by okartau** [comment]
reopening, per discovery that cpuid-HTT exposes "HT capable" i.e. the other way we assumed when we closed this issue. 
cpuid-HTT is thus not very helpful for practical purpose, for example it does not reflect state where is HT is disabled in BIOS.
We still need a new flag reflecting "HT enabled".

**Comment by marquiz** [comment]
Yup, this was an unpleasant finding when verifying the feature.

AFAIU, the hyper-threading setting cannot be detected directly. See PR #147 for an RFC implementation

**Comment by lmdaly** [comment]
Just so I understand fully, the current cpuid-HTT detects if any core has a sibling and if so the flag is enabled? And the new flag will discover if HTT is enabled instead if the cores have sibling hyper-threads?

**Comment by marquiz** [comment]
> Just so I understand fully, the current cpuid-HTT detects if any core has a sibling and if so the flag is enabled? And the new flag will discover if HTT is enabled instead if the cores have sibling hyper-threads?

Yeah, you got it right: cpuid-HTT only tells if the hardware has HTT capability. It does not tell if the capability has been enabled.

**Comment by marquiz** [comment]
Fixed by #147
