### ISSUE TITLE
Spell out release support policy

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1131]
**What would you like to be added**:

Decide on and write out a release support policy. E.g. that we always support (provide bug fixes and updates) for two releases, N and N-1. In practice, we have currently only supported one release, ceasing patch releases of N when N+1 is out.

**Why is this needed**:

Make it clear for both users and the NFD team what to expect.

**Comment by marquiz** [comment]
Related to this #1132 adds a red banner in v0.6 documentation that this release is not supported anymore. If that looks ok I think we could (and should) safely copy that banner to other older versions at least up to v0.9

**Comment by fmuyassarov** [comment]
> think we could (and should) safely copy that banner to other older versions at least up to v0.9

+1

**Comment by fmuyassarov** [comment]
This would be good addition.

**Comment by ArangoGutierrez** [comment]
Agree, a support matrix, displaying Go build version, Kubernetes version(go.mod) and git commit, and a big disclaimer of the N-1 support 

/lgtm

**Comment by marquiz** [comment]
Related #1141, #1142, #1143 and #1144 add "old non-supported version" banner to v0.7 to v0.10

**Comment by marquiz** [comment]
> Agree, a support matrix, displaying Go build version, Kubernetes version(go.mod) and git commit, and a big disclaimer of the N-1 support

Any thoughts on "N-1"? Makes sense, is enough?

**Comment by PiotrProkop** [comment]
> > Agree, a support matrix, displaying Go build version, Kubernetes version(go.mod) and git commit, and a big disclaimer of the N-1 support
> 
> Any thoughts on "N-1"? Makes sense, is enough?

Is there any official guideline regarding release schedule? I can see that new major version of NFD is released roughly twice a year. So "N-1" means 1 year of support, which seems enough for me 😄

**Comment by ArangoGutierrez** [comment]
I mean.... unless there's a BIG change on the kube dependency(kube api mostly) , we could in theory do N-2, buuuuuut...... I am happy with N-1

**Comment by marquiz** [comment]
> Is there any official guideline regarding release schedule?

Not really. The team has been so small and stretched and contributions so sporadic that I feel a set-in-stone release schedule hasn't really played out. We could decide/say something about this, too. 

> I can see that new major version of NFD is released roughly twice a year. So "N-1" means 1 year of support, which seems enough for me 😄

I hope we could do more than two releases a year, to get new features to users quicker. 3 releases at least would be nice IMO

**Comment by ArangoGutierrez** [comment]
> > Is there any official guideline regarding release schedule?
> 
> Not really. The team has been so small and stretched and contributions so sporadic that I feel a set-in-stone release schedule hasn't really played out. We could decide/say something about this, too.
> 
> > I can see that new major version of NFD is released roughly twice a year. So "N-1" means 1 year of support, which seems enough for me smile
> 
> I hope we could do more than two releases a year, to get new features to users quicker. 3 releases at least would be nice IMO

Agree a release every 3-4 months is desirable 
`release fast, release often`

**Comment by ArangoGutierrez** [comment]
The Vanilla example is -> https://kubernetes.io/releases/version-skew-policy/

---

Kubernetes versions are expressed as x.y.z, where x is the major version, y is the minor version, and z is the patch version, following [Semantic Versioning](https://semver.org/) terminology. For more information, see [Kubernetes Release Versioning](https://git.k8s.io/sig-release/release-engineering/versioning.md#kubernetes-release-versioning).

The Kubernetes project maintains release branches for the most recent three minor releases (1.27, 1.26, 1.25). Kubernetes 1.19 and newer receive [approximately 1 year of patch support](https://kubernetes.io/releases/patch-releases/#support-period). Kubernetes 1.18 and older received approximately 9 months of patch support.

Applicable fixes, including security fixes, may be backported to those three release branches, depending on severity and feasibility. Patch releases are cut from those branches at a [regular cadence](https://kubernetes.io/releases/patch-releases/#cadence), plus additional urgent releases, when required.

The [Release Managers](https://kubernetes.io/releases/release-managers/) group owns this decision.

For more information, see the Kubernetes [patch releases](https://kubernetes.io/releases/patch-releases/) page.

---

**Comment by marquiz** [comment]
See #1279
