### ISSUE TITLE
Enable NodeFeature API by default

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1187]
**What would you like to be added**:

Set default of `-enable-nodefeature-api` to true. IOW, will disable the gRPC API (by default) and, instead, use NodeFeature objects for communicating features and labels from nfd-workers to nfd-master. This will also automatically enable the usage of NodeFeature objects for 3rd party extensions.

**Why is this needed**:

Deprecation of NFD gRPC API.

**Comment by marquiz** [comment]
Would be nice to get feedback when do you think we're ready to make this switchover 😇 @ArangoGutierrez @zvonkok @mythi @PiotrProkop et al

**Comment by PiotrProkop** [comment]
I think one thing that is missing to make it happen is to implement `leader-election` for `nfd-master`. If someone wants to run multiple replicas of `nfd-master` we need to prevent multiple pods from updating same CRs :)

**Comment by marquiz** [comment]
> implement `leader-election` for `nfd-master`

Good point. Could you create an issue about that?

**Comment by PiotrProkop** [comment]
> > implement `leader-election` for `nfd-master`
> 
> Good point. Could you create an issue about that?

https://github.com/kubernetes-sigs/node-feature-discovery/issues/1188

**Comment by marquiz** [comment]
@ArangoGutierrez @PiotrProkop what do you think about this one? Wait until v0.15 or push it already in v0.14

**Comment by PiotrProkop** [comment]
I am fine with both approaches. Leader-election is implemented and if gc PR will be merged we should be good to roll it out.

**Comment by marquiz** [comment]
Thanks @PiotrProkop. I'm also find with both. Leaving this to @ArangoGutierrez then as he probably has the most experience from the production point-of-view 😊

**Comment by ArangoGutierrez** [comment]
the API has passed all recent QA tests, so I think is ready for show time! 
/assign

**Comment by ArangoGutierrez** [comment]
WIP
