### ISSUE TITLE
nfd-master: logging parameters in config file

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1206]
**What would you like to be added**:

Make klog parameters part of the (dynamic) configuration file, similarly to what we have for [nfd-worker](https://kubernetes-sigs.github.io/node-feature-discovery/v0.13/reference/worker-configuration-reference.html#coreklog).

This feature would make it possible to change logging parameters without re-starting nfd-master daemon.

Config file example

```yaml
klog:
  v: "4"
```

**Why is this needed**:

Better usability, dynamic run-time configuration of logging.

**Comment by fmuyassarov** [comment]
@marquiz would you mind if I take this?

**Comment by marquiz** [comment]
> would you mind if I take this?

Please do, it's all yours 😎

**Comment by fmuyassarov** [comment]
Thanks. 
/assign

**Comment by AhmedGrati** [comment]
@fmuyassarov Can I take this one, or you are working on it?

**Comment by fmuyassarov** [comment]
> @fmuyassarov Can I take this one, or you are working on it?

No, please go ahead.
/unassign 
/assign @AhmedGrati
