### ISSUE TITLE
Can't update topologyManagerPolicy and topologyManagerScope attributes of NodeResourceTopology

### ISSUE THREAD

**Issue by PiotrProkop** [kubernetes-sigs/node-feature-discovery#1254]
**What happened**:
NFD is only detecting policy and scope of Topology Manager when NRT object doesn't exist. This means that `topologyManagerScope` and `topologyManagerPolicy` attributes won't change even if `kubelet` config was changed to use other TopologyManager policy and scope.

**What you expected to happen**:

`topologyManagerScope` and `topologyManagerPolicy` attributes of NRT objects will be updated when kubelet config was changed.

**How to reproduce it (as minimally and precisely as possible)**:

- Change TopologyManager policy
- Restart kubelet
- NRT object is still advertising old policy

**Comment by ffromani** [comment]
it seems a bug indeed. We should update the attributes alongside the zones.
