### ISSUE TITLE
Improved metrics

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1275]
**What would you like to be added**:

Additional metrics that are missing in the initial implementation (#1242)

- error counters (on nfd-master):
  - node update errors
  - NodeFeatureRule processing errors
- counters of denied/filtered out properties
  - invalid/rejected labels
  - invalid/rejected extended resources
  - invalid/rejected taints
 
**Why is this needed**:

Improved observability, make it possible to spot error scenarios from metrics.

**Comment by jcpunk** [comment]
It would be helpful if I could attach a custom label to the pod monitor so specific prometheus instances can find it.
