### ISSUE TITLE
Topology-updater metrics

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1281]
**What would you like to be added**:

Add metrics support for nfd-topology-updater (and nfd-topology-gc?). From https://github.com/kubernetes-sigs/node-feature-discovery/issues/1162#issuecomment-1578007917 from @Tal-or 👍 

- Number of updates done to NRT objects, each update increase the counter by one.
- Number of PodresourceAPI calls, each call increases the counter by one.
- We can also expose the time the update took for each node

NOTE: tracking as a separate issue from metrics improvements for nfd-master and nfd-worker (#1275)

**Why is this needed**:

Observability for nfd-topology-updater, get it on-par with nfd-master and nfd-worker.

**Comment by ffromani** [comment]
good call @marquiz . This is totally something we should have.

I think we should indeed expose the time it took to query the podresources endpoints. There are very likely few more noteworthy metrics. I'll comment in the coming days.

**Comment by ffromani** [comment]
The only other meaningful metric I can think of is the time needed to update the NRT objects and the average time between updates (perhaps histogram?). Both metrics are expected to be stable and consistent on normal operation, and either can spike if the node or the apiserver is overloaded.

**Comment by marquiz** [comment]
Thanks for thinking about this @ffromani. If there's nothing very useful you can think of, one thing we could start with is an error counter for the resource scanner.

**Comment by ffromani** [comment]
we can surely start with the error counter indeed
