### ISSUE TITLE
Improve SGX labels

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#130]
Currently, the SGX label is added as true if the ```cpuid``` instruction says SGX is supported. However, it may be that the SGX leaf instructions are disabled from the feature control register making the label void (SXG=true but you cannot  execute SGX enclaves).

Additionally, SGX Launch control feature bit is necessary as the label.

**Comment by okartau** [comment]
cpuid-SGX label is correct (note the cpuid part in label name).
"SGX-capable CPU" is not equal to "SGX can be used by SW". 
This additional detection complexity is described in docs like https://en.wikipedia.org/wiki/Software_Guard_Extensions
(perhaps we can add a warning note for SGX case in NFD doc?).

The fact that use of SGX requires more (BIOS support, opt-in enabling), does not make cpuid-SGX label void or false.

If we want to see label "SGX can be used" then we need additional detection code somewhere.

Extending related CPUID-based flags:
Current klauspost/cpuid that is used by NFD, does not look further than SGX bit,
so if we want to see more on (Launch control, SGX1/SGX2 capability), we need to either push for additions on cpuid package side, or add own detection code (like we have on NFD/RDT side).

End goal, i.e. to get label "SGX can be used":
Can we rely on kernel cpu flag?
This flag gets added by SGX kernel driver, right?
(As I don't see it on a plain system (Xeon v6) where CPUID shows SGX capability).

**Comment by mythi** [comment]
IMO, the title of this issue is valid and the improvement is justified: ```cpuid-SGX``` alone cannot be use to determine the node can run enclaves.

**Comment by marquiz** [comment]
Probably so. I just tried to point out that the CPUID SGX label is correct and should not be changed (possibly only masked out), and, we need a new feature source (plugin) if we want to have SGX detection.

**Comment by marquiz** [comment]
@mythi: Is this feature still needed? What would be the use case for this?

**Comment by mythi** [comment]
/reopen
/remove-lifecycle rotten

I'll be working on addressing this.
