### ISSUE TITLE
NodeFeature CRD not deleted when node is deleted

### ISSUE THREAD

**Issue by mtaron** [kubernetes-sigs/node-feature-discovery#1304]
**What happened**:
When running with `"enableNodeFeatureApi": true` I've noticed that NodeFeature CRDs seem to accumulate endlessly. Our workload scales up and down frequently and the NodeFeature CRDs for deleted nodes are not removed. After a couple months, this led to almost five thousand NodeFeatures resources in one of our clusters, at which point it seems like NFD runs into intermittent performance/scale issues where new nodes sometimes do not get NodeFeatures created for them.
 
**What you expected to happen**:
I expect a NodeFeature to be deleted when the node in question is removed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install the Node Feature Discovery Helm chart with `"enableNodeFeatureApi": true`
2. Scale up the cluster (provider specific: [here are instructions](https://learn.microsoft.com/en-us/azure/aks/scale-cluster?tabs=azure-cli) for how to do this in Azure Kubernetes Service)
3. Confirm that a NodeFeature has been created for the new node.
4. Scale down the cluster
5. Confirm that the NodeFeature for the deleted node still exists (this is the bug)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.26.3
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux <vmname here> 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Helm
- Network plugin and version (if this is a network-related bug): Not networking
- Others:

**Comment by marquiz** [comment]
@mtaron thank you for reporting this issue.

I think the most straightforward way to address this would be to extend the existing `nfd-topolgoy-gc` to handle NodeFeature objects, too. Probably renaming the daemon to just `nfd-gc` or smth and enabling it by default in all deployments. In hindsight (with this issue reported) it looks odd that we didn't think about NodeFeature objects when introducing the nrt-garbage-collector in v0.13 🤨

ping @ArangoGutierrez @PiotrProkop @fmuyassarov

**Comment by marquiz** [comment]
In addition to addressing this in v0.14 we probably want to add a note/warning about this iin the v0.13 documentation
