### ISSUE TITLE
Allocatable CPU not updating

### ISSUE THREAD

**Issue by cl-rf** [kubernetes-sigs/node-feature-discovery#1312]
**What happened**:
Deploying a pod with a cpu request/limit does not change the allocatable value for the noderesourcetopology.

**What you expected to happen**:
I expect the value to decrease based on the request/limit of the pod.

**How to reproduce it (as minimally and precisely as possible)**:
 `kubectl get noderesourcetopology.topology.node.k8s.io -o yaml`
```
apiVersion: v1
items:
- apiVersion: topology.node.k8s.io/v1alpha2
  attributes:
  - name: topologyManagerPolicy
    value: single-numa-node
  - name: topologyManagerScope
    value: container
  kind: NodeResourceTopology
  metadata:
    creationTimestamp: "2023-08-26T19:04:07Z"
    generation: 3242
    name: ip-1.1.1.1-west-1.compute.internal
    resourceVersion: "67906"
    uid: 3f1f8a64-edbf-459a-a51b-12404b1f40d4
  topologyPolicies:
  - SingleNUMANodeContainerLevel
  zones:
  - costs:
    - name: node-0
      value: 10
    - name: node-1
      value: 21
    name: node-0
    resources:
    - allocatable: "32"
      available: "32"
      capacity: "36"
      name: cpu
    - allocatable: "98327445504"
      available: "98327445504"
      capacity: "100474929152"
      name: memory
    type: Node
  - costs:
    - name: node-0
      value: 21
    - name: node-1
      value: 10
    name: node-1
    resources:
    - allocatable: "36"
      available: "36"
      capacity: "36"
      name: cpu
    - allocatable: "99261173760"
      available: "99261173760"
      capacity: "101408657408"
      name: memory
    type: Node
kind: List
metadata:
  resourceVersion: ""`
```

Deploy a test.

```
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment1
spec:
  selector:
      matchLabels:
        name: test
  template:
    metadata:
      labels:
        name: test
    spec:
     containers:
      - name: test-deployment-1-container-1
        image: quay.io/fromani/numalign
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: [ "while true; do numalign; sleep 100000; done;" ]
        resources:
          limits:
            cpu: 20
          requests:
            cpu: 20`
```

The available and allocatable does not decrease.

```
`apiVersion: v1
items:
- apiVersion: topology.node.k8s.io/v1alpha2
  attributes:
  - name: topologyManagerPolicy
    value: single-numa-node
  - name: topologyManagerScope
    value: container
  kind: NodeResourceTopology
  metadata:
    creationTimestamp: "2023-08-26T19:04:07Z"
    generation: 3386
    name: ip-1.1.1.1-west-1.compute.internal
    resourceVersion: "70926"
    uid: 3f1f8a64-edbf-459a-a51b-12404b1f40d4
  topologyPolicies:
  - SingleNUMANodeContainerLevel
  zones:
  - costs:
    - name: node-0
      value: 21
    - name: node-1
      value: 10
    name: node-1
    resources:
    - allocatable: "99261173760"
      available: "99261173760"
      capacity: "101408657408"
      name: memory
    - allocatable: "36"
      available: "36"
      capacity: "36"
      name: cpu
    type: Node
  - costs:
    - name: node-0
      value: 10
    - name: node-1
      value: 21
    name: node-0
    resources:
    - allocatable: "98327445504"
      available: "98327445504"
      capacity: "100474929152"
      name: memory
    - allocatable: "32"
      available: "32"
      capacity: "36"
      name: cpu
    type: Node
kind: List
metadata:
  resourceVersion: ""`
```

**Anything else we need to know?**:
```
  kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.13.3
  kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/topologyupdater?ref=v0.13.3

```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.27.4+rke2r1
Kustomize Version: v5.0.1
Server Version: v1.27.4+rke2r1
```

- Cloud provider or hardware configuration:
`EC2 - c5n.metal`

- OS (e.g: `cat /etc/os-release`):
`Red Hat Enterprise Linux release 9.1 (Plow)`

- Kernel (e.g. `uname -a`):
`Linux ip-1.1.1.1-west-1.compute.internal 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:36:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by cl-rf** [comment]
It looks like this is when deployments are used instead of just a single pod definition.

**Comment by marquiz** [comment]
ping @PiotrProkop @ffromani 

@cl-rf did pod(s) from your deployment get scheduled on the node you're looking at?

**Comment by ffromani** [comment]
Hi, the meaning of the fields (we should probably annotate [more] the CRD spec) is

1. Capacity: what the machine reports in total, e.g. from hardware
2. Allocatable: capacity - reserved. If there are no resources reserved for the system, it will equal capacity
3. Available: Allocatable - consumed, the amount of resources free for allocation

Thus "allocatable" should never change if the machine/cluster config doesn't change first, which is an event we expect to happen rarely. "available" should instead change depending on the workload running. And it seems to me in the above example it is changing?

HTH,

**Comment by cl-rf** [comment]
It is only 1 node. If I set the requirements for both cpu and memory, it seems like it reports fine vs just setting a cpu requirement. 

noderesourcetopology.topology.node.k8s.io reports correctly

```
        resources:
          limits:
            cpu: 20
            memory: "256M"
          requests:
            cpu: 20
            memory: "256M"

```
vs
```
        resources:
          limits:
            cpu: 20
          requests:
            cpu: 20
```

```
  - costs:
    - name: node-0
      value: 10
    - name: node-1
      value: 21
    name: node-0
    resources:
    - allocatable: "36"
      available: "16"
      capacity: "36"
      name: cpu
```

**Comment by ffromani** [comment]
Yes, the accouting is done only for exclusively-assigned resources (CPUs in this case), which is possible only for guaranteed QoS pods. This may be surprising but is due to how kubernetes works, we can't do it differently.
There's something else not working as expected? because it seems to me this part could be documented perhaps better, but seems to work as intended.

**Comment by cl-rf** [comment]
Yeah, I guess a note on the documentation would help.

**Comment by ffromani** [comment]
fair enough, I'll review the docs and perhaps post a PR to clarify further in the coming days
