### ISSUE TITLE
Consider moving to cpu flags

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#132]
In a follow-up to #130, I started thinking why can't we rely on kernel's cpu flags more? That'd be more realistic view to what the node/kernel supports (HW support alone isn't necessarily what the node supports).

The additional benefit would be reduced dependencies and code maintenance: RDT detection tools and cpuid Go package would no longer be needed.

**Comment by okartau** [comment]
Obviously this would make NFD job easier, but there likely was reason why this was not the method from very start. It's a fundamental question should NFD consider features which are either
a) "supported in HW and detected by kernel"
or b) "supported in HW"
and b) was selected, leaving kernel out of path.
One reason coming to mind is, by relying on kernel-detected flag, NFD may miss some newer
features which are not listed by older kernel. I recall someone said that lot of k8s servers run
CentOS-7 which runs kernel 3.10. And is it possible some application can use CPU feature (like instruction set extension?) even if kernel is older and has not detected it? That's one scenario that might be behind thinking why b) was selected.
Has such a design selection been documented somewhere? I looked into design doc pointed from README but did not find it.

**Comment by mythi** [comment]
On Mon, May 28, 2018 at 4:36 PM, Olev Kartau <notifications@github.com>
wrote:

> One reason coming to mind is, by relying on kernel-detected flag, NFD may
> miss some newer
> features which are not listed by older kernel. I recall someone said that
> lot of k8s servers run
>

This is probably one of the reasons. If this is desired, the existing cpuid
source plugin could stay
and this issue can be renamed to 'add cpuflags source plugin'.

**Comment by marquiz** [comment]
> If this is desired, the existing cpuid
> source plugin could stay
> and this issue can be renamed to 'add cpuflags source plugin'.

Yep, I wouldn't remove the existing functionality, i.e. CPUID plugin. Write a new plugin, if needed.

But, I'm not necessarily very enthusiastic about this. My concern is the flat structure of labels, which would be cluttered with mostly uninteresting flags (that's prolly true with the existing CPUID flags, already). There are easily over 100 cpu kernel flags. I don't know if this really is a problem, though.

**Comment by mythi** [comment]
I filed the issue to open the discussion. The problem I see is ```cpuid``` plugin can give false result for what is really supported (see #130).

**Comment by okartau** [comment]
I would not say "cpuid plugin gives false result".
It gives us correct facts in CPU capability domain, just that in SGX case we additionally need other facts from other domains to get full SGX capability. The name of flag fortunately is cpuid-SGX which reflects the scope quite well.

**Comment by mythi** [comment]
@okartau true, ```s/false/incomplete/```
