### ISSUE TITLE
Limit feature file size

### ISSUE THREAD

**Issue by AhmedGrati** [kubernetes-sigs/node-feature-discovery#1330]
**What would you like to be added**:
Currently, we are processing feature files without any restriction on the file size, since we are expecting that the file is coming from a trusted source. However, processing large files can present some bottlenecks. Therefore, we should limit the size of features' files.
For more information: [https://github.com/kubernetes-sigs/node-feature-discovery/pull/1285#issuecomment-1704688764](https://github.com/kubernetes-sigs/node-feature-discovery/pull/1285#issuecomment-1704688764)

**Why is this needed**:
Improve confidence in the system, by covering edge cases concerning feature file size.

**Comment by AhmedGrati** [comment]
FYI @marquiz.
BTW I have two questions concerning this:
1- Should we make the file size limit configurable, with a default value of `64kB`, so users can adjust the limit based on their use cases?
2- If the size of a file is bigger than the limit, should we process it in chunks, or raise an error to the user?

**Comment by marquiz** [comment]
Thanks @AhmedGrati for creating this issue

> 1- Should we make the file size limit configurable, with a default value of `64kB`, so users can adjust the limit based on their use cases?

I don't think we need to make it configurable. I believe 64kB (or 32kB) should be plenty, enough. Let's revisit this if somebody really comes up with a use case for bigger feature files.

> 2- If the size of a file is bigger than the limit, should we process it in chunks, or raise an error to the user?

I would consider it as a "transaction", all or nothing, not advertise partial results. I.e. skip the file if it's too big

ping @eero-t
