### ISSUE TITLE
Create subdir for atomic feature file updates

### ISSUE THREAD

**Issue by eero-t** [kubernetes-sigs/node-feature-discovery#1337]
**What would you like to be added**:

NFD to document and create a subdir under its feature files dir, which NFD client apps can use for their atomic feature file creation.

**Why is this needed**:

Atomic feature file generation means that the file needs to be done elsewhere and renamed/moved to feature dir.   Because renaming works atomically only within same fs, best place for generating the feature file, is feature dir subdir (clients already have feature dir mounted as writable).

If NFD does not document & provide such dir, it means that clients need to.  That can results feature dir having large number extra entries, for per-client subdirs.  Which can be a problem, if NFD will at some later point start parsing also feature dir subdir content...

**Comment by marquiz** [comment]
Thanks for the suggestion @eero-t. NFD doesn't currently recurse into subdirectories so it is safe for the "clients" to create a tmpdir there. One change that we could possibly pretty safely do is to start ignoring "hidden" files (i.e. filenames starting with a dot), and document this. Then it would be straightforward for a client to create a new file like `.my.features` and then just rename it to `my.features`, without any directories involved. I think this would nicely keep the path open for subdir recursion in the future, if we want that, plus would allow clients to use tmpdirs if they want.

Thoughts?

**Comment by eero-t** [comment]
Hidden (dot) file idea sounds better than needing to use subdir!   FYI: @tkatila

**Comment by tkatila** [comment]
:+1: on the hidden file. It saves the burden of creating the temporary directory (and removing it).

**Comment by marquiz** [comment]
ping @AhmedGrati you have been working on these lately so this might be one more small enhancement to do 😇

cc @ArangoGutierrez
