### ISSUE TITLE
Drop the version annotations

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1352]
**What would you like to be added**:

Now that we have the [metrics](https://kubernetes-sigs.github.io/node-feature-discovery/v0.14/deployment/metrics.html) (with the `nfd_master_build_id` and `nfd_worker_build_id` metrics) there we could drop the `nfd.node.kubernetes.io/master.version` and `nfd.node.kubernetes.io/worker.version` annotations as redundant.

**Why is this needed**:

Drop redundant information. Keep the node annotations cleaner. Also the annotations are "asymmetric" in the sense that we don't have similar annotations for nfd-topology-updater or nfd-gc.

Stale annotations can also give misleading information. For example: say you run one replica of nfd-master, first it runs on node A and you get `master.version=v0.13.0` on node A. Then NFD gets migrated to node B and you update to NFD v0.14.0 and you will get `master.version=v0.14.0` on node B. Now node A has the annotation even if nfd-master is not running there anymore, and moreover, it also gives misleading information about the current version of NFD.

**Comment by ArangoGutierrez** [comment]
++
