### ISSUE TITLE
helm: worker role&rolebinding doesn't respect namespaceOverride

### ISSUE THREAD

**Issue by tkatila** [kubernetes-sigs/node-feature-discovery#1363]
**What happened**:
I'm using NFD as a child/sub chart. With 0.13.3, I could use values' `namespaceOverride` to deploy NFD components under a different namespace vs. the parent. Now when I deploy 0.14.0, everything seems to go under the `namespaceOverride` namespace, but actually role and rolebindings go under the parent namespace. This results in worker crash-looping.

**What you expected to happen**:
Worker(s) shouldn't crash-loop. Role and rolebinding object should go under the correct namespace.

**How to reproduce it (as minimally and precisely as possible)**:
values.yaml
```
nfd:
  namespaceOverride: node-feature-discovery
```

Chart.yaml
```
apiVersion: v2
name: foo
description: A Foo Helm chart
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: node-feature-discovery
    alias: nfd
    version: 0.14.0
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
```

To install:
```
kubectl create namespace node-feature-discovery
helm dep update
helm install --namespace bar --create-namespace foo .
```

Results in:
```
$ kubectl get pods -n node-feature-discovery 
NAME                             READY   STATUS             RESTARTS      AGE
foo-nfd-gc-576d46555-ftpwh       1/1     Running            0             107s
foo-nfd-master-8b7c86575-c6x59   1/1     Running            0             107s
foo-nfd-worker-cvk2h             0/1     CrashLoopBackOff   4 (17s ago)   107s
foo-nfd-worker-kk8wq             0/1     CrashLoopBackOff   4 (17s ago)   107s
$ kubectl get roles -n bar
NAME             CREATED AT
foo-nfd-worker   2023-09-19T09:12:23Z
$ kubectl get rolebindings -n bar
NAME             ROLE                  AGE
foo-nfd-worker   Role/foo-nfd-worker   2m50s
```

**Anything else we need to know?**:
Nope.

**Comment by marquiz** [comment]
Thanks @tkatila for reporting this. Will look into it...

**Comment by marquiz** [comment]
The Helm chart has been buggy ever since v0.12 but hasn't been hit because NodeFeature API has been disabled by default. Now that we enabled the api you were the first victim 😬
