### ISSUE TITLE
Configurable restrictions on CRs

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1380]
**What would you like to be added**:

I would like to be able to configure restrictions on NodeFeatures and NodeFeatureRule objects. E.g.
1. filtering of which NodeFeature objects to watch (e.g. per K8s namespace)
2. prevent labels from 3rd party NodeFeatures (just "raw features" allowed)
3. prevent overwriting of labels
4. prevent overwriting of "raw features"
5. set the max number of labels/ERs/taints that can be created, per CR and in total

**Why is this needed**:

Improved control on what is allowed on the cluster

**Comment by ArangoGutierrez** [comment]
V0.15 or v0.16?

**Comment by marquiz** [comment]
> V0.15 or v0.16?

Depends on people's time, I guess 😇 We could have something small already in v0.15

**Comment by AhmedGrati** [comment]
Two questions here:
- regarding setting the max number of taints, labels, and ERs: If the requested number exceeds the max, should we skip the nodes' update or update the nodes with a subset of labels? e.g. if the max is 10 labels and the request has 12 labels, we only take the first 10 labels.
- In the filtering of which NodeFeature to watch, I'm currently thinking of passing a regex of `<namespace>/<name>`, so users can have the most flexibility (with a default of `*/*`. Any objections here?

wdyt @marquiz @ArangoGutierrez ?

**Comment by marquiz** [comment]
Almost there
/remove-lifecycle rotten
