### ISSUE TITLE
Add the CPU Socket information

### ISSUE THREAD

**Issue by pgodowski** [kubernetes-sigs/node-feature-discovery#1383]
**What would you like to be added**:

The CPU Sockets number, for the bare metal worker nodes (otherwise, virtualized worker nodes' sockets count is just emulated number).

**Why is this needed**:

On some scenarios, the number of CPU Sockets is required for the license calculation perspective.
For example, take a look https://access.redhat.com/discussions/480953 where the 3rd party applications are licensed based on the number of CPU Sockets, where Kubernetes cluster (OpenShift, to be specific) runs on the bare metal systems.

Given that in **some** scenarios it's [possible to discover the number of cpu sockets](https://stackoverflow.com/questions/59158453/how-to-programmatically-find-the-number-of-cpu-sockets-and-core-per-socket-in-li), tools available like https://github.com/ryran/xsos, I believe such information shall be exposed, with the caveat that in some other conditions such value is either not available, or just represents the virtual number of sockets. 

There was a related issue closed https://github.com/kubernetes-sigs/node-feature-discovery/issues/784 where there was a comment https://github.com/kubernetes-sigs/node-feature-discovery/issues/784#issuecomment-1069554415 from @marquiz  that the node labels might not properly reflect the cpu related attributes in some cases, but wondering whether if we narrowed down the set of scenarios to support, it would make sense to proceed?

Other way of asking - if there were PR submitted, to introduce number of CPU Sockets, what are the things to consider, or perhaps such PR would be rejected right at the beginning?

**Comment by marquiz** [comment]
@pgodowski I think the number of sockets could be added as a feature, especially if/when you have a use case for it. Also, the number of sockets in system is unambiguous where as e.g. "number of threads per core" may not be (as different cores might have different number of threads).

We already have `cpu.topology` feature (see the [list of current features](https://kubernetes-sigs.github.io/node-feature-discovery/v0.14/usage/customization-guide.html#available-features)) so we could add `socket_count` (or something like that) as a new element there. That could then be exposed as a label with a [NodeFeatureRule](https://kubernetes-sigs.github.io/node-feature-discovery/v0.14/usage/custom-resources.html#nodefeaturerule). I'm not sure if this is something that we'd publish as a label by default - would be good to hear other people's opinions on this.

**Comment by marquiz** [comment]
@pgodowski are you willing to work on this?

**Comment by pgodowski** [comment]
Thank you so much for enhancing the discovery with the CPU Socket information! I am sorry I was late reacting to your questions.
