### ISSUE TITLE
Discover virtual network interfaces

### ISSUE THREAD

**Issue by rwlove** [kubernetes-sigs/node-feature-discovery#1385]
**What happened**:

```
➜  fleet-infra git:(main) ✗ kubectl describe nodefeaturerules.nfd.k8s-sigs.io test-vlan-device
Name:         test-vlan-device
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  nfd.k8s-sigs.io/v1alpha1
Kind:         NodeFeatureRule
Metadata:
  Creation Timestamp:  2023-09-28T23:32:36Z
  Generation:          1
  Resource Version:    12965328
  UID:                 dfbefb1e-a7a0-4677-a191-98347f8f0074
Spec:
  Rules:
    Labels:
      node.network/vlan:  test-vlan
    Match Features:
      Feature:  network.device
      Match Expressions:
        Name:
          Op:  In
          Value:
            enp1s0.20
    Name:  test-vlan.iot
Events:    <none>

➜  fleet-infra git:(main) ✗ kubectl get nodes --show-labels | grep test-vlan       
           
➜  fleet-infra git:(main) ✗ kubectl get nodes | grep worker8                
worker8.foo.com   Ready    <none>          13d   v1.28.1

➜  fleet-infra git:(main) ✗ ssh root@worker8 ip addr | grep enp1s0.20
3: enp1s0.20@enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    inet 10.10.20.34/24 brd 10.10.20.255 scope global dynamic noprefixroute enp1s0.20
```

**What you expected to happen**:

I expected the `node.network/vlan:  test-vlan` to be applied.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

Other NodeFeatureRules are working just fine, like pci.device and usb.device.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
➜  fleet-infra git:(main) ✗ kubectl version                 
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1
```

- Cloud provider or hardware configuration:

Mix of bare-metal and VMs on bare-metal.

- OS (e.g: `cat /etc/os-release`):

CentOS 9 Stream

- Kernel (e.g. `uname -a`):

5.14.0-354.el9.x86_64

- Install tools:

kubeadm, helm, flux, kustomize

- Network plugin and version (if this is a network-related bug):

```
➜  fleet-infra git:(main) ✗ cilium version     
cilium-cli: v0.15.5 compiled with go1.20.4 on linux/amd64
cilium image (default): v1.14.0
cilium image (stable): v1.14.2
cilium image (running): 1.14.2
```

- Others:

**Comment by marquiz** [comment]
Hi @rwlove thanks for reporting this. As per design/documentation the `network.device` feature only lists physical devices, i.e. interfaces which have a real device backing them up.

I think we could add detection of virtual interfaces, too, if there's a clear use case for that (other than just testing). Could you comment on this?

/kind feature
/remove-kind bug

**Comment by marquiz** [comment]
I'd suggest adding a new feature like `network.virtual`.

/retitle Discover virtual network interfaces
/help

**Comment by jon-rei** [comment]
Hi @marquiz Another use case for me is that I want to determine the speed of a bond interface out of multiple physical interfaces and schedule workloads on nodes based on the label. Since I have nodes with different network speeds in my cluster, I need to know which nodes to place higher traffic workloads on.

**Comment by AhmedGrati** [comment]
@rwlove @jon-rei what features would you like to be exposed out of the virtual network interface?

**Comment by jon-rei** [comment]
Hi @AhmedGrati I would like to get the speed of the virtual network interface e.g. the bond0 interface: `/sys/class/net/bond0/speed`, which is just an integer at the end. Looking at the current documentation of available features, I think it's the `network.device` feature.

**Comment by marquiz** [comment]
@jon-rei @AhmedGrati in https://github.com/kubernetes-sigs/node-feature-discovery/issues/1385#issuecomment-1744291455 I suggested to add a new `network.virtual` feature for the virtual devices. `network.device` is for physical devices – at least how we've currently documented it. WDYT?

**Comment by jon-rei** [comment]
@marquiz @AhmedGrati Thanks for the implementation. But unfortunately it is not useful for my use case. I want to discover bond interfaces with a specific interface speed, but the speed is not available. Would it be possible to add this to the virtual network interface detection as well?

**Comment by marquiz** [comment]
Oh. That should be very simple to add. @AhmedGrati would you be willing to work on that?

**Comment by AhmedGrati** [comment]
Sure @marquiz. Should I create a separate issue for this?

**Comment by marquiz** [comment]
@AhmedGrati infact this looked so simple that I submitted already #1536. PTAL

**Comment by marquiz** [comment]
I think this is something that we could consider cherry-picking for the release-0.15 branch. Especially bc not detecting the speed attribute was kind of mistake wrt the feature request. WDYT?

**Comment by AhmedGrati** [comment]
+1 for me.
