### ISSUE TITLE
nfd-topology-updater only tracks resources it discovered during startup

### ISSUE THREAD

**Issue by PiotrProkop** [kubernetes-sigs/node-feature-discovery#1424]
**What happened**:
Resources that will be managed by NFD topology-updater are only discovered during startup.
If a device plugin registers itself with kubelet after NFD topology-updater is already running the NRT will never be updated with new resources.

Resource discovery [link](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/pkg/resourcemonitor/noderesourcesaggregator.go#L94)
Ignoring resources not present during startup [link](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/pkg/resourcemonitor/noderesourcesaggregator.go#L246).

It may cause issues when nfd is restarted alongside device plugins, in this case NRT will stop reporting some resources.

**What you expected to happen**:

When device plugin is created after NFD start new resources should be reported without the need of restarting NFD. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marquiz** [comment]
@PiotrProkop @ffromani are you planning to work on this? Thinking about v0.16 release that is currently projected at the end of March

**Comment by ffromani** [comment]
> @PiotrProkop @ffromani are you planning to work on this? Thinking about v0.16 release that is currently projected at the end of March

I'd love to help but I won't have any bandwidth before early March.

**Comment by PiotrProkop** [comment]
> > @PiotrProkop @ffromani are you planning to work on this? Thinking about v0.16 release that is currently projected at the end of March
> 
> I'd love to help but I won't have any bandwidth before early March.

I would also be able to start working on that in March, in the meantime I'll try to figure out if there is an easy fix for that or if it requires a bigger refactoring 😄

**Comment by ffromani** [comment]
/remove-lifecycle stale

didn't forget, """just""" got preempted by other tasks :\
