### ISSUE TITLE
Add AhmedGrati as a reviewer

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1563]
I'd like to propose that @AhmedGrati would be added as a project reviewer.

Ahmed has been very active in the project and  has contributed a long list of important enhancements and new features, brought up new ideas and also helped in code reviews.

PRs and issues authored:
https://github.com/kubernetes-sigs/node-feature-discovery/pulls?q=author%3AAhmedGrati

Reviews and comments:
https://github.com/kubernetes-sigs/node-feature-discovery/pulls?q=commenter%3AAhmedGrati

I really feel being a bit late and that I should've proposed this earlier 😊

**Comment by fmuyassarov** [comment]
Big +1. Thank you @AhmedGrati for all the contributions you have already made.
/lgtm

**Comment by PiotrProkop** [comment]
Congrats! 
/lgtm

**Comment by jjacobelli** [comment]
Congrats! +1
/lgtm

**Comment by AhmedGrati** [comment]
Thank you for the recognition! Happy to join the team 🙏

**Comment by marquiz** [comment]
Welcome @AhmedGrati 🎉
