### ISSUE TITLE
Document NFD in k/k

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1569]
The k/k documentation has a section about automatic node labelling (in the context of GPU scheduling). However, there is no mention of NFD there:

https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/#node-labeller

That should be fixed. Thanks @eero-t for pointing this out.

I created this kind-of  "cross-project" issue for tracking (and not forgetting about it).

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/website/pull/44915

**Comment by ArangoGutierrez** [comment]
We can now close this :)
