### ISSUE TITLE
Swap support

### ISSUE THREAD

**Issue by kannon92** [kubernetes-sigs/node-feature-discovery#1584]
**What would you like to be added**:
I am working on https://github.com/kubernetes/enhancements/issues/2400 which adds swap support. I think that this project could be a good fit for labeling nodes if they have swap enabled.
**Why is this needed**:
Swap is an important characteristic of a node and it is usually turned off. We are introducing ways for heterogenous nodes for swap so we should have a label for a swap enabled node.

I think the implementation could just check `swapon` and verify that swap is enabled on the node.

**Comment by marquiz** [comment]
Thanks @kannon92 for bringing this up. I think this would be a really good enhancement for NFD. We cannot do `swapon` as  we run NFD essentially in an empty/scratch container. We could read `/proc/swaps`, we'd need to add that (this file only, not the whole procfs) to the volumes/mounts in deployment files. Do you know any other methods for determining if swap is on (like from sysfs which is already mounted inside the NFD container)?

**Comment by kannon92** [comment]
So I’m happy to contribute!

so as I posted this I realize /proc/swaps is probably the correct path.

I was thinking I could add this to memory in source/memory. 

So would I open /proc/swaps and detect if swap is enabled by parsing that file? 

And would swap be considered an attribute or a feature?

**Comment by marquiz** [comment]
> So I’m happy to contribute!

@kannon92  🎉
 
> so as I posted this I realize /proc/swaps is probably the correct path.

Yes, I'm not aware of anything better, either

> I was thinking I could add this to memory in source/memory.

👍 I think that would be the logical place for it

> So would I open /proc/swaps and detect if swap is enabled by parsing that file?

That would be it

> And would swap be considered an attribute or a feature?

I think `swap` would be an ["attribute feature"](https://kubernetes-sigs.github.io/node-feature-discovery/v0.15/usage/customization-guide.html#feature-types) under the `memory` source, with one "element" or "property" telling if it's on or not. So we'd have a label like `feature.node.kubernetes.io/memory-swap.on=<true/false>`, and correspondingly `memory.swap.on` ["hidden feature"](https://kubernetes-sigs.github.io/node-feature-discovery/v0.15/usage/customization-guide.html#available-features) for custom rules to use as input.

We could target NFD v0.16 which we've been planning to release before the end of March.
/milestone release-0.16

**Comment by kannon92** [comment]
> we'd need to add that (this file only, not the whole procfs) to the volumes/mounts in deployment files.

Can you point me where you expect this change to be?

**Comment by marquiz** [comment]
> Can you point me where you expect this change to be?

In this repo we have Helm:
https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/templates/worker.yaml

and kustomize:
https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/components/common/worker-mounts.yaml
