### ISSUE TITLE
Flag cpu manager availability

### ISSUE THREAD

**Issue by fabiand** [kubernetes-sigs/node-feature-discovery#165]
Today Kube does not announce the availability of cpu manager on a node.

NFD could expose this.

**Comment by fabiand** [comment]
Yes, it's about the configured policy IIUIC:

@vladikr do you have some details?

**Comment by marquiz** [comment]
And, what would be the use case for this? Why would you have non-uniformly configured cpu manager policies in the cluster?

**Comment by vladikr** [comment]
> So, first kubelet would need to be changed to advertise that information in node status or somewhere

Yes, I also agree that it's up to kubelet to advertise the configured policy. I've opened https://github.com/kubernetes/kubernetes/issues/66525 a while ago.

> And, what would be the use case for this? Why would you have non-uniformly configured cpu manager policies in the cluster?

Some workloads require cpu pinning, some don't so they need to be scheduled on a node where the cpu manager is running with a certain policy. There is no easy way to tell the cpu manager whether to pin a container or not, but schedule it on a node with correct policy.

**Comment by fabiand** [comment]
That's actually a valid question.

It does not depend on hardware, thus there is no reason to have a homogeneous cluster.

**Comment by marquiz** [comment]
Yeah, I wanted to understand if this is really needed. I.e. is the underlying assumption that the cluster admin is supposed to configure the same cpu manager policy in all nodes inside the cluster. Especially now that there are only two possible policies

**Comment by fabiand** [comment]
In geneal I see your point..
One remaining reason I see is that a user is atm not able to see if a
policy is available or not.

**Comment by marquiz** [comment]
> One remaining reason I see is that a user is atm not able to see if a policy is available or not.

But even NFD is not able to get that information. There seems to be a gap that the kubelet issue you opened would address

**Comment by fabiand** [comment]
True - and there is the issue open on that.

Should we then close this issue and or keep it open until it's fixedß

**Comment by marquiz** [comment]
We can keep this open until the problem has been resolved. And, we have full understanding whether nfd would need to be involved or not
