### ISSUE TITLE
Detect PCI devices

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#167]
A new feature source for detecting the presence of PCI devices.

By default, it would detect Network devices, GPUs and accelerator cards (device classes 0x02, 0x03 and 0x12). The label format would be:
```
nfd-pci-device-<DEV_LABEL>-present
```
And, by default, the `<DEV_LABEL>` part would consist of:
```
<CLASS_ID>-<VENDOR_ID>
```

The feature source would need to be configurable, with the following settings available:
1. device class white list:
   - not all device classes are interesting to the user
   - limit the number of labels
1. label format:
   - users might want to have more granularity
   - the `DEV_LABEL` part of the node label would be configurable

The use case for this would be e.g. deploying device plugins only on the nodes that have compatible hardware.

**Comment by kad** [comment]
it might be good that label will not in form "present", but also exposing quantity of such devices. 
E.g. 2 GPU of Vendor1, 1 GPU of Vendor2.

**Comment by marquiz** [comment]
> @kad hmm, qty should be handled by device plugins.

And, the labels would be simpler to use, by just utilising nodeSelector. It requires the label value to be specified so numerical values make it virtually unusable.

**Comment by marquiz** [comment]
I added network controllers to the default list of device classes to detect

**Comment by zvonkok** [comment]
Yes, as a first step only discovering `VENDOR_ID=0x10DE` (NVIDIA) `CLASS_ID=0x0302` 3D display controller where `0x03` is a Display Controller and `0x03` + `02 is a 3D display controller.

I am using the following script [find_nvidia_display_adapter.sh](https://github.com/zvonkok/node-feature-discovery/blob/5781cf7fdffcb72b77304880efa6c2ddd5c895b9/source/gpu/find_nvidia_display_adapter.sh#L1) , that can be easily generalized for any VENDOR_ID and CLASS_ID.

**Comment by marquiz** [comment]
I implemented a more generic solution, please see #168.

> I am not using any Linux commands like `lshw, lspci` because there are e.g Containerized Linux Distributions that do not ship these tools and only a shell is definitely available.

I disregarded those for the same reaseons.


> AFAIU a label for a 3D display controller from NV would look like:
> 
> `nfd-pci-device-0302-10DE-GPU-present` ?
> 
> where users in some kind of database could define the complete DEV_LABEL or only
> the last part of it?

I think we shouldn't probably include any vendor or device database inside NFD. The documentation (README) could (and probably should) have a reference to the PCI Id database, though. What do you think?

**Comment by marquiz** [comment]
> I know that 0x0200 0x1924 is a SolarFlare Network Adapter and 0x300 102b a Matrox VGA card, but as a user I just wanna know if I have a NVIDIA-GPU or a SOLARFLARE-NIC.

On theoretical level, I like the idea. However, in practice I do not like it because the labels would become quite long and ugly. And, easily even exceed the 63 character limit of the label name.

E.g. when using data from the PCI Id repository (what hwdata uses) we would have something like (after sanitizing the vendor name to be used in k8s label):
```
node.alpha.kubernetes-incubator.io/nfd-pci-VGA_COMPATIBLE_CONTROLLER-ADVANCED_MICRO_DEVICES_INC_AMDATI-present
node.alpha.kubernetes-incubator.io/nfd-pci-ETHERNET_CONTROLLER-INTEL_CORPORATION-present
```
Here, the first (AMD) label already is too long and would be rejected by the API server

**Comment by zvonkok** [comment]
You're right, that's ugly. I do not like it either. (I) would like to have a concise label. 

What about having a user specified translation table per default empty?

The people that do not care about would see the hex numbers, people who care, people who know what to look for could create  a `pci.db.conf` and those know that 102b Matrox, 1924 Solarflare ...
```
PCI_ID   107d NVIDIA
CLASS_ID  300 GPU
```
Another scenario where this would help is in the case of Mellonox cards, depending on the firmware you will either have a Infiniband or 40GigE NIC. The admin in this case could create a translation to name the card according to the firmware flashed. 

The discovery of hardware is from my standpoint a multi step process. Supposing we have 100 nodes where one of the nodes has a GPU. I do not want to deploy e.g 100 DevicePlugins just to find out that 99 are failing and only one runs because there is only 1 GPU node. 

1.  NFD shows me what hardware is present with minimal software overhead (no special software needed to discover the hardware) just a `GPU-present`.

2. Now I can deploy specialized PODs/containers to do more thorough discovery with Vendor tools (NVML, OFED, Onload) Fimrware, Software, Hardware version exact type of card ...

3. Deploy workload

**Comment by marquiz** [comment]
> What about having a user specified translation table per default empty?

This could be a future enhancement

> The people that do not care about would see the hex numbers, people who care, people who know what to look for could create a `pci.db.conf` and those know that 102b Matrox, 1924 Solarflare ...

I'd probably try to use nfd config file (`/etc/kubernetes/node-feature-discovery/node-feature-discovery.conf`, introduced in #168)

> ```
> PCI_ID   107d NVIDIA
> CLASS_ID  300 GPU
> ```

Need to support human-readable names for other fields (i.e. device id, subsystem ids), too. And, thus, need to have hierarchical structure similar to hwdata.

> The discovery of hardware is from my standpoint a multi step process. Supposing we have 100 nodes where one of the nodes has a GPU. I do not want to deploy e.g 100 DevicePlugins just to find out that 99 are failing and only one runs because there is only 1 GPU node.

Yeah, I agree. This is certainly a valid and meaningful use case, currently.

**Comment by jeremyeder** [comment]
Pretty simple feedback - I don't think having PCI IDs as labels makes sense from a user experience perspective.  I can't imagine what the user documentation would read if that were how this was implemented.

**Comment by marquiz** [comment]
> I don't think having PCI IDs as labels makes sense from a user experience perspective.

Do you mean raw PCI IDs like `nfd-pci-030000_10de.present` (Nvidia GPU) or PCI IDs in general? Don't you think the device plugin use case sketched above is valid?

> I can't imagine what the user documentation would read if that were how this was implemented.

NFD user documentation or something else?

**Comment by marquiz** [comment]
@jeremyeder any comments on the above?

**Comment by jeremyeder** [comment]
If NFD finds an NVIDIA GPU, what would the user's podspec have to contain?

**Comment by jeremyeder** [comment]
OK, so just confirming how this would work:

* NFD daemonset runs on a node, finds a GPU and writes the label according to this PR.

* The daemonset nodeselector for the device plugin will need to specify 
```node.alpha.kubernetes-incubator.io/nfd-pci-0300_10de.present: true```

* A user will specify in their pod spec Requests whatever the device plugin writes to the node capacity, e.g.:
```nvidia.com/gpu=N```

Confirm?

**Comment by kad** [comment]
@jeremyeder yes, that is the idea.

**Comment by jeremyeder** [comment]
OK, it solves our DP label selector bootstrapping issue with only a slight drawback in human readability of the label itself, but that is not what the user interacts with.

**Comment by kad** [comment]
Missed the old comment:
> > @kad hmm, qty should be handled by device plugins.

That is correct. For workload placement DPs should be used.
Showing number can help cluster admin to quickly view how many physical PCI devices present on the node. DP can report it differently, based on many factors (e.g. number of SR-IOV VFs).

> And, the labels would be simpler to use, by just utilising nodeSelector. It requires the label value to be specified so numerical values make it virtually unusable.

To use for selecting nodes for e.g. DP DaemonSet in case of number, it is possible to use `nodeSelectorTerms` with `operator: Exists`. Value of the label would not matter in that case.

**Comment by kad** [comment]
> OK, it solves our DP label selector bootstrapping issue with only a slight drawback in human readability of the label itself, but that is not what the user interacts with.

Most of the NFD labels are not supposed to be consumed by humans :) rather by DaemonSets.

**Comment by marquiz** [comment]
PCI detection is now supported in master as #168  was merged.

Do you think that the support for human-readable names would be useful and worth implementing?

**Comment by flx42** [comment]
My first reaction is that it doesn't matter to have an human-readable name.

But, what if a user wants to deploy the device plugin but they are not using `node-feature-discovery`? If we add the `nodeSelector` in https://github.com/NVIDIA/k8s-device-plugin/blob/v1.11/nvidia-device-plugin.yml, it will fail.

I see two options:
1) We ship two versions of our device plugin pod spec. One with the nfd `nodeSelector`, one without (or we templatize it somehow).
2) We ask users to manually label their GPU nodes if they don't use nfd. In this case a human-readable label would be valuable.

**Comment by marquiz** [comment]
> 1. We ship two versions of our device plugin pod spec. One with the nfd `nodeSelector`, one without (or we templatize it somehow).

NFD is kind of optional optimization, so probably you could provide two versions of the spec or comment the node selector out and refer to it in the documentation?


> 2. We ask users to manually label their GPU nodes if they don't use nfd. In this case a human-readable label would be valuable.

I don't think this is a good option because, as envisioned above, NFD wouldn't provide human-readable names out-of-the box (as we don't want to start maintaining a device id database in nfd). Rather configuration would be responsibility of the cluster admin (or whoever deploys nfd)

**Comment by marquiz** [comment]
Closing this issue as #168 has been merged. Please open new issue(s) if further enhancements would be desired
