### ISSUE TITLE
Malformed IPv6 address used in topology-update workers

### ISSUE THREAD

**Issue by craigcabrey** [kubernetes-sigs/node-feature-discovery#1727]
**What happened**:

Turning on node-topology-updater crashloops on an IPv6-first cluster.

**What you expected to happen**:

Don't crashloop.

**How to reproduce it (as minimally and precisely as possible)**:

Setup an IPv6 cluster (optionally dual stack, but IPv6 must have priority).

**Anything else we need to know?**:

https://github.com/kubernetes-sigs/node-feature-discovery/pull/1218#discussion_r1185922510

This is where the bug stems from.

```
E0529 21:48:11.522990       1 main.go:66] "error while running" err="failed to detect TopologyManager's policy and scope: failed to get kubelet config from configz endpoint: Get \"https://fdb5:12c1:f8cb:0:dd8f:717d:abc8:f650:10250/configz\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

The IP address needs to have `[]` around the address: `https://[fdb5:12c1:f8cb:0:dd8f:717d:abc8:f650]:10250/configz`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.29.5+k3s1
- Cloud provider or hardware configuration: self hosted
- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 40.20240504.3.0
- Kernel (e.g. `uname -a`): 6.8.8-300.fc40.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by marquiz** [comment]
🤦‍♂️🤦‍♂️🤦‍♂️  Thanks for reporting this issue @craigcabrey 

I put together a quick fix in #1729. PTAL
