### ISSUE TITLE
Mark taints stable

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1733]
**What would you like to be added**:

Remove the *experimental* statements related to taints. Both in the docs and in the code.

**Why is this needed**:

Node tainting has been around since NFD [v0.12](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.12.0). No bugs/issues have been reported (at least in a long while).

**Comment by ArangoGutierrez** [comment]
Done by #1944
