### ISSUE TITLE
Migrate to Community CI By August 1st

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/node-feature-discovery#1747]
Node feature discovery CI still needs migrating, per https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU

You can find jobs listed in:
 
https://github.com/kubernetes/test-infra/blob/master/docs/job-migration-todo.md

(see e.g. jobs with name containing "node-feature-discovery")

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/test-infra/pull/32887

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/test-infra/pull/32887 Merged! 
/close

**Comment by BenTheElder** [comment]
You should probably double check that the e2e job is still working, in particular, it might need some follow-ups.

**Comment by ArangoGutierrez** [comment]
> You should probably double check that the e2e job is still working, in particular, it might need some follow-ups.

you are right, celebrating too fast....
/reopen

**Comment by BenTheElder** [comment]
since it's a postsubmit, we won't know until a PR merges.

I could manually trigger it to run again for an existing merge but with the latest config, let's try that ...

**Comment by BenTheElder** [comment]
https://prow.k8s.io/?job=postsubmit-node-feature-discovery-e2e-test

**Comment by BenTheElder** [comment]
If we check the events for the failed run:

> Error: secret "node-feature-discovery-ci" not found

Whatever this secret was enabling will need to be replicated using only what is provided by the k8s community infra.

I don't have context on what this job attempts to do and why it had a custom secret. Does anyone know what this secret was for?

If it's just to use a GCP project, you can instead rent one from boskos, kubetest(2) provide facilities for this.

it actually kinda looks like https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/scripts/test-infra/test-e2e.sh is doing things on AWS?

**Comment by BenTheElder** [comment]
in which case we should move it to the EKS cluster and figure out how to replicate the infra over there (not my speciality but .. we can reach out in #sig-k8s-infra)

**Comment by marquiz** [comment]
#1763 is the last bit

**Comment by ArangoGutierrez** [comment]
> #1763 is the last bit

Merged! 
we are good to close this @BenTheElder

**Comment by BenTheElder** [comment]
Thanks!
