### ISSUE TITLE
Add support for revisionHistoryLimit to Helm Chart

### ISSUE THREAD

**Issue by reefland** [kubernetes-sigs/node-feature-discovery#1759]
**What would you like to be added**:
Please add support for `revisionHistoryLimit` in the Helm Chart and/or set a reasonable default such as `3`.

**Why is this needed**:
Systems which implement NFD via a Gitops process do not need 10 copies each `ReplicaSet` and `ControllerRevision`. They would never be used for rollback as the git commit would be reverted instead. Having a little bit of history for comparison can be handy so a default value of `3` is often reasonable for that and for rollbacks for non-gitops.

(The actual default value NFD wants to use I don't care about.  I just want to be able to override it.)

**Comment by marquiz** [comment]
Thanks @reefland for the suggestion. Makes sense to me.

Feel free to submit a PR in case you're up to it 😉
/help

**Comment by omerap12** [comment]
I can help with that :)
/assign
