### ISSUE TITLE
Change node label name(space)

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#176]
As part of the move from kubernetest-incubator org to kubernetes-sigs org (#175), the node labels (at least the namespace part) would need to be changed. Currently the label namespace/name scheme is `node.alpha.kubernetes-incubator.io/nfd-<source name>-<feature name>`.

There is a proposal about label namespaces in kubernetes/community#300, but that issue is still open, with no discussion lately.

Some questions:
1. what should be the "base" namespace, that is:
    - `<prefix>.sigs.kubernetes.io`
    - `<prefix>.kubernetes-sigs.io`
    - something else?
2. should we move the "nfd" from label name to the namespace part, that is e.g.:
    - `<prefix>.nfd.sigs.kubernetes.io/<source name>-<feature name>` 
    - `<prefix>.node-feature-discovery.sigs.kubernetes.io/<source name>-<feature name>`
3. is the `node` prefix we currently have useful, or should we drop that, e.g.:
    - `alpha.nfd.sigs.kubernetes.io/...`
    - `node.alpha.sigs.kubernetes.io/nfd-...`

**Comment by jeremyeder** [comment]
I think ```nfd.sigs.kubernetes.io/<source name>-<feature name>``` should be sufficient?

**Comment by marquiz** [comment]
> I think `nfd.sigs.kubernetes.io/<source name>-<feature name>` should be sufficient?

That looks good to me.

Is there any value in the `alpha` prefix? That is. indicating the "stability" of the labels, with alpha saying that this still might change

**Comment by jeremyeder** [comment]
Unless there is a well-known convention or policy for embedding the feature support status, I'd say no value in having it.

**Comment by marquiz** [comment]
> Unless there is a well-known convention or policy for embedding the feature support status, I'd say no value in having it.

I'm not aware of any official guidelines or policy about this. Could we come up with one?

**Comment by jeremyeder** [comment]
Raise it on the kubernetes-dev list or a sig-architecture call?

**Comment by marquiz** [comment]
> Raise it on the kubernetes-dev list or a sig-architecture call?

K, I'll do that.

The main reason for asking this is that I don't know the history, and, there currently is the `alpha` prefix used in NFD labels, and, `beta` prefix in some kubelet default labels like `beta.kubernetes.io/os` (vs. `kubernetes.io/hostname` which looks like GA).

**Comment by marquiz** [comment]
The subject was discussed on kubernetes-dev mailing list:
https://groups.google.com/forum/#!topic/kubernetes-dev/TxPcaDYLMq4

In brief, a common understanding seems to be neither the api status (e.g. `alpha`) nor `sigs` should be part of the label namespace. In the end, there were two suggestions: `feature.node.kubernetes.io` and `nfd.node.kubernetes.io`

The former is more is generic and better describes what the label is about (a *feature* of a *node*), and thus, possibly easier to understand by the end user. However, having *nfd* as part of the (full) label name is important so that NFD can reliably remove old deprecated/out-of-date feature labels when doing re-labeling. Thus, I think the two alternatives (for the full label name) to choose between would be:
- `feature.node.kubernetes.io/nfd-<source name>-<feature name>`, e.g. <br/>`feature.node.kubernetes.io/nfd-cpuid-AVX`
- `nfd.node.kubernetes.io/<source name>-<feature name>`, e.g. <br/>`nfd.node.kubernetes.io/cpuid-AVX`

**Comment by lmdaly** [comment]
I'm a +1 feature.node.kubernetes.io/nfd-<source name>-<feature name. This conveys to me a node feature label, and then the project that is advertising the feature.

**Comment by MarSik** [comment]
I would actually vote for the feature.node.kubernetes.io/<label> myself. The <label> can be <source name>-<feature name> for the built in sources too. I do not think a node feature label should encode the project reporting it. I would rather "standardize" the features themselves and let the user decide how to provide the labels (NFD, manual configuration, different tool...).

As for the local source (https://github.com/kubernetes-incubator/node-feature-discovery/pull/148), I would actually let the hook scripts return the full <label> names to make the label independent on the project/script reporting it completely. That way the hooks can even replace a detection method that might not be appropriate for some environments or hosts and still provide the same feature labels.

**Comment by MarSik** [comment]
Those are good points.

1) Maybe you could add annotations together with labels that would indicate the labels that were added by the NFD service. That way you will have the list of managed labels without compromising the labels' purity / independence.

2) We are working on cpu flags / cpu families detection based on what QEMU knows about the CPU. The `nfd-` prefix would basically prevent us from switching between static configuration, custom hook and separate service if that is ever written. The admin of a node should also know what he is doing when installing a custom hook, so I am not worried here.

**Comment by marquiz** [comment]
Thanks for the feedback and ideas.

> 1. Maybe you could add annotations together with labels that would indicate the labels that were added by the NFD service.

This might actually be a really good idea that I hadn't thought. I'll give it a try. Do you know what is the size limit for annotation data?

Probably NFD version (that created the labels) should be an annotation as well, instead of a label(?)


> 2\. We are working on cpu flags / cpu families detection based on what QEMU knows about the CPU. The `nfd-` prefix would basically prevent us from switching between static configuration, custom hook and separate service if that is ever written. The admin of a node should also know what he is doing when installing a custom hook, so I am not worried here.

Using annotations would cover this use case as well. And, if we'd not choose using those, we could add support for the hooks to be able to remove labels (e.g. write `<label>-` in stdout)

**Comment by MarSik** [comment]
About the NFD version label, yes I think is it common to express that using annotations.

**Comment by marquiz** [comment]
I wrote an initial implementation - submitted in #187

**Comment by marquiz** [comment]
#187 was merged. Label naming scheme now is:
```
feature.node.kubernetes.io/<source name>-<feature-name>
```
