### ISSUE TITLE
Change nfd container image registry

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#177]
Moving from kubernetest-incubator org to kubernetes-sigs org (#175), it would probably be logical to also move the nfd images to a new registry, in order to reflect the new host organization.

We currently use https://quay.io/repository/kubernetes_incubator/node-feature-discovery. Does the registry host matter (e.g. gcr.io vs quay.io)? Is there some kubernetes(-sigs) project under quay.io that we could possibly use?

**Comment by marquiz** [comment]
Still relevant

/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by marquiz** [comment]
Need to get back to this in the near future
/remove-lifecycle stale

**Comment by Ethyling** [comment]
@marquiz Do we have any update on this?

**Comment by marquiz** [comment]
Not really :grimacing:

But, thanks for poking this. I think we could ask for a gcr.io image repository (https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io). In the first stage we would use the gcr.io repos but still do image builds in travis-ci (plus the k8s.io image promoter for releases). In the second stage we could enable automatic gcr builds. I'll create PRs for the first stage

**Comment by marquiz** [comment]
I created kubernetes/k8s.io#524

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/k8s.io/pull/524 has been merged, we can move one here :)

**Comment by marquiz** [comment]
From the perspective of our project everything is basically now in place. I was able to push and promote the previous release: you can try out {asia,eu,us}.gcr.io/k8s-artifacts-prod/nfd/node-feature-discovery:v0.5.0

However, I'd still wait until the [k8s.gcr.io domain flip](https://groups.google.com/forum/#!msg/kubernetes-sig-release/ew-k9PEBckQ/T7dFepHdCAAJ) has been completed so that we can use `k8s.gcr.io/nfd/node-feature-discovery`, instead of relying on three region-specific `{asia,eu,us}.gcr.io/k8s-artifacts-prod/nfd/node-feature-discovery` repos

**Comment by marquiz** [comment]
The domain flip has been rolled out and `k8s.gcr.io` is working for us, i.e. pulling `k8s.gcr.io/nfd/node-feature-discovery:v0.5.0` should succeed. 

I now have a PR to publish the latest release (v0.6.0) in `k8s.gcr.io`.
https://github.com/kubernetes/k8s.io/pull/1099

After that we should be able to change our references of `quay.io` to `k8s.gcr.io` and finally close this issue.

**Comment by marquiz** [comment]
This is now complete. Staging images are found at:
`gcr.io/k8s-staging-nfd/node-feature-discovery:<TAG>`

Release images at:
`k8s.gcr.io/nfd/node-feature-discovery:<TAG>`
