### ISSUE TITLE
Discovery of PMEM / NVDIMM devices

### ISSUE THREAD

**Issue by kad** [kubernetes-sigs/node-feature-discovery#178]
It would be good if NFD will be able to detect and report presence of PMEM devices on the node.

Minimal way to detect that can be presence of entries under `/sys/class/nd/` hierarchy.

Label can be something like `nfd-pmem.present`

**Comment by marquiz** [comment]
I was thinking about the feature source. Would it be more logical to have a separate source (like *pmem* that you suggested), with a label like `nfd-pmem-present`, or, put it under currently existing feature source such as *memory* or *storage*, having label like `nfd-storage-pmem.present`?

**Comment by marquiz** [comment]
Detection of nvdimm hardware was merged in #214. Closing this issue
