### ISSUE TITLE
Publish false status of pstate-turbo

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#182]
For some workloads it may be important that Intel Turbo Boost technology has been disabled. Just checking that the `nfd-pstate-turbo` is not `true` does not necessarily be enough. The label may be missing for various reasons, e.g. the detection failed or the feature source has been disabled in NFD. 

Changing the `pstate` feature source to give the `turbo` label a `false` value in case we detect that turbo has been disabled would thus improve certainty that workloads (with turbo anti-affinity) are indeed scheduled correctly.

Also, README must be updated to reflect the change.

**Comment by marquiz** [comment]
I have an implementation, just need to rebase and push it

/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by marquiz** [comment]
Implemented in #266 . Rewrote a completely new patch as this was easier than rebasing the earlier badly outdated version...

**Comment by Ethyling** [comment]
@marquiz I think we can close this issue.

**Comment by marquiz** [comment]
True, thanks for noticing this
