### ISSUE TITLE
the link to feature gates documentation is broken

### ISSUE THREAD

**Issue by ChaoyiHuang** [kubernetes-sigs/node-feature-discovery#1820]
**What happened**:
when click the link [feature gates documentation](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/feature-gates.md) in the [docs/reference/master-commandline-reference.md](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/reference/master-commandline-reference.md), the link is broken.

Because the "feature gates documentation" file has already been moved to the folder docs/reference

**What you expected to happen**:
the link will lead to the file "feature gates documentation"

**How to reproduce it (as minimally and precisely as possible)**:
click the "feature gates documentation" link in [docs/reference/master-commandline-reference.md](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/reference/master-commandline-reference.md)

**Anything else we need to know?**:
NA

**Environment**:
- github repository: https://github.com/kubernetes-sigs/node-feature-discovery/

**Comment by omerap12** [comment]
yeah why not .
/assign
