### ISSUE TITLE
node-feature-discovery-workers sometimes fail and restart on the new joined nodes

### ISSUE THREAD

**Issue by ugur99** [kubernetes-sigs/node-feature-discovery#1828]
**What happened**:
Hi! We noticed that node-feature-discovery-workers pods sometimes fail with the following error on the new nodes and even though we restart them, it takes couple of minutes to synchronize all the related labels. I'm not so sure how the whole node-feature-discovery works, so maybe you can help us to find the root cause of this.

```text
E0808 09:07:46.113306       1 main.go:83] "error while running" err="failed to advertise features (via CRD API): failed to update NodeFeature object \"gpu.worker12\": Operation cannot be fulfilled on nodefeatures.nfd.k8s-sigs.io \"gpu.worker12\": StorageError: invalid object, Code: 4, Key: /registry/nfd.k8s-sigs.io/nodefeatures/node-feature-discovery/gpu.worker12, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 5576298f-79f6-40af-9ff0-ffd5944bd794, UID in object meta: "
```
**What you expected to happen**:
I expect node-feature-discovery would work as it is assigned to the new node.

**How to reproduce it (as minimally and precisely as possible)**:
-
**Anything else we need to know?**:
helm chart version is `0.15.3`
**Environment**:
- Kubernetes version (use `kubectl version`): v1.29
- Cloud provider or hardware configuration: onprem
- OS (e.g: `cat /etc/os-release`): -
- Kernel (e.g. `uname -a`): -
- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others: -

**Comment by marquiz** [comment]
@ugur99 we've seen no reports on this before. On a quick search this looks like some (caching) issue in the kubernetes apiserver (ref e.g. https://github.com/kubernetes/kubernetes/issues/82130). You could try restarting the apiserver and see if the problems goes away(?)

**Comment by ugur99** [comment]
yep you are right! Also found [this](https://github.com/kubernetes/kubernetes/issues/124347); sorry for my quick reaction. I should have done more research before creating the issue. Thanks for the fast support.
