### ISSUE TITLE
Can not deploy NFD plain manifest via README.md with the usage of kubectl kustomize

### ISSUE THREAD

**Issue by jz543fm** [kubernetes-sigs/node-feature-discovery#1877]
`kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.16.4`

`no matches found: https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.16.4`

I prefer plain Yaml

**Comment by marquiz** [comment]
Hi @jz543fm. What kubectl version are you using? I suspect you have a very old version that doesn't support kustomize

**Comment by jz543fm** [comment]
`Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3`

**Comment by marquiz** [comment]
Hmm, really strange. Worksforme. What could be the issue :thinking:

**Comment by jz543fm** [comment]
What kubectl version are you using?

**Comment by marquiz** [comment]
> What kubectl version are you using?

I have v1.30 and v1.31.

> I would prefer, if there could be found plain manifest for future, if it would be possible, kustomize with different versions with many users is not very good option, or maybe in the doc should be mentioned what version of kustomize works

This should really be no problem. Kustomize (with the remote refs) has been supported since kubectl v1.21 or so. I think it is reasonable to ask people to use kubectl v1.21 or later.

Could it be network access somehow (http proxy?). What shell are you using?

**Comment by jz543fm** [comment]
The problem was ' ', when I use it, it works...

**Comment by jz543fm** [comment]
I am using zsh and bash, I can try it tomorrow on bash too

**Comment by jz543fm** [comment]
Also bash had issue with it, thanks for fix
