### ISSUE TITLE
Dead links to feature-gates documentation

### ISSUE THREAD

**Issue by uniemimu** [kubernetes-sigs/node-feature-discovery#1971]
The documentation link for feature gates is dead in this page:
https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/reference/master-commandline-reference.html#-feature-gates

Same issue is also present with the worker page:
https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/reference/worker-commandline-reference.html#-feature-gates

The actual dead link is this:
https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/feature-gates.md

It should end up pointing to something like: https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/reference/feature-gates.html

What you get is this:
404
File not found

**Comment by marquiz** [comment]
Fixed by #1980 
/close
