### ISSUE TITLE
Failed to build node-feature-discovery docker image.

### ISSUE THREAD

**Issue by shunianyin** [kubernetes-sigs/node-feature-discovery#198]
I get Error when I building node-feature-discovery.
It shows error like
[WARN]  Unable to checkout golang.org/x/net
[ERROR]  Update failed for golang.org/x/net: Cannot detect VCS
[WARN]  Unable to checkout golang.org/x/text
[ERROR]  Update failed for golang.org/x/text: Cannot detect VCS
[WARN]  Unable to checkout github.com/gogo/protobuf
[ERROR] Update failed for github.com/gogo/protobuf:Unable to get repository : Cloning into 'root/.glide/cache/src/https-github.com-gogo-protobuf'...
error: RPC failed; result=18.HTTP code = 200
fatal:  The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
: exit status 128
[ERROR] Failed to install: Cannot detect VCS
Cannot detect VCS
Unable to get repository : Cloning into 'root/.glide/cache/src/https-github.com-gogo-protobuf'...
error: RPC failed; result=18.HTTP code = 200
fatal:  The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
: exit status 128
The command '/bin/sh -c glide install --strip-vendor' returned a non-zero code: 1
make: *** [image] Error 1

**Comment by marquiz** [comment]
I'm not able to reproduce. Works fine for me in linux (with docker v17.09) and macOS (with docker 18.06).

Are you behind a corporate proxy?

**Comment by shunianyin** [comment]
yes. I connect to outer net by a corporate proxy.  Is that the reason for the failure?

**Comment by marquiz** [comment]
Probably. The nfd build-time proxy settings were changed recently (#188) because the setup caused problems in some situations, and, docker now recommends specifying proxy settings in client conf.

Which version of docker are you using? Please see https://docs.docker.com/network/proxy/ for configuring you docker client proxy settings.
