### ISSUE TITLE
Rethink selinux feature source

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#200]
To me, the selinux feature source is a bit narrow in scope and would probably be better combined with some other feature source, or, renamed. I see three options:
1. Move it under the `kernel` feature source, i.e. the label would become `kernel-selinux.enabled`
2. Move it under the `system` feature source, i.e. the label would become `system-selinux.enabled`
3. Rename the feature source to widen its scope (for future), e.g. `security-selinux.enabled`

This would be a good time to make the change as all the labels have changed, anyway. Of course, this would have minor impact on the `--sources` command line option, too, but I don't think it would affect many users.

**Comment by marquiz** [comment]
Of course, this could be a good point to think about the feature source and label hierarchy even more widely. The current set of feature sources (and thus, labels too) is a bit arbitrary, and they could probably be organized in a more systematic way. An example would be having one source per type of hw (plus one for kernel sw and one for userspace sw), e.g. combining all CPU-related features under one feature source and similarly for others. We could have something like (with the current set of features):
- `cpu-hardware_multithreading`
- `cpu-cpuid.*`
- `cpu-pstate.turbo`
- `cpu-rdt.*`
- `iommu-enabled`
- `kernel-config.*`
- `kernel-selinux.enabled`
- `kernel-version.*`
- `memory-numa`
- `pci-*.present`
- `storage-nonrotationaldisk`
- `system-os_release.*`

Is this something that we want to think about, bringing it up in SIG-node??

**Comment by marquiz** [comment]
@jeremyeder: any thoughts on this?

**Comment by jeremyeder** [comment]
To your original question about selinux, we're fine with moving it.  Since the selinux enforcement occurs in the kernel, I think kernel-selinux.enabled feels more natural.

As far as the larger scope of feature namespaces ... if you have a more detailed proposal(s), then sure - please share in the community.

**Comment by marquiz** [comment]
> To your original question about selinux, we're fine with moving it. Since the selinux enforcement occurs in the kernel, I think kernel-selinux.enabled feels more natural.

👍 I prefer `kernel-selinux.enabled` myself, too. I'll submit a PR, soon.


> As far as the larger scope of feature namespaces ... if you have a more detailed proposal(s), then sure - please share in the community.

I feel that it would be worth pursuing a bit more systematic (or "standardized") naming scheme for the feature labels. And, as with the selinux label, this would be a good time to go for the change – before the next release as all labels are changing, anyway. I'll split out a separate issue on this, and, start from the sig-node mailing list, for example

**Comment by marquiz** [comment]
> I'll split out a separate issue on this,

Created #207

**Comment by marquiz** [comment]
Implemented in #206, closing this issue
