### ISSUE TITLE
create an operator for NFD

### ISSUE THREAD

**Issue by jeremyeder** [kubernetes-sigs/node-feature-discovery#205]
Hey - as discussed at KubeCon f2f, we'd like to contribute an NFD operator to this repo.  We'll send PRs soon.  Just wanted to make sure maintainers saw this and linked it mentally to our f2f agreement.

/cc @zvonkok @derekwaynecarr @balajismaniam @marquiz

**Comment by lmdaly** [comment]
+1 on an operator for NFD hosted here

**Comment by marquiz** [comment]
@zvonkok, any update on this? Are you planning to upstream the work you've been doing on this?

**Comment by zvonkok** [comment]
@marquiz yes I am planning on upstreaming, we would need a new repository
- nfd-operator
- node-feature-discovery-operator 

If we have that I can create a PR and we can work on it. WDYT?

**Comment by marquiz** [comment]
I'm not an expert on operators, so I believe you if you say we need a separate repo for that 😉

On the repo naming, I think **node-feature-discovery-operator** would be more logical (even though I like **nfd-operator** because of the compact length).

I can request a new repo under kubernetes-sigs org

/remove-lifecycle rotten

**Comment by zvonkok** [comment]
Definitely an own repository, the operator its an own entity in the cluster, managing the node-feature-discovery container, own set of Makefiles, Dockerfiles, configuration files etc. 

How the downstream looks like: https://github.com/openshift/cluster-nfd-operator

**Comment by marquiz** [comment]
Requested for a new repo, see kubernetes/org#957

**Comment by marquiz** [comment]
Initial version of the [Node Feature Discovery Operator](https://github.com/kubernetes-sigs/node-feature-discovery-operator) has now been merged. Closing this issue
