### ISSUE TITLE
New hierarchy of feature sources

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#207]
The current set of feature sources (and labels), is somewhat arbitrary, reflecting the (commit) history of the project – typically new features have been implemented as a completely new feature source. However, the feature sources and their associated labels could be organized in a more systematic way, providing a bit more standardized and logical hierarchy of the feature labels.

For example, we could have one source per type of hw (plus one for kernel sw and one for userspace sw). An example, how the current set of feature sources and labels could be transformed:

* cpu
  * hardware_multithreading
  * cpuid.&lt;cpuid flag&gt;
  * pstate.turbo
  * rdt.&lt;rdt feature&gt;
* iommu
  * enabled
* kernel
  * config.&lt;kconfig option&gt;
  * selinux.enabled
  * version.&lt;version component&gt;
* memory
  * numa
* pci
  * &lt;device&gt;.present
* storage
  * nonrotationaldisk
* system
  * os_release.&lt;version field&gt;

This issue was split out from #200. Similar to that, this would be a good time to go for the change as all the feature labels have changed after the repo migration, anyway.

**Comment by jeremyeder** [comment]
Not sure we have a lot to say about this since we're not depending on it yet, and thus can adapt quickly to any changes. /cc @zvonkok

**Comment by marquiz** [comment]
Tried to consult [SIG-node mailing list](https://groups.google.com/forum/#!topic/kubernetes-sig-node/R-Q6XTAs-EI) on this

**Comment by marquiz** [comment]
#217 has an implementation re-organizing CPU related features

**Comment by Ethyling** [comment]
I think #217 solved this issue

**Comment by marquiz** [comment]
Yes, it did – I don't have any other changes in mind
