### ISSUE TITLE
Ignore non-executable files in /etc/kubernetes/node-feature-discovery/source.d

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery#208]
If a sidecar container drops a feature detection hook into `/etc/kubernetes/node-feature-discovery/source.d` and needs additional configs or setting via a file (that is e.g. created during runtime) NFD should ignore files that are not executables.

Maybe print out a warning that a specific file is not executable, could be, the developer just forgot to set the executioin flag, or dropped some configs data in there. 

@jeremyeder

**Comment by marquiz** [comment]
Currently, NFD prints out an error like
```
ERROR: source hook 'foo' failed: fork/exec /etc/kubernetes/node-feature-discovery/source.d/foo: permission denied
```

Do you think this is misleading? Maybe the logging could be improved, printing out a warning about non-executable and non-regular files. You could drop config files in a separate subdir, though, in order to avoid errors/warnings(?)

**Comment by zvonkok** [comment]
Ah haven't thought about the directory to put the config in there. No it was not misleading, may just irritate "someone" and thinking that some went wrong. 

If NFD keeps working even with that error than its completely fine. Lets do not complicate. 
I will use a directory for configs. Thanks!

**Comment by marquiz** [comment]
OK. NFD works fine despite the error. Log messages and the logic could probably be improved. Patches are welcome 😄 

Nevertheless, I made a quick effort to address that in the documentation, see #212
