### ISSUE TITLE
Detect architecture os/package manager agnostic

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery#213]
https://github.com/kubernetes-sigs/node-feature-discovery/blob/5acd22ac6b9589fb5dc2e4a5a9fc65554b7d44d0/Dockerfile#L12

Could we use here a architecture detection that is os/package manager agnostic ?
What about: 
` RUN case $(uname -m) in `

@marquiz WDYT?

/cc @jeremyeder

**Comment by marquiz** [comment]
@zvonkok: definitely, that would be better.

But, I'd like to get rid of that intel-cmt-cat/rdt-discovery stuff, entirely: #189

**Comment by marquiz** [comment]
Should be fixed as #189 was merged, closing this issue
