### ISSUE TITLE
default set of node labels is too verbose

### ISSUE THREAD

**Issue by jeremyeder** [kubernetes-sigs/node-feature-discovery#222]
Heya,

Initial impressions of NFD as we expose more folks to it:

"Some folks here saw the cpuid labels from nfd and are asking if we really need all of them.   They say it makes the kubectl describe node output ugly."

While I don't see any technical problems with the amount of labels, I wonder if there's a way we can cut down on how many rows cpuid writes.  Maybe we could make the default set of labels configurable somehow, too?

For example, as of now, from the default set of cpuid labels, we only have known use-cases for hyperthreading and avx2 (could change over time).

**Comment by marquiz** [comment]
I think this makes sense. I think most of the cpuid labels are not interesting and just clutter the "label space". And, some of them are outright misleading. E.g. `cpuid-HTT` and `cpuid-SGX` only indicate whether these capabilities are supported by the cpu hardware (which is probably not interesting to the end user), and do NOT tell anything whether these technologies have actually been **enabled** in the system.

One way to solve this would be to make the cpuid feature source in nfd configurable. E.g. by adding `blacklist` (and `whitelist`?) configuration option. By default, we would blacklist "the uninteresting" flags

**Comment by marquiz** [comment]
I wrote an initial implementation, see #224

**Comment by marquiz** [comment]
Fixed in #224
