### ISSUE TITLE
Adding a source that reads files in a directory

### ISSUE THREAD

**Issue by Ethyling** [kubernetes-sigs/node-feature-discovery#226]
Hi,

We are currently working on labelling nodes depending on Nvidia GPUs.

To do so, we use the `local` source. As we need to get some information about
the GPUs using the Nvidia driver, we have another pod running on the host with
all the tools we need to get them. This pod's job is simply to get the
information we need and write them in a file. After this, we are using a simple
shell script as a hook in NFD doing a `cat` on this file. This seems weird to
execute a shell script to get the content of some files instead of just reading
them. An idea could be to add another source which will read files in a directory
and get labels from them.

We would like to get your opinion about this.

Thank you!

**Comment by marquiz** [comment]
I'm open to this as there seems to be a clear use case.

I'd  probably add this support to the existing `local` source. E.g. just specify a separate directory (similar to the hooks dir, e.g. `/etc/kubernetes/node-feature-discovery/features.d/`) that is expected to have files containing feature labels. The file format would be identical to the expected output of hooks.

**Comment by Ethyling** [comment]
Sounds good to me. I can do the PR if you want?

**Comment by marquiz** [comment]
Sure, patches are welcome, of course! 😄

**Comment by Ethyling** [comment]
@marquiz Here it is. Do not hesitate to tell me if something could be done in a better way.
