### ISSUE TITLE
Allow to change labels' prefix

### ISSUE THREAD

**Issue by Ethyling** [kubernetes-sigs/node-feature-discovery#227]
Hi,

Currently the labels' prefix is fixed to `feature.node.kubernetes.io/`. As we
would like to add some specific Nvidia labels (i.e. labels that are not
standard node features, but specifics to nodes with Nvidia GPUs), it seems less
confusing to be able to change this prefix to something like `nvidia.com/`.

For example, the labels would be something like:
`nvidia.com/family`
`nvidia.com/cuda-version`

What do you think about this?

Thank you!

**Comment by zvonkok** [comment]
Have a look at the docs for local: 

> However, if the <name> printed by the hook starts with a slash (/) it is used as the label name as is, without any additional prefix. This makes it possible for the hooks to fully control the feature label names, e.g. for overriding labels created by other feature sources.

If your hook prints out `/nvidia.com/family` it will be not prefixed.

**Comment by marquiz** [comment]
Actually, by using the slash you're still not able to override the namespace. Originally, that was a conscious design choice to limit NFD's "labeling power" into the `feature.node.kubernetes.io` namespace.

In principle, I'm not against the idea of allowing the hooks to label other namespaces. We just need to be careful about that. I think that this could be merged after #204 has been solved. Then, nfd-master would have control over which namespaces can be used. And, we must agree what format to use in the hook output and `feature-labels` annotation to support this use case.

**Comment by Ethyling** [comment]
Sounds good to me. As I understood, the idea is to add a whitelist of allowed namespaces in nfd-master?

Concerning the format, we can simply consider that if there is a `/` in a label name which is not the first character, then we should not add the NFD prefix. What do you think about this?

**Comment by marquiz** [comment]
> As I understood, the idea is to add a whitelist of allowed namespaces in nfd-master?

Yes, I think that should be the central "gatekeeper"

> Concerning the format, we can simply consider that if there is a `/` in a label name which is not the first character, then we should not add the NFD prefix. What do you think about this?

I was thinking about that, too. It would be kind of simple and neat.

Just thinking aloud: I wonder if there would be need to override labels without a namespace (i.e. label like simple `foo=bar`)? Probably not, better to treat those as user-defined labels(?) Or if we really want to support those as well, they would be defined with two leading slashes like `//foo=bar`.

What do you think?

**Comment by Ethyling** [comment]
> Just thinking aloud: I wonder if there would be need to override labels without a namespace (i.e. label like simple `foo=bar`)? Probably not, better to treat those as user-defined labels(?) Or if we really want to support those as well, they would be defined with two leading slashes like `//foo=bar`.

As we will use namespaces to control which label can be added to the nodes, I think that we shouldn't allow labels without namespace. The only way to do that is to add an option to specify "allow empty namespace" on nfd-master, and I don't think it's a great idea. If a user wants to use NFD to push a user-defined label, he can just use its own namespace and allow it on nfd-master.

**Comment by marquiz** [comment]
Yup. That can be left as a possible future extension if there really would be need for this

**Comment by Ethyling** [comment]
I was looking to add this feature in NFD and I found that the function `filterFeatureLabels` defined in `cmd/nfd-master/main.go:232` is no longer used, as all the `labelWhiteList` stuff in the master. Do we want to keep the whitelisting of labels only on worker and remove all from the master and just have namespace whitelisting on the master ?

**Comment by Ethyling** [comment]
@marquiz I would like to have your opinion about this:

If a label respect the format `<ns>/<name>=<value>` in the local source, do we still want to add the filename and generate the label `<ns>/<file>-<name>=<value>`? If so, the format `/<ns>/<name>=<value>` would generate the label `<ns>/<name>=<value>`?

Another idea would be to consider that if there is a namespace in the label name, we let it as it.

What do you think?

**Comment by marquiz** [comment]
> I was looking to add this feature in NFD and I found that the function `filterFeatureLabels` defined in `cmd/nfd-master/main.go:232` is no longer used, as all the `labelWhiteList` stuff in the master. Do we want to keep the whitelisting of labels only on worker and remove all from the master and just have namespace whitelisting on the master ?

Woops, that is an unintentional mistake on my part 😬 Really need to widen the unit test coverage...

I think we could keep whitelisting in master, it would allow flexibility to have strict control of "label space" in both ends. That was my original idea. I'll submit a patch to fix that

**Comment by marquiz** [comment]
> Another idea would be to consider that if there is a namespace in the label name, we let it as it.

This is probably more logical. Adding file name in case of `<ns>/<name>=<value>` seems a bit unintuitive. Either we treat `<ns>/<name>=<value>` and `/<ns>/<name>=<value>` alike, or fail in the former case

**Comment by Ethyling** [comment]
> > Another idea would be to consider that if there is a namespace in the label name, we let it as it.
> 
> This is probably more logical. Adding file name in case of `<ns>/<name>=<value>` seems a bit unintuitive. Either we treat `<ns>/<name>=<value>` and `/<ns>/<name>=<value>` alike, or fail in the former case

I agree with this. I think we should just ignore the leading slash in case there is another one in the label name. I'll make the change on my PR
