### ISSUE TITLE
README: clarify the feature diff between latest NFD release and master branch

### ISSUE THREAD

**Issue by cbf123** [kubernetes-sigs/node-feature-discovery#233]
The docker image at quay.io/kubernetes_incubator/node-feature-discovery seems to be missing the "nfd-master" and "nfd-worker" binaries.  I tried both the 0.3.0 and 0.2.0 versions.

When building my own image from the Dockerfile, it seems to work okay.

**Comment by marquiz** [comment]
That's because the new feature hasn't been released, yet. It will be part of the next release #202

**Comment by cbf123** [comment]
This should maybe be highlighted in the documentation somewhere.  As it stands, if you download the source code and follow the "getting started" steps in the README it doesn't work.

**Comment by cbf123** [comment]
As a suggestion, it might make sense to have the README instructions actually work for someone downloading the codebase.  The simplest solution (from an end user perspective) would be to have a "devel" docker image that works with the current codebase but can get updated at any time.

If there's no "devel" docker image then the instructions should specify that you need to build your own image and edit the kubernetes resource files to specify the custom image rather than the 0.3.0 docker image (that doesn't work with the latest codebase).

**Comment by marquiz** [comment]
Thanks for the suggestions.

Regarding a *devel* image, I have created a PR just for that, see #160. That hasn't got too much attention, so far

**Comment by Ethyling** [comment]
Fixed in #243 I think

**Comment by marquiz** [comment]
> Fixed in #243 I think

I would say so.

@cbf123, please re-open if you think this is not enough. Regarding devel images, see #160

**Comment by cbf123** [comment]
This looks much better for a new user.  Thanks.
