### ISSUE TITLE
README and/or CONTRIBUTING are missing information on how to contact devs

### ISSUE THREAD

**Issue by cbf123** [kubernetes-sigs/node-feature-discovery#234]
It is not specifically mentioned in either the README or the CONTRIBUTING file what the preferred method is to contact the developers for things that aren't new patches (such as bug reports or even just questions).

**Comment by marquiz** [comment]
Note taken, this would be a worthy addition to README.

**Comment by marquiz** [comment]
The methods would be, I think:
- SIG-node mailing list
- #sig-node slack channel
- opening an issue in Github
- contacting maintainers (currently me) directly
