### ISSUE TITLE
nfd-master: --label-whitelist is not applied

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#237]
nfd-master has command line flag `--label-whitelist` but it does not have any effect, currently, as the filterFeatureLabels() function is not called at all.

We should decide whether to:
1. Fix the functionality so that whitelist gets applied
2. Drop `--label-whitelist` from nfd-master

**Comment by Ethyling** [comment]
I think we need to keep this option on the nfd-master and the nfd-worker. I see at least a use case for each one:
- On the nfd-master, using the `--label-whitelist` option, I can control the labels I want to publish to my nodes.
- On the nfd-worker, using the `--label-whitelist` option, I can control the labels I want to publish to a particular node.

What do you think?

**Comment by marquiz** [comment]
I don't have a strong opinion. Let's keep it if users find it useful.

**Comment by marquiz** [comment]
See #241

**Comment by Ethyling** [comment]
Fixed in #241
