### ISSUE TITLE
Discovery of PMEM regions for PMEM-CSI driver

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/node-feature-discovery#245]
https://github.com/kubernetes-sigs/node-feature-discovery/pull/214 is not quite enough to determine whether PMEM-CSI can run on a node: that PR added detection for PMEM hardware in general, but PMEM-CSI only works on nodes that have been configured for App Direct. This is done by the admin by setting up regions.

We need a new label in addition to `feature.node.kubernetes.io/memory-nv.present`. How about `feature.node.kubernetes.io/memory-appdirect.present`?

**Comment by marquiz** [comment]
Which would be more correct, `memory-appdirect.present` or `memory-nv.appdirect.present` ?

Anyway, I think we can add this for sure. What would be the most convenient way to detect this?

**Comment by pohly** [comment]
Probably `memory-nv.appdirect.present`.

I'm not sure how to best detect that. You'll probably want to do that without depending on additional tools like `ndcntl`, so some investigation will be needed.

**Comment by marquiz** [comment]
> You'll probably want to do that without depending on additional tools like `ndcntl`

Yup

**Comment by marquiz** [comment]
ping @okartau @avalluri, any ideas?

**Comment by marquiz** [comment]
Submitted #254. Please take a look

**Comment by marquiz** [comment]
@pohly, @avalluri, @okartau  Is #254 sufficient? Can this issue be closed?

**Comment by avalluri** [comment]
@marquiz  Though I didn't try myself but seems #254 should suffice for detecting PMEM regions.

**Comment by marquiz** [comment]
I'll close this for now. Please re-open if needed
