### ISSUE TITLE
Node Feature Discovery needs an icon

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery#255]
Desperately needing and wanting an NFD icon. I was playing around and created a simple logo. 

https://github.com/openshift/node-feature-discovery/blob/logo/logo/nfd.pdf

I am testing the NFD Operator integration with OLM in the OperaturHub console, so I wanted to have an appealing presentation when a user wants to install it.

**Comment by marquiz** [comment]
I agree, the project would really need one. I'll try to come up with a proposal of my own 😄

**Comment by marquiz** [comment]
Asked for help from CNCF, see kubernetes/funding#3

**Comment by marquiz** [comment]
A plan I wrote in an email to sig-node mailing list:
* [ ] collect ideas
* [ ] draft few alternative
* [ ] arrange a poll

I think we could collect ideas here in this issue, feel free to shoot 😄

**Comment by zvonkok** [comment]
Nice, we can make some t-shirts, too :)
