### ISSUE TITLE
Question about labels related to an specific hardware

### ISSUE THREAD

**Issue by juliocri** [kubernetes-sigs/node-feature-discovery#263]
Hi there, 

I think this project is awesome, and very helpfully!

Currently I'm testing this feature of labeling on few nodes, and some of them have Intel Quick Assist Technology (QAT), is there an easy way to detect  (with the NFD labels) if the node is with QAT and its type? I would like to see something like:

`feature.node.kubernetes.io/intel_qat=true`
`feature.node.kubernetes.io/intel_qat.device=[c6xx|dh895xcc|c3xxx|d15xx]`

**is this possible to add?**

instead of only having:

`feature.node.kubernetes.io/pci-0300_1a03.present=true`
` feature.node.kubernetes.io/pci-0b40_8086.present=true`

Regards!

**Comment by mythi** [comment]
@juliocri with the following `nfd-worker.conf`:

```
sources:
  pci:
    deviceLabelFields:
      - "device"
```

You get something like: 

```
feature.node.kubernetes.io/pci-37c8.present=true
feature.node.kubernetes.io/pci-37c9.present=true
```

(the README file has instructions to get the config in a configmap. Just remember to create that in `-n node-feature-discovery` namespace that is missing from the doc).

This should be enough

**Comment by marquiz** [comment]
Closing this now
