### ISSUE TITLE
Detect and label CPU Model Name

### ISSUE THREAD

**Issue by lmdaly** [kubernetes-sigs/node-feature-discovery#270]
An addition to the CPU source that adds a string label with the CPU Model name (model name as described under /proc/cpuinfo for eg.)

For example: : "Intel(R) Xeon(R) CPU E5-XXXX"

The reason for this, in heterogeneous clusters, a workload that requires a specific platform feature or configuration needs to run on a particular model type, ensuring that the workload does not end up on an undesirable platform.  

A latency sensitive workload may want to run on the latest architecture to reap the benefits of this new architecture, whereas infrastructure tasks can run on older generations as performance is not as important.

**Comment by marquiz** [comment]
Would it be better to split the information into smaller pieces, like:
```
cpu-cpuinfo.model="79"
cpu-cpuinfo.stepping="1"
cpu-cpuinfo.mhz="2200"
```
I think this would be a more reliable way of ensuring a certain generation of cpu. WDYT?

**Comment by lmdaly** [comment]
Yes, I think this would work,
Or if we could potentially get both in that would be good!

**Comment by ArangoGutierrez** [comment]
++

**Comment by ArangoGutierrez** [comment]
Just to raise awareness of this issue, I want to share a nice library that is targeting this issue

> https://github.com/archspec/archspec

A library to track system architecture aspects incl. processor family & co

**Comment by marquiz** [comment]
Maybe we should just start with model, stepping, and nominal clock frequency

/remove-lifecycle stale

**Comment by ArangoGutierrez** [comment]
I have created a side care container for NFD https://github.com/archspec/archspec-feature-discovery , leverage [ArcSpec](https://github.com/archspec/archspec) library, that give us the name of the microarch

**Comment by MadhavJivrajani** [comment]
Is this issue available to be worked on?

**Comment by marquiz** [comment]
I think with #464 hopefully merged at some point this can be more useful

**Comment by ArangoGutierrez** [comment]
I have an example side-car container that helps with this https://github.com/archspec/archspec-feature-discovery

**Comment by AshwiniGhanwat** [comment]
I am working on this issue. Please assign this issue to me.

**Comment by zvonkok** [comment]
@fabiand Any requirements for kubeVirt I remember that some folks asked about CPU Model for kubeVirt as well?

**Comment by zvonkok** [comment]
@marquiz @ArangoGutierrez  Should we think of a plugin system to enable such third party libs or do you think the side-car container is the way to go to extend NFDs detecting functionality?

**Comment by zvonkok** [comment]
One thing I dislike is that we are still using a hostMount which can cause some pain.

**Comment by zvonkok** [comment]
The other thing we thought about was a grpc plugin system a dedicated channel for extensions.

**Comment by marquiz** [comment]
> @marquiz @ArangoGutierrez Should we think of a plugin system to enable such third party libs or do you think the side-car container is the way to go to extend NFDs detecting functionality?

I would go with side-car for now. And it doesn't need to be a side-car, it can be a separate pod.


> One thing I dislike is that we are still using a hostMount which can cause some pain.

Could you elaborate a bit? What is the pain you're experiencing?


> The other thing we thought about was a grpc plugin system a dedicated channel for extensions.

I wouldn't go there until there is a clear use case and reasoning to do this. It complicates matters - from the plugin's perspective, too, IMO. The extensions/communication is supposed to be node-local in any case.

For this particular issue (CPU detection) we shouldn't need any extra plugins. Just read/parse `/proc/cpuinfo` should do the job

**Comment by digambar15** [comment]
Can someone assign this issue to   @AshwiniGhanwat as she is already working on it.

**Comment by zvonkok** [comment]
@digambar15 @AshwiniGhanwat Any updates on this?

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery/pull/792

**Comment by ArangoGutierrez** [comment]
Hey @lmdaly thanks for this issue, can you verify if changes #792 fit your need, and if so, closing this issue :)

**Comment by marquiz** [comment]
I think lmdaly is not working in this area anymore.
/close
