### ISSUE TITLE
Merging GPU discovery?

### ISSUE THREAD

**Issue by y2kenny** [kubernetes-sigs/node-feature-discovery#275]
I am the author for [AMD GPU Node Labeller](https://github.com/RadeonOpenCompute/k8s-device-plugin/tree/master/cmd/k8s-node-labeller).  I did not realize NFD existed when I wrote my labeller.  Is it a good idea to merge some of feature of my labeller here or should I keep it separate?  Or perhaps change it to use the local/hooks?  (Although that seems to add another layer of complexity.)  I am not clear on  the criteria for adding new feature sources to NFD.

**Comment by rajatchopra** [comment]
If your GPU Node labeler (or is it labeller?) adds vendor specific labels, you should use hooks. Just my opinion.

**Comment by y2kenny** [comment]
Hey Rajat, it was good meeting you at KubeCon.

Is NFD part of k8s by default (or will it be?)  I am wondering if it's worth while to move to use the NFD's hook if this means the user will need to run more than one containers (nfd-worker + labeller to populate the hook) just to label the GPUs.

Labeller for Canadian/UK spelling ;)

**Comment by marquiz** [comment]
> If your GPU Node labeler (or is it labeller?) adds vendor specific labels, you should use hooks. Just my opinion.

This is my "first impression", too. You could use hooks or alternatively feature files. We could add documentation how to preferably deploy/use this, though.

Hooks are binaries run by NFD so in this case you need to deploy/mount the hook binary into the nfd-worker container. Feature files are files that NFD just reads so you could run the detection e.g. in the device plugin and dump the labels into a file that is mounted inside the NFD container.

I think the benefit of using NFD would be that you could keep you labeller simpler and more secure 
 as it would not need to communicate with k8s control plane.

**Comment by marquiz** [comment]
> Is NFD part of k8s by default (or will it be?)

No it's not and prolly won't be. It's an "add-on"

> I am wondering if it's worth while to move to use the NFD's hook if this means the user will need to run more than one containers (nfd-worker + labeller to populate the hook) just to label the GPUs.

Could the labeller be run inside the device plugin pod/container?

**Comment by y2kenny** [comment]
> Could the labeller be run inside the device plugin pod/container?
Base on your description above, I think I should be able to dump the features file for NFD to consume.  Would there be issue on the start order of NFD and device plugin (say, NFD started first so there are no features file.  Device plugin starts afterward and create the feature files.  Does NFD continuously watch the `/etc/kubernetes/node-feature-discovery/features.d/` directory?

Damn... I should have found this before diving into the whole CRD thing... although learning it was fun.

**Comment by marquiz** [comment]
> Base on your description above, I think I should be able to dump the features file for NFD to consume.

Yes, that should work. You'd need to create/mount this common directory, though.

> Would there be issue on the start order of NFD and device plugin (say, NFD started first so there are no features file. Device plugin starts afterward and create the feature files.)

No, if you run NFD as a DaemonSet,  in which  case it does re-labeling periodically, interval specified with `--sleep-interval` (60 s by  default).

Does NFD continuously watch the `/etc/kubernetes/node-feature-discovery/features.d/` directory?

NFD if currently pretty dumb in this sense. It does not use watch/fsnotify for detecting changes. It just re-runs feature detection in intervals specified by `--sleep-interval`. In your case it means that it re-scans the directory (every 60 s by default) and (re-reads) all files it finds.

> Damn... I should have found this before diving into the whole CRD thing... although learning it was fun.

Ha, learning is always fun 😄 And CRDs are something that I personally would need a deeper knowledge of
