### ISSUE TITLE
cert-manager

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/node-feature-discovery#277]
cert-manager can be used to issue certificates. It would be nice to have support for this.

**Comment by marquiz** [comment]
Agree, this would be highly desirable. I just haven't had the time to dive in to this ☹️

**Comment by marquiz** [comment]
@kfox1111 would you have time to look at this? :smile: Because I haven't had, yet

**Comment by kfox1111** [comment]
I'm in the same boat. Lots of things to do and not much time to do it. Sorry.

Cert-manager fits for getting the master a cert well I think. Does the workers get contacted directly, or do they only ever contact the master? If the latter, what about using the kubelet's cert/key for client auth? Would that work?

**Comment by marquiz** [comment]
> I'm in the same boat. Lots of things to do and not much time to do it. Sorry.

Ha, no problem


> Cert-manager fits for getting the master a cert well I think.

Mm

> Does the workers get contacted directly, or do they only ever contact the master?

nfd-workers are clients that connect to the nfd-master, not the other way around. The workers do not listen to any inbound connections.

> If the latter, what about using the kubelet's cert/key for client auth? Would that work?

Dunno, I probably wouldn't give the workers access to the kubelet cert. Just for the case

**Comment by kfox1111** [comment]
Ok. That helps. I can think of maybe two ways of automating this. One is the new cert-manager-csi driver:

https://github.com/jetstack/cert-manager-csi

The setup would be something like:
Create two cert-manager issuers, one for the server, one for clients
Create a Certificate object for the server. That should generate a cert/key in a secret

In the workers, use the csi driver pointing at the client issuer. Also point at the CA of the server's issuer so it can talk to the Server. This should give each worker its own cert.

In the server, use the cert/key and trust users from the user issuer.

This one I'm not sure how to ensure identity of a node cert for sure though.

The other option might be doing something with spiffe. This seems like something they might support.

Really this speaks to a greater Kubernetes problem though. There are lots of services that run on every node, that need to do something to some k8s objects, but only restricted to the node that particular instance is on. Maybe this issue needs a KEP?

**Comment by marquiz** [comment]
Thanks for thinking about this. I wasn't aware of the cert-manager-csi project.

> This one I'm not sure how to ensure identity of a node cert for sure though.

Yeah, this might be tricky. But even without the strict per-node certificate validation this would be a huge improvement

**Comment by marquiz** [comment]
Maybe this is the next bigger task.

/remove-lifecycle stale

**Comment by marquiz** [comment]
@kfox1111 are you still interested in this? I'm trying to find cycles to look into this

**Comment by kfox1111** [comment]
Yes. :)

**Comment by marquiz** [comment]
Enabled in #379. However, need to add support for updating cert files at runtime before merging that. This is being worked on separately.
/remove-lifecycle rotten

**Comment by marquiz** [comment]
We're almost there 😉
