### ISSUE TITLE
pci: add sriov detection

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#286]
SR-IOV is a PCI attribute. I'd suggest we add new attributes to PCI features:

```
feature.node.kubernetes.io/pci-0200_8086.sriov.capable=true
feature.node.kubernetes.io/pci-0200_8086.sriov.configured=true
```
Benefits:
* all SRIOV PCI devices can be detected
* For NIC class devices it is possible get to know which NICs have that capability (right now it's just "there's an SRIOV NIC on this node")

**Comment by marquiz** [comment]
This might be useful. Do you have a specific use case in mind that could be documented here? Do you think that only one label would be sufficient, e.g. `sriov.configured` (thinking about limiting the number of labels)?

**Comment by mythi** [comment]
QAT is an SR-IOV device and the QAT device plugin uses SR-IOV VF devices. My preference would be `sriov.capable` because the configuration could also be done in an initContainer before the actual device plugin runs... Just a quick thought.

**Comment by marquiz** [comment]
K, sounds reasonable. I'd prolly only add `sriov.capable` for now (in order to limit the number of labels). We can add `sriov.configured` later if required. WDYT?

**Comment by mythi** [comment]
+1 to `sriov.capable` only.
