### ISSUE TITLE
Add support for Custom features

### ISSUE THREAD

**Issue by adrianchiris** [kubernetes-sigs/node-feature-discovery#287]
Add a new feature source, `custom`, that will enable node labeling of custom features by defining a set of rules to match on per feature.

The custom features shall have two sources:
1. predefined list of node features in repository that are vendor agnostic (e.g RDMA)
2. configuration file

More info in the discussion in [PR#261](https://github.com/kubernetes-sigs/node-feature-discovery/pull/261)

**Comment by adrianchiris** [comment]
I will propose a PR for this based on the discussion in #261

**Comment by marquiz** [comment]
Implemented in #290.
