### ISSUE TITLE
Default location of /etc/os-release in Fedora is /usr/lib/os-release

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery#297]
Good and bad news regarding Fedora, if Fedora had `os-release` in the "right" place NFD would just work 
```
2020/03/19 15:56:06 system-os_release.ID = fedora
2020/03/19 15:56:06 system-os_release.VERSION_ID = 31
2020/03/19 15:56:06 system-os_release.VERSION_ID.major = 31
2020/03/19 15:56:06 system-os_release.VERSION_ID.minor = 
```
But unfortunately `/etc/os-release` is a symlink to `.../usr/lib/os-release`

Sooner or later this change may appear in RHEL.

**Comment by zvonkok** [comment]
@ArangoGutierrez PTAL

**Comment by marquiz** [comment]
Hmm, shouldn't this just work, already now 🤔  As `/etc/os-release` is mounted inside the nfd container it should be the symlink target that gets there(?)

**Comment by zvonkok** [comment]
I am running a Fedora 31
```
cat /etc/os-release | grep PRETTY
PRETTY_NAME="Fedora 31 (Workstation Edition)"
```
Debian e.g and Fedora symlink `/etc/os-release` to `../usr/lib/os-release`. 
Running an F29 container and mounting the `os-release` will show the wrong information about the host. 
```
podman run -it --rm    -v /etc/os-release:/host-etc/os-release    fedora:29  cat /etc/os-release | grep PRETTY
PRETTY_NAME="Fedora 29 (Container Image)"
```

Running a Debian container shows me that my host is now a Debian. 

```
podman run -it --rm    -v /etc/os-release:/host-etc/os-release    debian  cat /etc/os-release | grep PRETTY
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```

The symlink will be followed inside the container. Docker will not resolve the symlink and mounting `/usr/lib` additionall, we get the right information. 

```
podman run -it --rm    -v /etc/os-release:/host-etc/os-release  -v /usr/lib/os-release:/usr/lib/os-release   debian  cat /etc/os-release | grep PRETTY
PRETTY_NAME="Fedora 31 (Workstation Edition)"
```

**Comment by marquiz** [comment]
I didn't quite get that 🤔 We expose os-release of the host OS, not the container. We mount it under `/host-etc` not `/etc`

Works as expected, at least for me:
```
podman run -it --rm -v /etc/os-release:/host-etc/os-release fedora:29 cat /host-etc/os-release
```

**Comment by zvonkok** [comment]
@marquiz You did not paste the output. 
Your host os is?

**Comment by marquiz** [comment]
On openSUSE I get:
```
$ ls -l /etc/os-release
lrwxrwxrwx 1 root root 21 Oct 12 11:08 /etc/os-release -> ../usr/lib/os-release

$ podman run -it --rm -v /etc/os-release:/host-etc/os-release fedora:29 cat /host-etc/os-release
NAME="openSUSE Leap"
VERSION="15.1"
...
```

On Fedora 31 I get:
```
$ ls -l /etc/os-release
lrwxrwxrwx 1 root root 21 Oct 21 18:41 /etc/os-release -> ../usr/lib/os-release

$  podman run -it --rm -v /etc/os-release:/host-etc/os-release fedora:29 cat /host-etc/os-release
NAME=Fedora
VERSION="31 (Thirty One)"
ID=fedora
VERSION_ID=31
...
```

What container runtime are you using?

**Comment by zvonkok** [comment]
Oh man, mea culpa. I will close this. 

```
$ podman run -it --rm -v /etc/os-release:/host-etc/os-release fedora:29 cat /host-etc/os-release
                                                                            ^^^^^ forgot to add this!!!
```
