### ISSUE TITLE
nfd-workers crashes under an ipv6 environment 

### ISSUE THREAD

**Issue by yrobla** [kubernetes-sigs/node-feature-discovery#301]
applied this operator on an environment with ipv6. It deployed correctly on masters, but nfd-workers pods keep crashing.
When i look at logs inside the container, i can see:

2020/04/08 10:44:05 Sendng labeling request nfd-master
2020/04/08 10:44:05 failed to set node labels: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: address fd02::d19a:12000: too many colons in address"

This seems to be a problem with ipv6 address validation.

**Comment by marquiz** [comment]
How did you deploy this, could you share details of your nfd-worker Pod spec? Which version of NFD are you running, could you try the just-released [v0.6.0](https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.6.0)?

**Comment by aojea** [comment]
The IPv6 addresses has to be enclosed between square brackets

The nfd worker is using https://godoc.org/google.golang.org/grpc#DialContext

in https://github.com/kubernetes-sigs/node-feature-discovery/blob/e9017bef06d4a6aad2000299a2f06e0a681fd312/pkg/nfd-worker/nfd-worker.go#L249


and based in the documentation, you should allow more things than IP addresses ... it seems that is not a bug and user misconfiguration, or maybe the grpc library has a better validation for the target?

> The target name syntax is defined in https://github.com/grpc/grpc/blob/master/doc/naming.md. e.g. to use dns resolver, a "dns:///" prefix should be applied to the target.

**Comment by zvonkok** [comment]
@ArangoGutierrez Did we upstream the fix?

**Comment by ArangoGutierrez** [comment]
We did :
- https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/45 
Just a minor clarification, this is the OPERAND repo, not the OPERATOR.

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery-operator/pull/45
/close
