### ISSUE TITLE
why default nfd-worker yaml is using hostnetwork

### ISSUE THREAD

**Issue by tongtongxiaopeng1979** [kubernetes-sigs/node-feature-discovery#305]
it means nfdworker will not CNI based pod network.  Suspect it  will cause some communication issue for some CNI such as weavenet

**Comment by Ethyling** [comment]
AFAIK, nfd-worker is using `hostNetwork` to discover the network features from the host using the `Network` source. If it is required, I think you can disable the `Network` source and remove the `hostNetwork: True` from the YAML. @marquiz can you confirm?

**Comment by marquiz** [comment]
Yes, that is the reason for using host network in the sample deployment.

But, this is a valid issue. Maybe we could get the same information from sysfs without using hostNetwork.

**Comment by marquiz** [comment]
Stupid me 🤦 When thinking this closer I realized that we already have host sys mounted at `/host-sys` and we can use that for discovery. PR #317 fixes this

**Comment by marquiz** [comment]
Fixed by #317 that was merged
