### ISSUE TITLE
Explore design for cells (named node classes)

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-sigs/node-feature-discovery#32]
As discussed in [Kubernetes issue #28311](https://github.com/kubernetes/kubernetes/issues/28311),

_From @jeremyeder:_

> Here's what I'd propose. The concept of a cell (bikeshed the name...)
> 
> Labels are dynamically adjusted per the system/node capabilities "fleecing pod" as per @ConnorDoyle proposal. Next is how to express that in a way that keeps the UX under control.
> 
> Propose to de-couple into two parts; one being sort of a cluster administrator job -- defining what a cell contains. It could be a logical group of nodes. A cell could be exclusive or there could be overlap. Not sure how else to describe it, but a cell might be described as a cgroup controllers for datacenters.
> 
> And so the admins would define a cell such as this below, which is the union of labels that the fleecer pod applies to a node, and that are well defined:
> 
> ``` yaml
> kind: Cell
> apiVersion: v1
> metadata:
>     name: prod-trading
>     daemonset: tunedaemonset
>     annotations:
>             psap.server.kubernetes.io/model: XYZ1234
>             psap.network1.kubernetes.io/name: mgmt
>             psap.network2.kubernetes.io/name: backup
>             psap.network3.kubernetes.io/name: prod
>             psap.passthrough.kubernetes.io/name: /dev/sdd,eth2
>             psap.cpuset.mems.kubernetes.io/nodes: 1,exclusive
>             psap.cpuset.cpus.kubernetes.io/cores: 2,4,6-11
>             psap.memory.hugepages.kubernetes.io/hugetlb: 2MB
>             psap.kernel.kubernetes.io/module: nvidia,onload
>             psap.kernel.kubernetes.io/version: >= 3.10.0-229
>             psap.tuned.kubernetes.io/profile: network-latency
> ```
> 
> And then ... the UX for a developer is very simple...just specify what cell you want to run on:
> 
> ``` yaml
> kind: Pod
> apiVersion: v1
> metadata:
>     mame: matching-engine
>     cell: prod-trading
>     annotations:
>             psap.kernel.kubernetes.io/ulimit: n:1048576
> ```
> 
> I should also say that @ConnorDoyle proposal covers over 90% of what we're envisioning, but there's at least one missing piece. A long-running daemon that ensures a node is "fit for service". Concept I'm calling in my head "extended-node-fitness".
> 
> In RHEL we have a daemon called "tuned" which handles system tuning based on workload. Tuned has a "verify" verb that goes through and ensures desired state matches what's in place. To avoid sprawl of infra pods/daemonsets I was thinking we could let this pod be long running and have the fitness test (in our case tuned) run.
> 
> There would need to be a call-back from this pod to the Kube scheduler if the fitness test ever failed (let's say, a rogue admin ssh'd in and flipped a few tunables that conflict with application needs). The tuned pod would inform the scheduler that it's out of sync and take some action:
> - re-enable the tuning
> - evict the node from the cluster
> - make it unschedulable or drain it
> - shut the node down hard
> - whatever else the app needs
> 
> Now ... I have a set of proposals and use-cases that center around delivering this and several other associated features. I'd love to talk with folks at KubeCon about it in more depth!

_From @vikaschoudhary16:_

> +1 for cells. Additionallly, I think it would be helpful if api is available for user to compose a cell using kv pairs (capabilities) she thinks are desrired for her workload. Different cells could be composed for different workloads over same nodes and then accordingly mentioned in pod spec.
> 
> Wondering what could be the concerns if we trigger node-feature-discovery when a cell is composed to discover nodes with capabilities mentioned in the cell and labelling nodes with cell names.

**Comment by jeremyeder** [comment]
Thanks for filing this.  The idea for cells is to:

- Retain the ability for developers to ship code quickly and easily
- De-couple shipping code from the need to understand the infrastructure at it's lowest levels.
  - Assuming this code has special requirements, such as:
    - Which geography it should run in
    - Which mix of hardware/software is required (containers don't fix everything!)
    - What SLA the application has
    - Any other business need/logic

**Comment by derekwaynecarr** [comment]
A StorageClass is primarily for dynamic provisioning.  The PVC itself is not mutated other than a reference to the StorageClass, and that reference is optional, and we still have issues that arise when the StorageClass changes or is removed while the PVC remains.

This appears more to modify the incoming pod with default labels/taints/tolerations/resource requests/etc which may or may not have its own problems, and the scope of things that you would want to modify may be quite large.

**Comment by fabiand** [comment]
Initially I was worried that exposing low-level features like CPU flags in annotations might quickly clutter those.
But by grouping these feature sin Cells (or maybe NodeFeatures?) this concern goes away.

But what about using the reverse fqdn notation - which makes it look nicer in a sorted fashion:

```
io.kubernetes.kernel.psap/flags: svm
io.kubernetes.net1.psap/name: data
io.kubernetes.net2.psap/name: controll
```

**Comment by ConnorDoyle** [comment]
@fabiand thanks for the feedback. See also #27 where we're bikeshedding the prefix for all labels published by NFD.

**Comment by davidopp** [comment]
Is there some way we can get the same benefits without having to introduce a new API object (Cell)?

You could put annotations directly on the daemonset pod, which could read them through the downward API (or even better, configure it using ConfigMap).

On the requesting pod, you could apply an annotation that is read by an admission controller (configured via the same ConfigMap as the daemonset pod uses) that adds the corresponding node selectors.

This isn't very different than what you have proposed, but the Cell just becomes something defined via a ConfigMap rather than as its own API object.

**Comment by fabiand** [comment]
@davidopp to me that sounds a little to generic. To me features look special enough (they will be valuable for any application having some kind of hardware dependence), that they should be exposed in a well defined place.

I am not sure if it was already discussed in another place already: But why don't we expose the features of a host in the Node status? In that case we could reuse the existing object.

What is actually speaking against this from my POV is that these informations should probably be gathered outside of core node, and might be an add-on. In that case we don't want add-ons to update the Node status, do we?

Besides that: I would not expose/list all the features in an entity directly, at least not low-level features like svm/vmx or whatever, but I'd rather think that we the features are either grouped (like in cells) and this group is referenced. Or that some kind of controller is deriving more high-level features from a set of primitives (i.e. `virtualization` from `svm` or `vmx`), and this high-level feature can then be used for scheduling.

**Comment by balajismaniam** [comment]
@davidopp, I think ConfigMap might work . @ConnorDoyle, @jeremyeder and I were discussing about using third party resources to define a Cell and associating the Cell to a node using labels. That way, we could select a node based on the label (or Cell). WDYT?

**Comment by jeremyeder** [comment]
I agree w/TPR primarily because it is a zero-friction method of prototyping the long term solution, which I'd hope is a new API object. There's nothing in the API that *cleanly* lets us do this now, and retains a simple UX for users.

We also want Cells tied to other features in the product such as admission control and RBAC.  While we can do the first generation of this with TPR, at least I would like us have a clear goal of promotion to a real API object that people can rally their design/architectures/security stance around.

As far as @davidopp point about adding node selectors...I think we want users to be comfortably numb about individual nodes, and target "any node that can successfully run my magic-app", which is abstracted cleanly with a Cell object.

**Comment by davidopp** [comment]
I'm still not understanding why you need a new API object (or a TPR). Any kind of configuration that you can put in an API object you can put in a ConfigMap.

**Comment by timothysc** [comment]
> I'm still not understanding why you need a new API object (or a TPR). 

Usability and sane RBAC rules.  

> Any kind of configuration that you can put in an API object you can put in a ConfigMap.

Users already have a tough time, I think that would obfuscate it even more.

**Comment by davidopp** [comment]
Ah I see, you want to limit who can make changes to the Cell information, which I guess wouldn't be possible with a ConfigMap? (Though it seems that's a pretty big deficiency if we can't control who can modify ConfigMap, since we're moving towards doing all Kubernetes component config via ConfigMap)

**Comment by ConnorDoyle** [comment]
I've been meaning to comment since we chatted but have been on the road. Thanks Balaji for summarizing what we talked about. Just a couple of additional comments/ideas:

- Another vote for TPR, allows for seamless UX between experimentation and potential first-class resource in the future.
- If we represent Cell membership as a special label on nodes, then we can schedule against them for free using affinity.
- Node cell membership labels could be published by  the NFD container (via a new "cell" source). The cell source could fetch the criteria for the defined cells via the API server and compare against the discovered features. If the NFD container is configured to use --sources=cpuid,cell then the --label-whitelist attribute could be used to filter out everything but the cell membership labels.

Anyway, this seems to be shaping up. Should we collaborate on a design doc to work through the details?

**Comment by fabiand** [comment]
Was there some further movement outside of this thread on this topic? Our use-case (http://kubevirt.io) also requires to publish node features.

I do like the separation of Cells as TPRs and associating them to pods using labels.

What would be a next step, @ConnorDoyle ?
