### ISSUE TITLE
cpu: add Intel AMX

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#328]
a feature request to add labels for the new [AMX instructions](https://software.intel.com/content/www/us/en/develop/download/intel-architecture-instruction-set-extensions-programming-reference.html)

labels (TBC):

- [x] AMX  (BF16/TILE/INT8) cpuid bits
- [ ] num of tile palettes
- [ ] TMUL presence + TMUL `maxk`/`maxn`

**Comment by askervin** [comment]
- PR to cpuid on detecting BF16/TILE/INT8:
  https://github.com/klauspost/cpuid/pull/56

**Comment by marquiz** [comment]
> klauspost/cpuid#56

Has been merged so you could submit a corresponding pr here

**Comment by mythi** [comment]
@marquiz we have a couple of other bits still in works and there's no release with these changes yet so we could wait a bit

**Comment by marquiz** [comment]
NP, take your time, I'm not in a hurry 😉

**Comment by marquiz** [comment]
@mythi are we now there?
/remove-lifecycle rotten

**Comment by mythi** [comment]
@marquiz the first bullet is done: we get "true" labels for those three bits. the rest are numerical labels and not currently implemented.

**Comment by askervin** [comment]
@mythi, what do you think, should we prioritize exposing numeric values in labels, too?

**Comment by mythi** [comment]
> Is the missing information readable through cpuid instruction 

@marquiz yes it is but not yet implemented in `klauspost/cpuid`

**Comment by marquiz** [comment]
K, thanks for the update.

**Comment by mythi** [comment]
@marquiz I did a bit of homework and concluded that the existing information is enough (and, FWIW, exactly the same as what `/proc/cpuinfo` is going to provide as `flags`)

this can be closed

**Comment by marquiz** [comment]
> @marquiz I did a bit of homework and concluded that the existing information is enough (and, FWIW, exactly the same as what `/proc/cpuinfo` is going to provide as `flags`)
> 
> this can be closed

Thanks for the update. Let's close this then and re-open (or submit a new issue) if needed
/close
