### ISSUE TITLE
Exposing Hardware Topology through CRDs in Node feature discovery

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes-sigs/node-feature-discovery#333]
Currently Node feature Discovery consists of nfd-master and nfd-worker. The former is responsible for labeling Kubernetes node objects and the latter is responsible for detecting features and communicating them to nfd-master. nfd-worker runs as a daemon-set on all the nodes in the cluster.

Resource Topology Exporter ([KEP](https://github.com/kubernetes/enhancements/pull/1870), [Code](https://github.com/swatisehgal/resource-topology-exporter)) can nicely fit into NFD architecture by:
- enabling nfd-worker to gather node resource topology information
- passing this information to the nfd-master over grpc
- Ultimately, the nfd-master is responsible for creating CRD instances for all the worker nodes in the cluster.

Design document explaining the approach and proposed changes are provided in detail [here](https://docs.google.com/document/d/1Q-4wSu1tzmbOXyGk_2r5_mK6JdXXJA-bOd3cAtBFnwo/edit?ts=5f24171f#).

Possible implementation approaches of introducing Resource Topology Exporter in NFD operand are summarized below:

1. Option 1:Introducing Resource Topology Exporter as a source or a new command line option in the nfd-worker. New source (or new command line option) is where nfd-worker would gather hardware topology information. Nfd-master would update NumaTopology CRD

1. Option 2 (preferred): A new helper daemon eg nfd-node-topology (similar to nfd-worker). 

- The new helper gathers hardware topology information and sends to nfd-master over gRPC through another endpoint. 

- The communication between nfd-node-topology between nfd-master is over the separate endpoint which contains hardware topology information but can be easily enhanced to other CRDs 

- Nfd-master would update NumaTopology CRD using NodeTopologyRequest that it receives from nfd-worker

- NOTE: NFD operator would have to be enhanced to cater to nfd-node-topology (like it manages nfd-master and nfd-worker)

- The advantage of this approach is that  nfd-worker and nfd-master continue to work the same way as they currently do

Changes to the gRPC interface: Introducing another gRPC endpoint for communication between nfd-worker and nfd-master. (completely separate proto as shown below)
``` yaml
syntax = "proto3";

option go_package = "sigs.k8s.io/node-feature-discovery/pkg/topologyupdater";
import "github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha1/generated.proto";

package topologyupdater;

service NodeTopology{
    rpc UpdateNodeTopology(NodeTopologyRequest) returns (NodeTopologyResponse);
}
message NodeTopologyRequest {
    string nfd_version = 1;
    string node_name = 2;
    repeated string topology_policies = 3;
    repeated v1alpha1.Zone zones = 4;
}
message NodeTopologyResponse {
}


```

Additionally, we propose that NFD becomes home for NodeResourceTopology CRD API definition (and informer, clientset, handlers etc)

**Comment by marquiz** [comment]
I'd suggest to use a more generic name for the package, "cr-updater" or something.

Regarding the data/CRD, I was pondering should we prepare for more detailed information, e.g. bake in or make it possible to present numa distances(?)

**Comment by swatisehgal** [comment]
@marquiz Sure, we can make the package name more generic.
Can you elaborate on how do you see numa distances here?
In order to gather resource information out of tree we rely on podResource API. As our only source of truth for obtaining [device information](https://github.com/kubernetes/kubelet/blob/master/pkg/apis/deviceplugin/v1beta1/api.proto#L101) is (device manager in) kubelet, we can obtain device information (device ids and numanodes)  by extending podResource API (as proposed here: https://github.com/kubernetes/enhancements/pull/1884) . As per the device plugin API design, numa distances cannot be obtained from kubelet as it is not supported currently in kubelet.

**Comment by swatisehgal** [comment]
@marquiz Sure, we can make the package name to be more generic.
Can you elaborate on how do you see information related to numa distances being exposed here?
In order to gather resource information out of tree we are currently relying on podResource API. As our only source of truth for obtaining device information is (device manager in) kubelet, we have [device information](https://github.com/kubernetes/kubelet/blob/master/pkg/apis/deviceplugin/v1beta1/api.proto#L101) in kubelet (health, device ids and numa node as part of topologyInfo) but need to extend podResource API (as proposed here: kubernetes/enhancements#1884) . Numa distances cannot be obtained from kubelet as it is not supported currently in kubelet.

As per the design of topology manager, cpu manager and device manager implement the hint providers interface and provide numa node id as a hint to topology manager. 
We are open to suggestion here, but as a starting point we could expose the constructs in terms of numa node ids (as it aligns with the current design of topology manager) and more importantly that's the only information at our disposal currently. We would be more than happy to update later when topology information becomes more descriptive in topology manager as the API itself would become more descriptive and would allow us to expose this information. Let me know your thoughts.

**Comment by fromanirh** [comment]
A way we can expose the numa distance could probably be like
```
message NUMANodeResource {
    int numa_id = 1;
    map<string, string> resources = 2;
    map<int, int> distances = 3;
}
```
However I second what @swatisehgal wrote, the thing is we were using the podresources API - and the extensions we were proposing here - as source of truth. However, if there is interest specifically about the numa distances we can maybe learn them reliably from sysfs, kinda like `numactl` does. That should be pretty safe to reconcile. It could require access to more system resources though.

**Comment by swatisehgal** [comment]
Thanks @fromanirh for this code snippet. Getting this information from sysfs is totally doable and populating this in NumanodeResource makes sense! I was considering numa node distance from the point of view of resources and their distance from each other.

**Comment by marquiz** [comment]
I don't have the answers myself, either, just throwing some ideas 😊 I was just trying to think a bit ahead and broader and not "cement" this too tightly just for this one use case and scheduler extension. When we add something we should at least try to think about possible other users and usages, too, e.g. some other scheduler extensions and possibly alternative rte daemons digging more detailed data. Just trying to avoid the situation where we quickly patch together the api for one narrow use case and after a while we're stuck with that and have problems serving new users. This case is simple, but still. Maybe we have something to learn from how the Linux kernel handles apis 😄

**Comment by swatisehgal** [comment]
@marquiz Thanks for the input. I see your point and have updated the design document to include NumaNode distances as part of the NumaNodeResource structure

**Comment by swatisehgal** [comment]
Development work is in progress to support this feature. PR will be linked here soon!

**Comment by fromanirh** [comment]
Expect the missing two PRs by monday

**Comment by fromanirh** [comment]
No 	Task Break Down 	PR 	Owner
1. 	NFD Topology Updater Implementation 	https://github.com/kubernetes-sigs/node-feature-discovery/pull/525 	@swatisehgal
2. 	NFD Topology Updater Documentation 	https://github.com/kubernetes-sigs/node-feature-discovery/pull/526 	@swatisehgal
3. 	NFD Topology Updater E2E tests 	https://github.com/kubernetes-sigs/node-feature-discovery/pull/528 	@fromanirh
4. 	Enable Configz Endpoint for obtaining Kubelet config 	TODO 	@Tal-or

**Comment by ArangoGutierrez** [comment]
/kind/feature

**Comment by ArangoGutierrez** [comment]
Hey all, any updates on this feature set?

**Comment by marquiz** [comment]
There is progress lately in e2e-tests and /configz endpoint

/remove-lifecycle stale

**Comment by marquiz** [comment]
This is still alive and tracking
/remove-lifecycle rotten

**Comment by marquiz** [comment]
@ffromani @Tal-or @swatisehgal are we expecting new PRs here or should we close this issue? We could also track the missing pieces as separate issues

**Comment by marquiz** [comment]
@ffromani @PiotrProkop @Tal-or @swatisehgal should we close this issue as implemented and track any future enhancements in separate issues?

**Comment by ffromani** [comment]
> @ffromani @PiotrProkop @Tal-or @swatisehgal should we close this issue as implemented and track any future enhancements in separate issues?

From my perspective yes, we're now in a pretty good shape and we can track future enhancements with separate issues.

**Comment by swatisehgal** [comment]
> @ffromani @PiotrProkop @Tal-or @swatisehgal should we close this issue as implemented and track any future enhancements in separate issues?

+1. Nice to see that we have come a long way :) Let's close this issue. Thanks!

**Comment by marquiz** [comment]
Closing as suggested. Thanks for everybody involved for working on this 🎉

/close
