### ISSUE TITLE
HTML-based documentation

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#353]
The current README is probably not the easiest to read and navigate. Even if it was the structuring certainly could be improved.

I think it would be a relatively small effort to switch to html-based documentation, served by [GitHub Pages](https://pages.github.com/) and [Jekyll](https://docs.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll)

README would be a small landing page pointing to the full documentation.

**Comment by ArangoGutierrez** [comment]
++

**Comment by marquiz** [comment]
HTML docs now available at
https://kubernetes-sigs.github.io/node-feature-discovery
