### ISSUE TITLE
pathPrefix in source/config.go is wrong

### ISSUE THREAD

**Issue by zvonkok** [kubernetes-sigs/node-feature-discovery#374]
```
var (
        pathPrefix = "/"
        // BootPath is where the /boot directory of the system to be inspected is located
        BootDir = HostDir(pathPrefix + "boot")
        // EtcPath is where the /etc directory of the system to be inspected is located
        EtcDir = HostDir(pathPrefix + "etc")
        // SysfsPath is where the /sys directory of the system to be inspected is located
        SysfsDir = HostDir(pathPrefix + "sys")
)
```

The files are mounted `/host-etc/os-release`  `/host-sys/...` `/host-boot/...` but the pathPrefix will read the files not under `/host-<OBJ>` it will read in `/` in the container. 

We need to set the  ` pathPrefix = "/"` to  ` pathPrefix = "/host-"` and append a `/` after the dir `{boot, etc, sys}`

**Comment by zvonkok** [comment]
@marquiz @ArangoGutierrez PTAL

**Comment by marquiz** [comment]
It is deliberately like this and set at build time

**Comment by zvonkok** [comment]
Thanks @marquiz we have everything in place, our build system has made an error.
