### ISSUE TITLE
Namespace 'nvidia.com' is not allowed. Ignoring label 'nvidia.com/gpu.memory'

### ISSUE THREAD

**Issue by weishiuchang** [kubernetes-sigs/node-feature-discovery#384]
**What happened**:

Deployed [nfd](https://github.com/kubernetes-sigs/node-feature-discovery) and [gfd](https://github.com/NVIDIA/gpu-feature-discovery) via helm

kubectl logs -f node-feature-discovery-master-abcdefghi

2020/11/09 11:59:10 Namespace 'nvidia.com' is not allowed. Ignoring label 'nvidia.com/gpu.memory'
2020/11/09 11:59:10 Namespace 'nvidia.com' is not allowed. Ignoring label 'nvidia.com/cuda.runtime.major'
2020/11/09 11:59:10 Namespace 'nvidia.com' is not allowed. Ignoring label 'nvidia.com/gpu.count'
...

Numerous lines ignoring the labels from worker nodes.

**What you expected to happen**:

Nvidia labels on nodes with GPUs

**How to reproduce it (as minimally and precisely as possible)**:

helm install nfd and gfd

**Anything else we need to know?**:

Error came from https://github.com/kubernetes-sigs/node-feature-discovery/blob/6c6a682d230468e62820e6add7abd4867d027bf1/pkg/nfd-master/nfd-master.go#L287 which implies that extraLabelNs is not-empty. Looking at [args.ExtraLabelNs](https://github.com/kubernetes-sigs/node-feature-discovery/blob/6c6a682d230468e62820e6add7abd4867d027bf1/cmd/nfd-master/main.go#L125) it is actually a slice with an empty string as its sole element: [""]. This is because [strings.Split()](https://golang.org/pkg/strings/#Split) "Split returns a slice of length 1 whose only element is s" since "s does not contain sep and sep is not empty".

**Comment by marquiz** [comment]
Currently, only `feature.node.kubernetes.io` namespace is allowed by default. You need to pass `--extra-label-ns=nvidia.com` cmdline flag to nfd-master in order to be able to create the labels listed above.

**Comment by weishiuchang** [comment]
Thank you @marquiz does this mean that I cannot white list all namespaces?

**Comment by marquiz** [comment]
> Thank you @marquiz does this mean that I cannot white list all namespaces?

No, unfortunately there's no support for wildcards/regexps. You need to explicitly list all namespaces that you want to enable. This was a deliberate choice as node labeling is a powerful capability. Regexp matching might be a worthwhile enhancement, though.

**Comment by klueska** [comment]
Strange, this should be set by default when you deploy NFD/GFD via helm

https://github.com/NVIDIA/gpu-feature-discovery/blob/master/deployments/helm/gpu-feature-discovery/values.yaml#L28
https://github.com/NVIDIA/gpu-feature-discovery/blob/master/deployments/helm/gpu-feature-discovery/charts/node-feature-discovery/templates/master.yaml#L50

**Comment by marquiz** [comment]
Hmm, there must be something wrong in the help charts 🤔 What are the command/args of the nfd-master pod?

**Comment by klueska** [comment]
At least from the GFD side, this is the first instance I've heard of people having problems. Most people that use GFD tend to deploy NFD from GFDs integrated subchart (which shoud work without problems by default). I'm guessing  @weishiuchang deployed NFD and GFD separately, without first setting the `--extra-label-ns` in hist NFD deployment.

**Comment by weishiuchang** [comment]
Actually I used the chart listed in [gpu-operator/deployments/gpu-operator/charts/node-feature-discovery](https://github.com/NVIDIA/gpu-operator/blob/master/deployments/gpu-operator/charts/node-feature-discovery-2.0.0.tgz) which looks to just be the default NFD. I'm ok to close this issue as user-error.

**Comment by klueska** [comment]
Got it. I'll make sure the that the default values passed to NFD in the Operator include this setting for `--extra-label-ns` in the next release.

**Comment by marquiz** [comment]
Closing this issue as proposed above
