### ISSUE TITLE
Move to kustomize

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#398]
**What would you like to be added**:

I'd like to propose NFD moves out from `.yaml.template` and commented lines to [kustomize](https://kubectl.docs.kubernetes.io/guides/introduction/kustomize/)

**Why is this needed**:

To make the deployments more maintainer and end-user friendly by using the latest deployment tooling

**Comment by marquiz** [comment]
Need to go this direction..
/remove-lifecycle stale

**Comment by ArangoGutierrez** [comment]
Fixed in  #573
/close
