### ISSUE TITLE
Graduate from incubator

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-sigs/node-feature-discovery#4]
[Criteria](https://github.com/kubernetes/community/blob/master/incubator.md#graduation) for graduating from the incubator.

Incubation date: 29 August 2016
Incubation deadline: 29 August 2017

When the OWNERS of the Incubator project determine they have met the criteria to graduate they should contact their Champion and Sponsor to discuss. If both the Sponsor and Champion agree that the above criteria have been met the project can graduate to become a Kubernetes Community Project and exit the Kubernetes Incubator.

_TODO: Link sub-issues to gather evidence for each topic below._
- [ ] Documented users: the project tracks evidence from downloads, mailing lists, Twitter, blogs, GitHub issues, etc that the project has gained a user base.
- [ ] Regular releases: the project is making releases at least once every 3 months; although release should happen more often.
- [ ] Incubation time: a minimum of 6 months has passed since incubation (March 2017)
- [ ] Healthy community: a healthy number of users, contributors, and/or OWNERS outside of your own company have participated in the project. The Sponsor and Champion can make this call.
- [x] Roadmap: A roadmap for the next release is maintained; this can be in the form of a doc, GitHub milestones, or any other tool but it must be documented in the README.
- [ ] An announcement of graduation must be sent to the kubernetes-dev@googlegroups.com mailing list by the Champion.

**Comment by ConnorDoyle** [comment]
#40 first tagged release

**Comment by ConnorDoyle** [comment]
[self-identified users](https://github.com/kubernetes-incubator/node-feature-discovery/wiki/Users) on the project wiki

**Comment by ConnorDoyle** [comment]
Milestones are used for roadmap tracking, noted in the README.

**Comment by taylorm10** [comment]
Index of [blog posts](https://github.com/kubernetes-incubator/node-feature-discovery/wiki/Blog-Posts) on the project wiki

**Comment by marquiz** [comment]
NFD was migrated to kubernetes-sigs organization. We're not aiming for kubernetes core, anymore. Closing this issue now.
