### ISSUE TITLE
Dependency: update klauspost/cpuid to v2

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery#413]
**What would you like to be added**:
- https://github.com/klauspost/cpuid/issues/28
We need to watch for `klauspost/cpuid` dependency, once it cut a next release we should update go.mod 

**Why is this needed**:
Is always a good practice to keep deps up to date and pointing to a release not a commit hash

**Comment by marquiz** [comment]
[v2.0.1](https://github.com/klauspost/cpuid/releases/tag/v2.0.1) is out
