### ISSUE TITLE
Add Helm Chart to NFD

### ISSUE THREAD

**Issue by adrianchiris** [kubernetes-sigs/node-feature-discovery#422]
**What would you like to be added**:
A helm chart to be used by Helm for deploying NFD in a K8s cluster

**Why is this needed**:
To ease NFD deployment and upgrade.

Currently there are several self brewed charts to deploy NFD. we should have one source.

https://github.com/Mellanox/network-operator/tree/master/deployment/network-operator/charts/node-feature-discovery
https://github.com/k8s-at-home/charts/tree/master/charts/node-feature-discovery
https://github.com/NVIDIA/gpu-operator/tree/master/deployments/gpu-operator/charts/node-feature-discovery

**Comment by cpanato** [comment]
@adrianchiris what is the idea for this, we create the chart in this repository?

**Comment by adrianchiris** [comment]
yes, maintain a chart a part of this repository, github can also be used as a helm repo to serve the chart.

**Comment by cpanato** [comment]
yes, we can release the chart to another branch.

would you mind if I work on this issue?

**Comment by adrianchiris** [comment]
was planning to take it from [network-operator](https://github.com/Mellanox/network-operator/tree/master/deployment/network-operator/charts/node-feature-discovery) and propose a PR, if you want to propose a PR for this im fine with it :)

**Comment by cpanato** [comment]
@adrianchiris if you already have things you can move forward, i will help to review! thanks!

**Comment by e0ne** [comment]
Since #423 is merged, let's close this issue
