### ISSUE TITLE
Local -- User-specific Features with error Namespace *** is not allowed

### ISSUE THREAD

**Issue by wukong1992** [kubernetes-sigs/node-feature-discovery#424]
**What happened**:
I write a script in host's /etc/kubernetes/node-feature-discovery/source.d path, and the output of script will be example/nvidia-driver=480.10 ...， when apply, the log of nfd-master is:  Namespace 'example' is not allowed. Ignoring label 'example/nvidia-driver'
**What you expected to happen**:
the label is added to the node succeffuly
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mythi** [comment]
Same as #384? `--extra-label-ns=example` is needed.

**Comment by mythi** [comment]
Same as #384? `--extra-label-ns=example` is needed.

**Comment by marquiz** [comment]
> Same as #384? `--extra-label-ns=example` is needed.

Yes. We're very strict about the label namespaces. You need to provide `--extra-label-ns=example` as a command line argument to nfd-master. I'd suggest to close this issue
