### ISSUE TITLE
Add additional cpu features

### ISSUE THREAD

**Issue by bfournie** [kubernetes-sigs/node-feature-discovery#439]
In order to provide for more granularity in scheduling decisions, we would like to add the following cpu features:

- feature.node.kubernetes.io/cpu-performance_policy (_performance_ or _powersave_) based on /sys/devices/system/cpu/cpufreq/policy
- feature.node.kubernetes.io/cpu-max_cstate (integer) based on /sys/module/intel_idle/parameters/max_cstate
- feature.node.kubernetes.io/cpu-virtualization (_VT-x_ or _VT-d_) based on output of lscpu
- feature.node.kubernetes.io/cpu-pstate.disable (true or false) based on /sys/module/acpi_cpufreq/parameters/acpi_pstate_strict

**Comment by ArangoGutierrez** [comment]
Awesome @bfournie !!

**Comment by marquiz** [comment]
> * feature.node.kubernetes.io/cpu-performance_policy (_performance_ or _powersave_) based on /sys/devices/system/cpu/cpufreq/policy

You mean the scaling governor? We prolly need to check that all cpus (policies) have the same governor activated.



> * feature.node.kubernetes.io/cpu-virtualization (_VT-x_ or _VT-d_) based on output of lscpu

Hmm, need to check if there's an easy way to discover these without resorting to `lscpu` binary

**Comment by bfournie** [comment]
> > * feature.node.kubernetes.io/cpu-performance_policy (_performance_ or _powersave_) based on /sys/devices/system/cpu/cpufreq/policy
> 
> You mean the scaling governor? We prolly need to check that all cpus (policies) have the same governor activated.
> 
Yes the intent was to use the scaling governor, but need to figure out what to report if all cpus don't have the same policy.

> > * feature.node.kubernetes.io/cpu-virtualization (_VT-x_ or _VT-d_) based on output of lscpu
> 
> Hmm, need to check if there's an easy way to discover these without resorting to `lscpu` binary

Right, if don't want use lscpu, could check /proc/cpuinfo for the 'vmx' flag which would show if VT-x is enabled.  Again not sure how to report this if cpus have different settings though.

**Comment by MadhavJivrajani** [comment]
Hi! Could I work on this if it's available?

**Comment by mythi** [comment]
> feature.node.kubernetes.io/cpu-virtualization (VT-x or VT-d) 

`VMX` and `HYPERVISOR` bits are supported by cpu source.

**Comment by bfournie** [comment]
> Hi! Could I work on this if it's available?

Hi!  These are mostly done, but feel free to propose additional features

**Comment by bfournie** [comment]
> > feature.node.kubernetes.io/cpu-virtualization (VT-x or VT-d)
> 
> `VMX` and `HYPERVISOR` bits are supported by cpu source.

Thanks, yes I realized afterwards that these are read by cpuid and can be obtained by setting the values in attributeWhiteList

**Comment by MadhavJivrajani** [comment]
> Hi! These are mostly done, but feel free to propose additional features

Thanks! I see that these features are meant to provide more granular scheduling decisions, I'm a complete beginner because of which I'm not sure if this apt in this context, but would the following help:
- CPU Frequency
- Scheduler statistics ([`/proc/schedstat`](https://www.kernel.org/doc/html/latest/scheduler/sched-stats.html))
- Shared CPU list per cache index, per core

If I've gotten the idea itself wrong here, could you maybe point me towards what I can read up on in order to understand this better? I'd love to learn!

**Comment by bfournie** [comment]
> > Hi! These are mostly done, but feel free to propose additional features
> 
> Thanks! I see that these features are meant to provide more granular scheduling decisions, I'm a complete beginner because of which I'm not sure if this apt in this context, but would the following help:
> 
> * CPU Frequency
> * Scheduler statistics ([`/proc/schedstat`](https://www.kernel.org/doc/html/latest/scheduler/sched-stats.html))
> * Shared CPU list per cache index, per core
> 
> If I've gotten the idea itself wrong here, could you maybe point me towards what I can read up on in order to understand this better? I'd love to learn and come back to this!

Hi! These are good ideas, note though that these new feature will be used as label selectors and as such there is no integer comparisons, see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/.

The features are usually expressed as booleans (I will change this proposal to express each new feature as a boolean also) so that the scheduling is straightforward. In that case statistics, frequency, or a list would be hard to use, at least as I understand it.

**Comment by MadhavJivrajani** [comment]
Oh, I think I understand now. Thanks!

So, for example, would something like showing if SMT at runtime (`/sys/devices/system/cpu/smt`) is enabled or not on a system be helpful?

**Comment by bfournie** [comment]
> Oh, I think I understand now. Thanks!
> 
> So, for example, would something like showing if SMT at runtime (`/sys/devices/system/cpu/smt`) is enabled or not on a system be helpful?

Yes, that may be useful. 

It looks like that is being accessed by cpuid only for ppc here - https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/source/internal/cpuidutils/cpuid_ppc64le.go#L51, but I don't know much about this feature.

**Comment by bfournie** [comment]
Note that the initial proposal had:
feature.node.kubernetes.io/cpu-virtualization (VT-x or VT-d)

but since VMX is already being retrieved via cpuid its not probably not necessary to add anything additional.

**Comment by marquiz** [comment]
> Yes, that may be useful.
> 
> It looks like that is being accessed by cpuid only for ppc here - https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/source/internal/cpuidutils/cpuid_ppc64le.go#L51, but I don't know much about this feature.

We already have `cpu-hardware_multithreading`. It dates back to before the smt sysfs interface was available but in practice provides the information if smt is on.
