### ISSUE TITLE
Host NFD Helm charts in gh-pages

### ISSUE THREAD

**Issue by adrianchiris** [kubernetes-sigs/node-feature-discovery#440]
**What would you like to be added**:
With #423 we added Helm Chart to NFD. This will facilitate an easy deployment and management of NFD in a k8s cluster.
We should support deploying this chart via a helm repository instead of cloning a particular release and deploying NFD with helm from the `/deployment/node-feature-discovery` folder

I propose to leverage gh-pages which this project already uses to host a helm repo for NFD.

What this might entail:
- create a new `helm-release` folder which contains all created helm tarballs
  - on new release a new tarball is created and copied to the folder
- create an index.yaml
  - on new release, index.yaml is updated (`helm repo index` command) 
- serve the above from gh pages
- update of automation script (`scripts/prepare-release.sh`, `scripts/github/push-gh-pages.sh`)

**Why is this needed**:
This will provide an improved user experience for consumers of NFD by providing ease of deploy/update of NFD.

**Comment by marquiz** [comment]
Yes, we need something like this. How about using the release page (https://github.com/kubernetes-sigs/node-feature-discovery/releases) for storing the release artefact(s)? E.g. for the upcoming release we would have something like https://github.com/kubernetes-sigs/node-feature-discovery/archive/nfd-helm-0.8.0.tgz (I have no idea about the naming scheme 😄 )

We need to update the `prepare-release.sh` could create the artefact. Which would need to manually uploaded, though 😕 Maybe we could utilize github workflows for this 🤔  On "create-tag" create a helm chart and put it in place under "archive"

**Comment by adrianchiris** [comment]
> How about using the release page (https://github.com/kubernetes-sigs/node-feature-discovery/releases) for storing the release artefact(s)? E.g. for the upcoming release we would have something like https://github.com/kubernetes-sigs/node-feature-discovery/archive/nfd-helm-0.8.0.tgz (I have no idea about the naming scheme 😄 )

If we host the chart under release artifacts, we would need to manually update _index.yaml_ with the new release info.
usually this file is updated via `helm repo index` command which requires a folder with all chart tarballs.
(essentially you have a "release" chart folder somewhere where you add to it the helm chart tarball every release, then generate index file from that folder)

see: https://helm.sh/docs/topics/chart_repository/

_index.yaml_ file should (IMO) be served from gh pages, that way a user will use `https://kubernetes-sigs.github.io/node-feature-discovery` as helm repository which should contain all released charts.

**Comment by marquiz** [comment]
Thanks @adrianchiris for educating me on this. I agree that at least `index.yaml` should be served from gh-pages. However, I would explore storing the chart tarballs themselves under release assets. The gh-pages automation should be able to list releases and their assets (via github api) and update the index. Need to take a closer look at the details, though.

**Comment by marquiz** [comment]
I experimented a bit, see #457

**Comment by marquiz** [comment]
@kfox1111 commented in #457

> Can someone add a reference to the repo to artifacthub.io please?

Anyone familiar with the artifacthub.io? I think we'd need a kubernetes-sigs org there

**Comment by kfox1111** [comment]
yeah, a kubernetes-sigs org would be good. No idea how to do that though. Everything being under the CNCF umbrella should help I would think.

**Comment by marquiz** [comment]
> yeah, a kubernetes-sigs org would be good. No idea how to do that though. Everything being under the CNCF umbrella should help I would think.

We definitely need an "official" org there. I'm asking around to find/get one, stay tuned...

**Comment by marquiz** [comment]
Now available in artifacthub.io:
https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery

Closing this issue
