### ISSUE TITLE
Consider expanding the scope to discovering/publishing opaque integer resources.

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes-sigs/node-feature-discovery#45]
Per the original [NFD scope document](https://docs.google.com/document/d/1ki7QqKp9n7vzX7yKIpXp2fGGRsG2B1dUUoQ3uCarIC4/edit) that was circulated at project incubation time, this project only handles "binary" (there-or-not) attributes.

Since then, alpha support for opaque integer resources was added to Kubernetes. See [Kubernetes PR 31652](https://github.com/kubernetes/kubernetes/pull/31652).

Should we expand the scope to allow NFD sources to advertise new kinds of consumable resources?

For one concrete usage example, consider extending issue #35 (Discover SR-IOV capable network interfaces) to allow allocatable virtual functions. In this case, there is work in progress to isolate VFs in a CNI plugin.

**Comment by vishh** [comment]
If NFD is expected to work across deployments, it should align with the overall compute resource management plans for Kubernetes. The maintainers of core kubernetes should also be managing NFD in-order for it to successfully align with the overall roadmap for kubernetes

**Comment by ConnorDoyle** [comment]
Hey @vishh, please help me parse your comment. Are you for or against allowing NFD to patch the capacity of a node to advertise OIRs?

- If Kubernetes core knows about the resource, then we don't need to use OIR. Nonetheless, OIR is now a thing :)
- If this code doesn't do the capacity-patching, then something else must, since that's how OIR works.

**Comment by derekwaynecarr** [comment]
@vishh +1 , we also need a road-map identified for 2017 for resource management generally.

**Comment by ConnorDoyle** [comment]
So you guys are saying, no decision now but let's talk about it in the long term roadmap? That's fair. Is there an issue yet to put that roadmap together (can we start linking things from one spot?)

**Comment by rkamudhan** [comment]
Network isolation using CNI plugin and also using NFD label is achievable, but in the case of multiple CNI configuration files in a node in the default directory (/etc/cni/net.d) , the Kubelet pick the first one in lexicographic order of file name.

**Comment by rkamudhan** [comment]
Isolating VFs in a CNI plugin is added as features in Multus CNI plugin, please refer https://github.com/containernetworking/cni/issues/343

**Comment by marquiz** [comment]
Closing in favor of #229
