### ISSUE TITLE
Support CRDs for custom label rules

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#468]
**What would you like to be added**:

An idea I've been pondering to make adding new rules for the `custom` source easier, without the need to add any new mounts or anything. NFD would specify a new CRD and watch for objects. Not sure what would be the best way to implement this:

1. NFD worker instances would watch the CRs directly themselves
1. NFD master would watch the CRs and communicate rules via gRPC
1. NFD master would watch the CRs and update a predefined ConfigMap that is mounted on the worker containers
1. Do rule processing on master side: NFD worker sends "raw" features to master. Master watches CRs, performs rule processing/matching against the "raw" features and creates labels.

Option 1 would be the obvious simplest choice even if it opens up direct communication of the worker to the control plane. 

**Why is this needed**:

Make dropping in vendor/user specific custom label rules easier, as simple as `kubectl apply -f <rules.yaml>`

**List of individual PRs**:

- ~#543~
- ~#544~
- ~#596~
- ~#597~
- ~#601~
- ~#596~
- ~#642~
- ~#604~
- ~#639~
- ~#464~
- ~#646~
- ~#653~
- ~#654~
- ~#655~
- ~#656~
- ~#553~

Adjacent PRs, building on top and extending the functionality:

- ~#649~
- ~#660~
- ~#661~
- ~#550~
- ~#663~
- #605
- #662

**Comment by zvonkok** [comment]
etcd has the 1.5 MiB object limit size which corresponds to roughly 750 pages of text. I think this should be enough to hold enough rules.

**Comment by zvonkok** [comment]
Regarding 1. does it mean we would have 1 CR that all nfd-workers would read and report the labels ... If we have several hundreds of nodes, how will the API behave is several hundred nfd-workers are reading from the very same CR? 

Should we add a random startup time?

**Comment by marquiz** [comment]
> Regarding 1. does it mean we would have 1 CR that all nfd-workers would read and report the labels ... 

Yes, all workers will need read that config (CR)

> If we have several hundreds of nodes, how will the API behave is several hundred nfd-workers are reading from the very same CR at the same time? Should we add a random startup time?

This is a fair concern. Unfortunately I don't have access to such a cluster. It's not just startup time but any time a new CR is added (or old one updated)

**Comment by marquiz** [comment]
> Regarding 3. only the master would read the CR and the load would be distributed to each node, update of the CM...

Yes. Point of stress would be moved to the configmap

**Comment by zvonkok** [comment]
Regarding 2. This could create some load on the "network" if going this route we definitely would need something like "OnChange" trigger and not do this periodically.

**Comment by marquiz** [comment]
> Regarding 2. This could create some load on the "network" if going this route we definitely would need something like "OnChange" trigger and not do this periodically

Yeah, I don't like this as it complicates the worker-master communication and looks like a well of sync issues.

**Comment by marquiz** [comment]
Added option 4 which might make sense: do rule processing of the CRs on the master side.

**Comment by marquiz** [comment]
> I know I am biassed, but I feel this issue is more suited for the Operator than the Operand side of NFD
> thoughts?

I think this would be orthogonal to / independent of the operator and should be handled by nfd-master. Allowing the creation of rules independent of the deployment mechanism, be it the operator, Helm or templates/kustomize.

**Comment by marquiz** [comment]
Been working on a prototype building on top of #464 and #550. I'll submit a RFC version soon.
/remove-lifecycle stale

**Comment by marquiz** [comment]
> Been working on a prototype building on top of #464 and #550. I'll submit a RFC version soon.

...and we have #553

**Comment by ArangoGutierrez** [comment]
we are getting ready for V0.11.0 !!!!

**Comment by marquiz** [comment]
With #663 all the essential parts are now merged and I declare this issue as implemented
/close

**Comment by eero-t** [comment]
> With #663 all the essential parts are now merged and I declare this issue as implemented /close

@marquiz In one of the PRs you mentioned documentation update being a separate PR, but I do not see one listed above.  could you you give a pointer to the associated doc update?

**Comment by marquiz** [comment]
> @marquiz In one of the PRs you mentioned documentation update being a separate PR, but I do not see one listed above. could you you give a pointer to the associated doc update?

It's still under construction, there's no PR yet on that
