### ISSUE TITLE
Allow sub-namespaces of default label namespace

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#477]
**What would you like to be added**:

We could allow `*.feature.node.kubernetes.io` sub-namespaces for feature labels, in addition to the default `feature.node.kubernetes.io`. That is, these namespaces would be automatically allowed, without any extra configuration/options. Arbitrary namespaces (like `vendor.com/`) could be enabled with `-extra-label-ns` just like before.

**Why is this needed**:

Make it easier to do vendor/user specific differentiation/partitioning.

**Comment by zvonkok** [comment]
Would they be automatically whitelisted? Are we going still to allow own namespaces? GPU feature discovery exposes the new discovered feature labels as `nvidia.com/.....`

**Comment by marquiz** [comment]
> Would they be automatically whitelisted?

Yeah, that was the intention. Whitelist `*.feature.node.kubernetes.io` in addition to the default `feature.node.kubernetes.io`. The idea would be that these namespaces could be used without `-extra-label-ns`

> Are we going still to allow own namespaces? GPU feature discovery exposes the new discovered feature labels as `nvidia.com/.....`

Sure, they could be enabled with `-extra-label-ns` just like before.

**Comment by marquiz** [comment]
Implementation in #536 
/remove-lifecycle stale
