### ISSUE TITLE
Create a nfd-worker/master dump to help debugging

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery#479]
**What would you like to be added**:
A CLI helper command to get all the info of the running instance when inside the container, when going into the pod using `kubectl debug` it would be nice to have a dump command to see how the instance is configured.

This would help live debugging of a pod much easier

**Comment by marquiz** [comment]
Maybe something like `nfd-worker config` could be useful. It should dump the core config plus all the source configs, too.

/remove-lifecycle stale

**Comment by marquiz** [comment]
Patches are welcome 😉
