### ISSUE TITLE
Config file for nfd-master

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#485]
**What would you like to be added**:

Now that nfd-worker has quite extensive support for dynamic run-time configurability through its config file, I started to think would it be good to have something similar for nfd-master as well 🤔  A similar json/yaml based configuration file with fsnotify watching for changes. Could allow dynamic control of e.g. logging parameters, allowed namespaces, extended resources and label whitelisting.

**Why is this needed**:

Would make configuration of nfd-master easier, enabling dynamic (run-time) configurability.

**Comment by ArangoGutierrez** [comment]
++ I like this idea

**Comment by marquiz** [comment]
Moving milestone to v0.12.0
/remove-lifecycle stale

**Comment by marquiz** [comment]
We still want this (I think) but might need to adjust the milestone...

/remove-lifecycle rotten
