### ISSUE TITLE
On containerd - Failed to unpack image "quay.io/kubernetes_incubator/node-feature-discovery:v0.6.0"

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [kubernetes-sigs/node-feature-discovery#503]
**What happened**:
On a kubernetes cluster with containerd as runtime, install of nfd fails with below error:

![image](https://user-images.githubusercontent.com/36700822/113543287-aeffcc80-9603-11eb-862f-f13819e741c5.png)

**What you expected to happen**:

succesful installation of nfd.

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.6.0/nfd-master.yaml.template

namespace/node-feature-discovery created
serviceaccount/nfd-master created
clusterrole.rbac.authorization.k8s.io/nfd-master created
clusterrolebinding.rbac.authorization.k8s.io/nfd-master created
deployment.apps/nfd-master created
service/nfd-master created

2. kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.6.0/nfd-worker-daemonset.yaml.template

daemonset.apps/nfd-worker created 

3.  kubectl -n node-feature-discovery get all

NAME                                                  READY   STATUS                     RESTARTS      AGE
pod/nfd-master-74dfb98fbd-d9sfm   0/1        CreateContainerError   0                49s
pod/nfd-worker-7zpfd                        0/1        CreateContainerError   0                18s

4. kubectl describe pod nfd-master-74dfb98fbd-d9sfm -n node-feature-discovery
........................................
........................................
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m17s                 default-scheduler  Successfully assigned node-feature-discovery/nfd-master-7.......
  
  Warning  Failed     23s (x12 over 2m17s)  kubelet            Error: failed to create containerd container: error unpacking image: failed to extract layer sha256:83b43189420d069cbdc1421b94c396c6b74d1ad8150933d411a223b145b981ab: failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.gzip: fork/exec /usr/bin/unpigz: no such file or directory: unknown

**Anything else we need to know?**:

Runtime for this cluster is containerd

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`):  Linux ca1dl01-vm1 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marquiz** [comment]
There seems to be something wrong with your Ubuntu installation, not with the NFD image. This looks like the root cause (unpigz missing):

> /usr/bin/unpigz: no such file or directory: unknown

I'd propose to close this issue as not-applicable.

**Comment by vaibhavraizada-hcl** [comment]
@marquiz 

Yes, you were correct. This was a problem with the ubuntu VM. We can mark this issue as not-applicable.
