### ISSUE TITLE
When --verify-node-name is on, respect either SubjectAlternativeName and/or wildcards

### ISSUE THREAD

**Issue by robertdavidsmith** [kubernetes-sigs/node-feature-discovery#511]
Hi,

Using --verify-node-name is currently pretty painful, while it's easy enough to produce a certificate per node with Helm/CertManager, there is no clean way to get a different certificate into every pod with a DaemonSet.

It would be better if one certificate could cover all nodes.

Can we have an alternative way of securing this?
- CommonName wildcard support
- SubjectAlternativeName support
- An alternative auth mechanism, maybe based on a shared secret

I can put in a PR to change https://github.com/kubernetes-sigs/node-feature-discovery/blob/ab78df346679a6df0e1f5286874fb191022404ba/pkg/nfd-master/nfd-master.go#L369 to support wildcards or SubjectAlternativeName. Would you accept such as PR?

Thanks,

Rob

**Comment by marquiz** [comment]
@robertdavidsmith thanks for bringing this up

> Using --verify-node-name is currently pretty painful, while it's easy enough to produce a certificate per node with Helm/CertManager, there is no clean way to get a different certificate into every pod with a DaemonSet.

I'm painfully aware of this 😓 

I think `--verify-node-name` is actually very badly out-of-date as SSL common name is kind of deprecated 😬 

> It would be better if one certificate could cover all nodes.
> 
> Can we have an alternative way of securing this?
> 
> * CommonName wildcard support
> * SubjectAlternativeName support
> * An alternative auth mechanism, maybe based on a shared secret
> 
> I can put in a PR to change
> 
> https://github.com/kubernetes-sigs/node-feature-discovery/blob/ab78df346679a6df0e1f5286874fb191022404ba/pkg/nfd-master/nfd-master.go#L369
> 
> to support wildcards or SubjectAlternativeName.

I think we should definitely add support for SubjectAlternativeName. How about wildcards in SubjectAlternativeName? We could keep the CommonName for some time for backwards compatibility but I wouldn't add wildcard support there. Regarding the  additional auth mechanisms, I think those could be left as a future exercise. Add the later if needed. WDYT?


> Would you accept such as PR?

Definitely! That would be much appreciated 😊 👍

**Comment by robertdavidsmith** [comment]
Ok, I'll do this, might be a few days though due to other commitments

Suggest just using https://golang.org/pkg/crypto/x509/#Certificate.VerifyHostname - this uses SubjectAlternativeName, and it looks like it supports limited wildcards (* on left hand side only).

**Comment by marquiz** [comment]
> Ok, I'll do this, might be a few days though due to other commitments

Cool, thanks!

> Suggest just using https://golang.org/pkg/crypto/x509/#Certificate.VerifyHostname - this uses SubjectAlternativeName, and it looks like it supports limited wildcards (* on left hand side only).

Sounds good 👍

**Comment by robertdavidsmith** [comment]
https://github.com/kubernetes-sigs/node-feature-discovery/pull/514

**Comment by robertdavidsmith** [comment]
Thanks for merging the above PR @marquiz !

It would be great if someone could make another release, the last appears to be v0.8.1 from 6th April 2021.

**Comment by robertdavidsmith** [comment]
Closing as https://github.com/kubernetes-sigs/node-feature-discovery/issues/518 has been made to cover releasing a new version of node-feature-discovery.

Thanks again for your help @marquiz !
