### ISSUE TITLE
node-feature-discovery-worker terminated often due to "failed to advertise labels: rpc error: code = Unknown des"

### ISSUE THREAD

**Issue by hsgahm** [kubernetes-sigs/node-feature-discovery#539]
**What happened**:
1. Issue: 
node-feature-discovery-worker terminated often due to "failed to advertise labels: rpc error: code = Unknown des" in func advertiseFeatureLabels(client pb.LabelerClient, labels Labels).
It happens about every 1~2 days.

2. check status:
kubectl describe -n nvidia pod gpu-operator-node-feature-discovery-worker-4fdtd | grep "Last State" -A4
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 06 Jun 2021 15:05:03 +0000
      Finished:     Mon, 07 Jun 2021 21:28:17 +0000

3. related logs
2021/06/07 21:28:17 ERROR: can't detect whether turbo boost is enabled: open /host-sys/devices/system/cpu/intel_pstate/no_turbo: no such file or directory
2021/06/07 21:28:17 Failed to read /proc/config.gz: open /proc/config.gz: no such file or directory
2021/06/07 21:28:17 Configuration successfully loaded from "/etc/kubernetes/node-feature-discovery/nfd-worker.conf"
2021/06/07 21:28:17 cpu-cpuid.AVX2 = true
2021/06/07 21:28:17 cpu-cpuid.AVX512BW = true
2021/06/07 21:28:17 cpu-cpuid.AVX = true
2021/06/07 21:28:17 cpu-cpuid.AESNI = true
2021/06/07 21:28:17 cpu-cpuid.ADX = true
2021/06/07 21:28:17 cpu-cpuid.AVX512DQ = true
2021/06/07 21:28:17 cpu-cpuid.AVX512CD = true
2021/06/07 21:28:17 cpu-cpuid.AVX512VL = true
2021/06/07 21:28:17 cpu-cpuid.FMA3 = true
2021/06/07 21:28:17 cpu-cpuid.AVX512VNNI = true
2021/06/07 21:28:17 cpu-cpuid.IBPB = true
2021/06/07 21:28:17 cpu-cpuid.AVX512F = true
2021/06/07 21:28:17 cpu-cpuid.STIBP = true
2021/06/07 21:28:17 Failed to detect the status of selinux, please check if the system supports selinux and make sure /sys on the host is mounted into the container: open /host-sys/fs/selinux/enforce: no such file or directory
2021/06/07 21:28:17 kernel-version.minor = 4
2021/06/07 21:28:17 kernel-version.revision = 0
2021/06/07 21:28:17 kernel-config.NO_HZ = true
2021/06/07 21:28:17 kernel-config.NO_HZ_IDLE = true
2021/06/07 21:28:17 kernel-version.full = 5.4.0-65-generic
2021/06/07 21:28:17 kernel-version.major = 5
2021/06/07 21:28:17 SR-IOV not supported for network interface: cali0b60e08835c: open /host-sys/class/net/cali0b60e08835c/device/sriov_totalvfs: no such file or directory
2021/06/07 21:28:17 SR-IOV not supported for network interface: cali8547da6ff7f: open /host-sys/class/net/cali8547da6ff7f/device/sriov_totalvfs: no such file or directory
2021/06/07 21:28:17 SR-IOV not supported for network interface: docker0: open /host-sys/class/net/docker0/device/sriov_totalvfs: no such file or directory
2021/06/07 21:28:17 SR-IOV not supported for network interface: ens33: open /host-sys/class/net/ens33/device/sriov_totalvfs: no such file or directory
2021/06/07 21:28:17 SR-IOV not supported for network interface: tunl0: open /host-sys/class/net/tunl0/device/sriov_totalvfs: no such file or directory
2021/06/07 21:28:17 pci-15ad.present = true
2021/06/07 21:28:17 system-os_release.VERSION_ID.major = 20
2021/06/07 21:28:17 system-os_release.VERSION_ID.minor = 04
2021/06/07 21:28:17 system-os_release.ID = ubuntu
2021/06/07 21:28:17 system-os_release.VERSION_ID = 20.04
2021/06/07 21:28:17 INFO: Custom features: [{Name:rdma.capable MatchOn:[{PciID:0xc000188280 UsbID:<nil> LoadedKMod:<nil>}]} {Name:rdma.available MatchOn:[{PciID:<nil> UsbID:<nil> LoadedKMod:0xc00000ea20}]}]
2021/06/07 21:28:17 Sending labeling request to nfd-master
2021/06/07 21:28:17 failed to set node labels: rpc error: code = Unknown desc = Operation cannot be fulfilled on nodes "prod-master1": the object has been modified; please apply your changes to the latest version and try again
2021/06/07 21:28:17 ERROR: failed to advertise labels: rpc error: code = Unknown desc = Operation cannot be fulfilled on nodes "prod-master1": the object has been modified; please apply your changes to the latest version and try again

**What you expected to happen**:
n

**How to reproduce it (as minimally and precisely as possible)**:
It happens while run time randomly. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.12
- Cloud provider or hardware configuration: VM in VMware
- OS (e.g: `cat /etc/os-release`): 20.04.2 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): Linux prod-master1 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: gpu operator   image: node-feature-discovery version: v0.6.0
- Network plugin and version (if this is a network-related bug): quay.io/calico/kube-controllers:v3.16.5
- Others:

**Comment by hsgahm** [comment]
One more question.
It looks "labeling request" action every 1 minute.
Is there any option to not to update label? or is there any option only request when env changed?

**Comment by marquiz** [comment]
Hi @hsgahm! The issue is with nvidia gpu-operator using a very old release of nfd (v0.6.0). The issue above (sporadic crashes) was fixed in NFD v0.7.0.

Thus, I suggest to close this issue and file a bug agains nvidia gpu-operator, instead.

> It looks "labeling request" action every 1 minute.

Yes, it does this by default.

> Is there any option to not to update label?

Yes. There is the `--sleep-interval` command line flag, plus a config file option (in v0.8.0 and later) https://kubernetes-sigs.github.io/node-feature-discovery/v0.8/advanced/worker-configuration-reference.html#core to specify the interval or disable updates altogether. Dunno how this is usable with the nvidia gpu-operator, though.

> or is there any option only request when env changed?

Nope. But it's on the backlog (#467)

**Comment by hsgahm** [comment]
I see.
Thank you.
