### ISSUE TITLE
Add support to detect whether running on virtual machine or bare metal

### ISSUE THREAD

**Issue by yank1** [kubernetes-sigs/node-feature-discovery#554]
**What would you like to be added**:

Like [Virt What](https://linux.die.net/man/1/virt-what)，user can get node whether running on virtual machine or bare metal easily.

**Why is this needed**:

It is useful for kubernetes cluster sizing. VM and bare metal are different. VM may be overcommited , so it's not as powerful as bare-metal.

**Comment by mythi** [comment]
@yank1 `cpuid` source gives you `HYPERVISOR`. Would that be sufficient?

**Comment by marquiz** [comment]
> @yank1 `cpuid` source gives you `HYPERVISOR`. Would that be sufficient?

Yes @yank1, shouldn't that be enough?

**Comment by yankay** [comment]
Yes， I think it's useful and enough.

![Uploading 企业微信截图_16413031898614.png…]()


> > @yank1 `cpuid` source gives you `HYPERVISOR`. Would that be sufficient?
> 
> Yes @yank1, shouldn't that be enough?

**Comment by ArangoGutierrez** [comment]
> Yes，@marquiz . I think it's useful and enough.
> 
> ![企业微信截图_16413031898614](https://user-images.githubusercontent.com/1469319/148066734-dce4b94d-d272-4ebb-a941-54dc7831b30b.png)
> 
> > > @yank1 `cpuid` source gives you `HYPERVISOR`. Would that be sufficient?
> > 
> > 
> > Yes @yank1, shouldn't that be enough?

Given that it satisfies initial request
/close

**Comment by mnaser** [comment]
Could we re-open this?  It's not accurate since it is possible for a VM to have nested virtualization enabled, therefore, having the following label set to `true` even though it's a virtual machine.

**Comment by mythi** [comment]
’true’ means ”this is a VM”. As far as I can tell  this is valid regardless of the nesting level. Do you see something else?

**Comment by mnaser** [comment]
> `true` means ”this is a VM”. As far as I can tell this is valid regardless of the nesting level. Do you see something else?

You're right, that's my bad, it seems to imply "HYPERVISOR=true" as in, this is a hypervisor.

**Comment by zvonkok** [comment]
Agree with @mnaser it is a very bad naming by the go cpuid package, the bit is actually named `HYPERVISOR PRESENT` - bit 31 of ECX.  It would be very surprising that AMD and/or Intel are naming bits ambiguously.

**Comment by zvonkok** [comment]
@marquiz @ArangoGutierrez is this extracted from the klauspost/cpuid package?

**Comment by zvonkok** [comment]
A host would have bit 31 of ECX set to 0x0 and a guest would have bit 31 set to 0x1. A host would not have a `HYPERVISOR PRESENT` where a guest would see a `HYPERVISOR PRESENT`.

**Comment by mythi** [comment]
> Agree with @mnaser it is a very bad naming by the go cpuid package, the bit is actually named `HYPERVISOR PRESENT` - bit 31 of ECX. It would be very surprising that AMD and/or Intel are naming bits ambiguously.

@zvonkok I added it and followed the `/proc/cpuinfo` naming: `flags` contains `hypervisor` in case of vCPUs.
