### ISSUE TITLE
Typing error in https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/get-started/deployment-and-usage.md

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes-sigs/node-feature-discovery#567]
In https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/docs/get-started/deployment-and-usage.md,
under the section **NFD-Worker**, 
`This assures re-labeling on regular intervals capturing changes in the system configuration and mames sure that new nodes are labeled as they are added to the cluster.`

`mames` shoud be written as make

**Comment by marquiz** [comment]
Thanks for noting this @vaibhav2107. Are you willing to contribute a PR fixing this?

/good-first-issue
/help

**Comment by vaibhav2107** [comment]
@marquiz sure, will fix this.

**Comment by vaibhav2107** [comment]
Fixes in #575
