### ISSUE TITLE
nfd-worker-daemonset.yaml.template is missing in v0.9.0

### ISSUE THREAD

**Issue by adpempx** [kubernetes-sigs/node-feature-discovery#595]
Hi,

**What would you like to be added**:

With new release v0.9.0 we cannot find anymore:

https://github.com/kubernetes-sigs/node-feature-discovery/blob/v0.8.2/nfd-worker-daemonset.yaml.template

**Why is this needed**:

This template is incredible useful for our deployment and mainly fast.
The file is missing now. Can you please add it again with new release v0.9.0?

Please let us know.

Thanks

**Comment by marquiz** [comment]
Hi @adpempx! Maintaining the templates was error prone and customizing deployments was inflexible. Thus, in v0.9.0 we switched to "template-less" deployments leveraging kustomize. Unfortunately, I won't see the old templates coming back.

Can you specify in a little bit more detail your usage scenario. I believe kustomize should serve you well. You can generate the yaml with
```
kubectl kustomize https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.9.0
```

If you only want to get the worker-related parts and customize it you could create and maintain an overlay of your own. E.g. have `my-overlay/kustomization.yaml` (assuming `node-feature-discovery` and `my-overlay` are in the same parent directory)

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

bases:
- ../node-feature-discovery/deployment/base/worker-daemonset

components:
- ../node-feature-discovery/deployment/components/worker-config
- ../node-feature-discovery/deployment/components/common
```

**Comment by adpempx** [comment]
OK.

Thanks
