### ISSUE TITLE
Broken Link in Advanced Section

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes-sigs/node-feature-discovery#612]
In https://kubernetes-sigs.github.io/node-feature-discovery/v0.9/advanced/developer-guide.html
under the section **Customizing the build**
In `Parameterization file of e2e-tests (see example)` example link is giving 404 Error.

I think the proposed solution is to find some typo in the link.

**Comment by sandipanpanda** [comment]
/sig node 
kind/documentation

**Comment by krishna2603** [comment]
Hey! I am new to open source. I went through the doc. Should I change e2e-config-sample to e2e-tests? I am a bit confused about what to do can u plz guide me?

**Comment by mallow111** [comment]
i think the issue is fixed: https://github.com/kubernetes-sigs/node-feature-discovery/commit/dbb99c6f18c210218c8e844290f11e7ddf7149e1, please close it @vaibhav2107

**Comment by vaibhav2107** [comment]
Thanks @mallow111 for checking, thanks @krishna2603  for the fix.
/close
