### ISSUE TITLE
topologyupdater: more graceful exit on error

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#617]
**What would you like to be added**:

Currently, nfd-topology-updater exits with a cryptic backtrace if `KubeletPodResourcesGetAllocatable` feature gate hasn't been enabled in kubelet. Instead of this, nfd-topology-updater should provide a human-understandable error message, exiting more gracefully.

**Why is this needed**:

Do not confuse users with backtraces

**Comment by we4tech** [comment]
Hi @marquiz,
Do you have any suggestions on how I can reproduce this step locally?
Thanks

**Comment by marquiz** [comment]
> Do you have any suggestions on how I can reproduce this step locally?

1. Run kubelet with `--feature-gates=KubeletPodResourcesGetAllocatable=false` (this is the default so with default k8s deployment you should be ok)
2. (In cloned NFD repo) deploy topology-updater, e.g. with `kubectl apply -k deployment/overlays/topologyupdater-job/``
3. See the logs with `kubectl -n node-feature-discovery logs <pod-name>` and you should see an ugly backtrace

**Comment by we4tech** [comment]
Thanks @marquiz , I'll work on it.
