### ISSUE TITLE
Add support to detect whether the node has storage

### ISSUE THREAD

**Issue by reenakabra** [kubernetes-sigs/node-feature-discovery#674]
Is there a possibility that NFD can set label indicating the storage attached to node and type of storage. These are the disks other than the ones used by operating system and can be formatted and used by storage vendors. Information like the capacity and type of  disks can be helpful.

Let me know your thoughts on this.

**Comment by marquiz** [comment]
With #649 we added capability to detect block devices. Currently, we only detect few queue-related attributes (`rotational`, `dax`, `nr_zones` and `zoned`) but new attributes can easily be added if there is a clear use case for those.

Related to this, I don't see use adding any storage-specific labels that would be generated by default. Merely, the new block attributes are available for vendor/application specific custom labels (#464, #553). This functionality is new, unreleased and the documentation is scarce. But happy to help you out with that.

**Comment by reenakabra** [comment]
Thanks marquiz. From where I was coming is, in case of kubernetes cluster some nodes can be storage only nodes and some can be compute only. It can be good if there is a way to find this using node labels (or some other way if you can suggest). Storage vendors can deploy their software on the nodes that can provision storage and skip the compute nodes that does not have storage.

**Comment by marquiz** [comment]
@reenakabra is block device detection what you're after? Can you elaborate on what specific attributes your would be looking for. Just as an example, we could easily add for example `size` and/or `device/model`.

Generally, I think your use case would be satisfied by deploying a vendor/appication specific labeling rule that would examine certain block device attributes and create labels accordingly.

/cc zvonkok mythi

**Comment by apurv15** [comment]
@marquiz : Set "non-OS-block-device=true" if there exists block devices which do not contain OS bits. NFD could look at output of "lsblk" and if there exist devices other than the one's which contain "/" or "/boot" mountpoints, set "non-OS-block-device=true".

**Comment by reenakabra** [comment]
Hi @marquiz , is it possible to set this label on the node?

**Comment by marquiz** [comment]
You can write a custom hook or side-car container (or pod) to do the detection. See [local feature source](https://kubernetes-sigs.github.io/node-feature-discovery/v0.9/get-started/features.html#local--user-specific-features)
