### ISSUE TITLE
Drop the iommu feature source

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#676]
**What would you like to be added**:

I'd like to drop the iommu feature source. It has only one feature `enabled` that I doubt nobody uses. This could be replaced by per pci device attribute(s).

Plan:
- v0.10.0: mark as deprecated, disable by default
- drop after two releases (in v0.12.0)

If we get feedback that people are using this we need to re-evaluate the plan

**Why is this needed**:

Simplifying the code, dropping unused functionality.

**Comment by mythi** [comment]
> If we get feedback that people are using this we need to re-evaluate the plan

with the enhanced custom rules, this might become a useful source. 

Along the same lines, `Network`  could be deprecated as this is part of the PCI source (`sriov.capable`)

**Comment by zvonkok** [comment]
@mythi We're going to provide more useful information about the whole iommu/pci/passthrough/mediated devices topic. I will tag you on the draft when ready if you like.

**Comment by zvonkok** [comment]
But I see your point. As a first step one could select the node(s) that have the iommu enabled. Some entity could then enable the kernel cmdline iommu={on, pt} and enable the second phase and expose this feature.

**Comment by zvonkok** [comment]
@marquiz @mythi I need to do a brain dump on the topics I have flying in my head. Lets discuss when ready.

**Comment by mythi** [comment]
@zvonkok thanks! it sounds we have the same use-cases in mind so let's think about it together

**Comment by marquiz** [comment]
@mythi thanks for the feedback

> with the enhanced custom rules, this might become a useful source.

My feeling was just that in it's current form this is pretty incomplete and useless. Maybe better have iommu attributes available as per-pci device attributes(?)

> Along the same lines, `Network` could be deprecated as this is part of the PCI source (`sriov.capable`)

That is worth considering, too, I think 🤔 My feeling is that the generic `sriov.capable` and `sriov.configured` labels are prolly rather useless in practice. BTW, with #660 we added more generic network interface detection (similar to pci and usb devices) and `sriov_totalvfs` and `sriov_numvfs` is available as attributes there, too

**Comment by zvonkok** [comment]
@mythi Currently looking into sandboxed/virtualized container runtimes and how we could provide the right information. There are several ways to provide such devices into the container. 

- passthrough (bound to VFIO) -> PCI ADDR used for creating the device in the VM 
- passthrough (bount to VFIO) -> IOMMU GROUP used for creating the devices(s) in the VM (Kata does that right now) 
- mediated device -> UUID used for creating the device in the VM 
- SR-IOV be it a PF or VF -> PCI ADDR used for creating the device in the VM 

I am not sure if it would be advisable to expose information at every stage; 

(1) IOMMU enabled  -> `iommu_enabled=true`
(2) PCI devices bound to VFIO -> `vfio-pci-0300-10de-04:00:0-present`
(3) PCI devices configured as MDEVs -> `mdev-pci-0300-10de-0xfa9fa0sdf0as-present`
(4) SR-IOV PCI devices -> `vf-pci-addr-present` `pf-pci-0300-10de-04:00:0-present` 

Another use-case I have is to expose PCI config space, vendor agnostic.

**Comment by zvonkok** [comment]
@mythi FYI: https://github.com/kata-containers/kata-containers/issues/2938

**Comment by marquiz** [comment]
As said, maybe those really should per-device attributes (we have `sriov_totalvfs` and `sriov_numvfs`) currently.

IMO, it doesn't seem to make much sense to start advertising any of these as new default labels. WDYT?

**Comment by mythi** [comment]
> As said, maybe those really should per-device attributes 

This could work, yeah. OTOH, to satisfy both (1) and this deprecation, the IOMMU enabled label could also be moved to CPU source.

**Comment by ArangoGutierrez** [comment]
@mythi @zvonkok any thoughts on this issue and #677 ?

**Comment by mythi** [comment]
No objections to drop/deprecate this source. I think we all agree the capability still needs to be detected.

**Comment by marquiz** [comment]
> No objections to drop/deprecate this source. I think we all agree the capability still needs to be detected.

K.

What do you think about adding `iommu_group/type` attribute to all `pci` and `network` devices? This would contain the "raw" value from `iommu_group/type` sysfs file (i.e `DMA`, `DMA-FQ` or `identity`. This would make it possible to detect if iommu has been enabled by simply checking:

```
  - name: "iommu enabled rule"
    labels:
      iommu.enabled: "true"
    matchFeatures:
      - feature: pci.device
        matchExpressions:
          "iommu_group/type": {op: Exists}
```

OTOH, one could check if passthrough has been enabled with something like:

```
  - name: "iommu passthrough rule"
    labels:
      iommu.passthrough: "true"
    matchFeatures:
      - feature: pci.device
        matchExpressions:
          "iommu_group/type": {op: In, value: ["identity"]}
```

**Comment by marquiz** [comment]
WDYT @zvonkok @mythi about that^

**Comment by marquiz** [comment]
#705 implements the idea above^
