### ISSUE TITLE
question - Does it support GPU topology discovery with NFD-Topology-Updater?

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-sigs/node-feature-discovery#681]
I am wondering if the GPU topology can be found and updated with the NodeResourceTopology CR?

I did not find the doc or code about it. Thus I opened this issue.

I'd appreciate it if anyone could help me.

Thanks :clinking_glasses: :beers:

**Comment by marquiz** [comment]
What are you referring to with "GPU topology"? Local CPUs of each GPU device or something else? In the case of former I think we support it (per NUMA-node granularity of device locality). Basically we're dependent on kubelet providing the topology information (through pod resource API).

@swatisehgal @fromanirh can chime in and correct me.

**Comment by gaocegege** [comment]
Thanks for your reply!

>  Local CPUs of each GPU device 

Yeah I mean this. I am not sure if we can get the local CPU and GPUs like this:

```diff
apiVersion: topology.node.k8s.io/v1alpha1
kind: NodeResourceTopology
metadata:
 name: node1
topologyPolicies: ["SingleNUMANodeContainerLevel"]
zones:
 - name: node-0
   type: Node
   resources:
     - name: cpu
       capacity: 20
       allocatable: 16
       available: 10
+     - name: vendor/gpu1
       capacity: 3
       allocatable: 3
       available: 3
```

> Basically we're dependent on kubelet providing the topology information (through pod resource API).

Do you mean https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/606-compute-device-assignment ?

**Comment by fromanirh** [comment]
@marquiz wrote a correct summary. We can report GPU (or any other device) NUMA Affinity provided this is reported by a device plugin through the kubelet.

**Comment by leonharetd** [comment]
Can I add GPU labels, gpu-vendor, gpu-type, gpu-num, gpu-mem Then write different plugs according to different vendors, like NVIDIA uses NVIDIA-smi to fill in this information

**Comment by fromanirh** [comment]
> /cc @ArangoGutierrez, @fromanirh

This is a question for the maintainers (cc @marquiz ) :)
I don't think this feature as it is described now really belongs in the `nfd-topology-updater`, but we can discuss extensions

**Comment by leonharetd** [comment]
provided this is reported by a device plugin through the kubelet, nvidia-device-plugin uses nvidia.com/gpu resource type. The type of gpu is not told here, such as P40, V100, T4. We need this for scheduling, Now we label manually.

**Comment by fromanirh** [comment]
> provided this is reported by a device plugin through the kubelet, nvidia-device-plugin uses nvidia.com/gpu resource type. The type of gpu is not told here, such as P40, V100, T4. We need this for scheduling, Now we label manually.

OK, so we are talking about the base `node-feature-discovert` functionality, not `nfd-topology-updater`.
Can you perhaps integrate using the `local` feature source? https://kubernetes-sigs.github.io/node-feature-discovery/v0.9/get-started/features.html#local--user-specific-features

**Comment by uniemimu** [comment]
> Can I add GPU labels, gpu-vendor, gpu-type, gpu-num, gpu-mem Then write different plugs according to different vendors, like NVIDIA uses NVIDIA-smi to fill in this information

Such vendor specific GPU feature discovery can be handled for example like this: https://github.com/intel/intel-device-plugins-for-kubernetes/tree/main/cmd/gpu_nfdhook

**Comment by marquiz** [comment]
Yes, I think this is a very vendor-specific feature that would be best served by a hook or a side-car pod/container. 

BTW, there's a documentation update under review. Adding a separate customization guide that covers all the recently added new functionality and hopefully improves the documentation of the old stuff a bit, too.
https://github.com/kubernetes-sigs/node-feature-discovery/pull/704
https://marquiz.github.io/node-feature-discovery/master/advanced/customization-guide.html

On a sidenote, isn't this something that the nvidia gpu-feature-discovery would do for you?

**Comment by zvonkok** [comment]
This is done via GFD https://github.com/NVIDIA/gpu-feature-discovery it will provide thing such as: 
```
$ kubectl get nodes -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    ...

    labels:
      nvidia.com/cuda.driver.major: "455"
      nvidia.com/cuda.driver.minor: "06"
      nvidia.com/cuda.driver.rev: ""
      nvidia.com/cuda.runtime.major: "11"
      nvidia.com/cuda.runtime.minor: "1"
      nvidia.com/gpu.compute.major: "8"
      nvidia.com/gpu.compute.minor: "0"
      nvidia.com/gfd.timestamp: "1594644571"
      nvidia.com/gpu.count: "1"
      nvidia.com/gpu.family: ampere
      nvidia.com/gpu.machine: NVIDIA DGX-2H
      nvidia.com/gpu.memory: "39538"
      nvidia.com/gpu.product: A100-SXM4-40GB
      ...
...
```

**Comment by leonharetd** [comment]
Thanks a lot.

**Comment by ArangoGutierrez** [comment]
Hey @gaocegege , is your question solved? if so feel free to close this issue

**Comment by gaocegege** [comment]
Thanks! I am closing it
