### ISSUE TITLE
Use shorter label namespace

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#778]
**What would you like to be added**:

I'd like to move to a shorter label namespace (e.g. `nfd.k8s.io/` or `feature.node.k8s.io/`) before nfd v1.0. I'm not sure what would be the least painful way there (or if it even is worth it).

One path could be:
1. Allow the shorter namespace. For custom labels only
2. Have an option to switch to the shorter namespace for all labels (the old long namespaces would still be the default)
3. Make the new namespace the default for built-in labels. Have an option to use the old one instead
4. Drop the compatibility mode (no hurry with this)

**Why is this needed**:

Usability

**Comment by marquiz** [comment]
@zvonkok @ArangoGutierrez what do you think about this? Is it too disruptive?

OTOH we can start implementing this with the two first steps (allow `nfd.k8s.io` and create a flag for turning that on for all labels). This gives us time to experiment and get feedback based on which we can do the switchover of back off.

**Comment by ArangoGutierrez** [comment]
Agree that this should be optional for some time. Many workloads might have hard coded the current schema.

Question: can we use k8s when becoming a 1.0 API?

**Comment by fmuyassarov** [comment]
I think it is better we keep discussion notes here. So, I will copy paste my comments here from the PR. 

This is a breaking change, and usually in k8s for such a change it takes ~3-4 releases to remove a feature. Example: [rename "node-role.kubernetes.io/master" ](https://github.com/kubernetes/kubeadm/issues/2200) `node-role.kubernetes.io/master` label & taint renaming in Kubeadm, they had both labels in parallel that gave time to users to switch to the new format. And perhaps we can follow the same path?

For example, 

#### Release - v0.12.X
1. introduce a short label and a flag to switch between long and short labels
2. set the flag to use long label by default
3. announce to community/users to adapt to use the short label
4. get community/users feedback

#### Release - v0.13.X
1. turn on both short and long labels by default but still have an option to disable them
2. get community/users feedback

#### Release - v0.14.X
1. Turn off long label by default but still have an option to enable it

#### Release - v0.15.X
1. Remove the long label entirely from the codebase and keep only short label
2. Remove the flag to switch between short and long labels

I'm not sure about the estimated time between MINOR releases in NFD project, but if you think it is too short that we take above steps in every MINOR release, then of course we can extend it. And actually better if we get users feedback on that.

Patch for the first step is ready for review in https://github.com/kubernetes-sigs/node-feature-discovery/pull/881 and if you folks agree with the plan then let's move on. Any comments, thoughts, concerns are welcome. I will also spread the word in on the slack.

**Comment by marquiz** [comment]
> I think it is better if we keep discussion notes here.

Yup 👍

**Comment by ArangoGutierrez** [comment]
What if for a next step we make it optional? 
in the CRD add an entry `short namespace :yes/no` 

thoughts?

**Comment by fmuyassarov** [comment]
> What if for a next step we make it optional? in the CRD add an entry `short namespace :yes/no`
> 
> thoughts?

As per discussion on the [slack](https://kubernetes.slack.com/archives/C01A82FKSQK/p1662963765877289), I was thinking of introducing a flag to turn on/off the new label but I'm also fine with the CRD as well. TBH, I don't have a strong opinion which was one is better.

**Comment by marquiz** [comment]
What CRD are you referring to? If it's operator then sure. But this needs to be a single config option in nfd-master (i.e. cluster-wide)

**Comment by ArangoGutierrez** [comment]
yes, I agree, it should be a flag. see the slack link above

**Comment by marquiz** [comment]
I think we're not doing this for now. Too much hassle, especially for the end user. Ref discussion in #881 
/close
