### ISSUE TITLE
Adding node hardware specific attributes

### ISSUE THREAD

**Issue by AjinkyaNakave** [kubernetes-sigs/node-feature-discovery#784]
**What would you like to be added**:
Adding node hardware specific attributes in the node labels listed below.
1. Architecture
2. CPU op-mode
3. Total CPU
4. Threads per core
5. Cores per socket
6. Sockets
7. CPU MHz
8. Vendor ID
9. CPU model name
10. Total memory

All these attributes are available in output of below commands
1. /usr/bin/lscpu (1 to 8)
2. cat /proc/cpuinfo (9)
3. cat /proc/meminfo (10)

**Why is this needed**:
Product, which I work on, uses these attributes for collecting system hardware related data and take appropriate actions using business logic.

**Comment by marquiz** [comment]
1-3 are already covered by Kubernetes even without NFD (`kubernetes.io/arch` and `kubernetes.io/os`labels).

4-6: I'm not convinced that the cpu topology information should be exposed as node labels. One problem is that one label (key-value pair) may be inadequate to describe the topology truthfully. Think about e.g. heterogenous CPU architecture (P-core/E-core or big.LITTLE).

7-9: are more or less duplicate to #270 I think

10: I'd like to understand the use case for this. Is a label adequate for this 🧐
