### ISSUE TITLE
helm deploy nfd-topology-updater pod status is CrashLoopBackOff

### ISSUE THREAD

**Issue by wangzihao05** [kubernetes-sigs/node-feature-discovery#810]
**What happened**:

when I use helm to install nfd-topology-updater,it encountered that nfd-topology-updater pod status is CrashLoopBackoff. Then I 
use "kubectl logs -f pod" to see the logs.It says that "failed to obtain node resource information: failed to get allocatable resources (ensure that KubeletPodResourcesGetAllocatable feature gate is eabled): rpc error:code = Unimplemented desc=unknown method 
get allocatableResources for service v1.PodResourcesLister".

I just change chart that /node-featrue-discovery/values.yaml,  "Topology Updater:  enable: true   createCRDs: true"

**What you expected to happen**:
Topology Updater pod can start successfully and I can get topology CR that it detects

**How to reproduce it (as minimally and precisely as possible)**:
just change chart that /node-featrue-discovery/values.yaml,  "Topology Updater:  enable: true   createCRDs: true"
then use helm install values command to install node-feature-discover

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- v1.20.10
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- helm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by marquiz** [comment]
What's your kubelet config? Have you enabled `KubeletPodResourcesGetAllocatable` in kubelet as the error suggests?

**Comment by wangzihao05** [comment]
> What's your kubelet config? Have you enabled `KubeletPodResourcesGetAllocatable` in kubelet as the error suggests?

Thanks.My kubernetes version is 1.20.10.I saw the kubernetes.io just now.The doc says that KubeletPodResourcesGetAllocatable is since 1.21 until 1.22.So my kubernetes doesn't support it.

**Comment by marquiz** [comment]
> Thanks.My kubernetes version is 1.20.10.I saw the kubernetes.io just now.The doc says that KubeletPodResourcesGetAllocatable is since 1.21 until 1.22.So my kubernetes doesn't support it.

Ah, true. You need to update K8s in order to get nfd-topologyupdater to run.
/close
