### ISSUE TITLE
NFD Operator not labeling SR-IOV capable nodes when operstate is not up

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes-sigs/node-feature-discovery#812]
**What happened**:
On SR-IOV capable machines, NFD is not setting the proper labels when the operstate is not up.

**What you expected to happen**:
NFD to set SR-IOV labels when the node is SR-IOV capable

`feature.node.kubernetes.io/network-sriov.capable=true`

**How to reproduce it (as minimally and precisely as possible)**:
Deploy NFD on a SR-IOV cabale machine with nic cables unpluged (operstate down)

**Comment by ArangoGutierrez** [comment]
The diff between v0.11 and v0.9 is at 

```go

		if attrs["operstate"] != "up" {
			continue
		}
```

diff with line https://github.com/openshift/node-feature-discovery/blob/release-4.9/source/network/network.go#L76 at v0.9

**Comment by ArangoGutierrez** [comment]
From Slack @marquiz said
> Basically NFD only considers interfaces that are "up". In v0.9 and before that information was taken from the "flags" attribute in sysfs but in v0.10 and later NFD looks at the "operstate" attribute. Obviously "up" in flags is not the same as operstate == "up"

**Comment by marquiz** [comment]
Yeah, it's a bit messy. NFD In checks if the interface is "up". However, in v0.9 and earlier we checked the `IFF_UP` flag whereas in v0.10.0 we check the `operstate` attribute. And, they are not the same 😑.

`IFF_UP` is the "administrative status" of the interface, indicating if the interface has been enabled or disabled (e.g. `ip l set dev <iface> down` would disable an interface) but it doesn't indicate if the interface is capable of transferring any data, e.g. the cable might be unplugged. The `operstate` is the "operational status", indicating that the interface can be used to transfer data (`IFF_UP`, cable plugged etc).

I basically see three options:
1. Remove the "up" condition checking completely. This would include all devices, independent of their operating state.
2. Revert back to what we did in v0.9 and before, only include devices that have the `IFF_UP` flag set.
3. Do nothing, continue checking the `operstate` attribute as we currently do

Option 2. above is naturally an easy choice for backwards compatibility, but I'm not sure what would be the right thing to do 🧐 Option 1. would be straightforward and understandable, dumbly listing any devices notwithstanding their status. 3. kind of makes sense to me if we want to only list "up" devices.

In any case we should update the documentation (at least in 2. and 3.), emphasizing what is actually being detected.

I'd like to hear thoughts/opinions on this. @ArangoGutierrez @zvonkok @mythi @adrianchiris

**Comment by ArangoGutierrez** [comment]
and what about adding an option to the config like `ignoreState` or something similar?

**Comment by adrianchiris** [comment]
my 2-cent on this:

sriov capability of a network device is not related to neither the administrative nor operating state of the device.
so its Option1 for me

**Comment by marquiz** [comment]
> sriov capability of a network device is not related to neither the administrative nor operating state of the device.
> so its Option1 for me

Thanks @adrianchiris. Now, after sleeping over this I'm inclined to agree. I'm not sure why the check for the if being "up" was added in the first place, probably to check if there are any "usable" interfaces. But I'd probably go and do the simple thing

**Comment by ArangoGutierrez** [comment]
Option 1 ++
