### ISSUE TITLE
I met unexpectedamissionedError when I used BestEffort which is kubelet's topology policy

### ISSUE THREAD

**Issue by wangzihao05** [kubernetes-sigs/node-feature-discovery#816]
I met unexpectedamissionedError when I used BestEffort which is kubelet's topology policy

The question is that I schedulered a pod that to a node.The node has two numa nodes ,the information as follows 

numa node1 memory:
capacity: 16000000000
available: 14000000000

numa node2 memory:
capacity: 16000000000
available: 14000000000

the pod information as follows:

memory: 15000000000

Then the pod's state is unexpectedamissionedError. The pod's error message is that failed to find numa nodes to extend the current topology hint.

But three conditions as follow that pod successfully runs.

situation 1：

numa node1 memory:
capacity: 16000000000
available: 14000000000

numa node2 memory:
capacity: 16000000000
available: 14000000000

pod memory: 17000000000

situation 2：

numa node1 cpu:
capacity: 16
available: 14

numa node2 cpu:
capacity: 16
available: 14

pod cpu: 15

situation 3：

numa node1 cpu:
capacity: 16
available: 14

numa node2 cpu:
capacity: 16
available: 14

pod cpu: 17

So why three situations ran successfully. But the question I met failed.
The Cpu situations are quite different from the memory situations.
Is the memory situation a bug? And Why?

**Environment**:
- Kubernetes version (use `kubectl version`):
- 1.23.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

- Kernel (e.g. `uname -a`):
- Linux node1 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fromanirh** [comment]
> hmm, looks like nothing related to NFD. @swatisehgal @fromanirh ??

I agree. This seems more like a kubernetes/kubelet issue.

**Comment by marquiz** [comment]
Closing as out-of-scope. @wangzihao05 if you're using mainline kubernetes without any scheduler extensions or other customizations I suggest to submit this in the kubernetes repository.
/close
