### ISSUE TITLE
NFD worker fails to communicate with NFD master after worker node rejoin to the cluster

### ISSUE THREAD

**Issue by Tianhao-intel** [kubernetes-sigs/node-feature-discovery#817]
**What happened**:

After a node(as a NFD worker) was deleted through "kubectl" command and rejoin to the cluster, the NFD worker failed to communicate with NFD master. And there are some error logs in nfd-worker pod.

I0526 15:13:24.461238       1 component.go:36] [core]parsed scheme: ""
I0526 15:13:24.461249       1 component.go:36] [core]scheme "" not registered, fallback to default scheme
I0526 15:13:24.461364       1 component.go:36] [core]ccResolverWrapper: sending update to cc: {[{nfd-node-feature-discovery-master:8080  <nil> 0 <nil>}] <nil> <nil>}
I0526 15:13:24.461377       1 component.go:36] [core]ClientConn switching balancer to "pick_first"
I0526 15:13:24.461472       1 component.go:36] [core]Channel switches to new LB policy "pick_first"
I0526 15:13:24.461504       1 component.go:36] [core]Subchannel Connectivity change to CONNECTING
I0526 15:13:24.461672       1 component.go:36] [core]Subchannel picks a new address "nfd-node-feature-discovery-master:8080" to connect
I0526 15:13:24.465091       1 component.go:36] [core]Channel Connectivity change to CONNECTING
W0526 15:13:44.461771       1 component.go:41] [core]grpc: addrConn.createTransport failed to connect to {nfd-node-feature-discovery-master:8080 nfd-node-feature-discovery-master:8080 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout". Reconnecting...
I0526 15:13:44.461914       1 component.go:36] [core]Subchannel Connectivity change to TRANSIENT_FAILURE
I0526 15:13:44.462098       1 component.go:36] [core]Channel Connectivity change to TRANSIENT_FAILURE

**What you expected to happen**:

NFD worker should communicate with NFD master normally after worker node rejoin to the cluster

**How to reproduce it (as minimally and precisely as possible)**:

After NFD service deploy through helm successfully. Delete one worker node and after the NFD worker pod was deleted, rejoin the node to the cluster

**Anything else we need to know?**:

The NFD worker gateway address left after node delete and after rejoin the node, there will be two gateway addresses

**Environment**:
- Kubernetes version (use `kubectl version`): client: v1.22.0; server:v1.17.8+vmware.1
- Cloud provider or hardware configuration: Tanzu
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`):5.4.115
- Install tools: helm

**Comment by ArangoGutierrez** [comment]
I get this when running Minikube from time to time, my work around is
```
kubectl -n kube-system rollout restart deployment coredns
```
it always fix the network issue, and NFD workers communicate back with the master :)
