### ISSUE TITLE
NodeFeature CRD

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#828]
**What would you like to be added**:

Replace gRPC with a CRD.

Introduce a new `NodeFeature` CRD for nfd-worker to expose all underlying "raw" features. This would be per-node, i.e. one object per node. Nfd-worker would create/update this CR instead of communicating with nfd-master over gRPC. Correspondingly, nfd-master would watch for updates in `NodeFeature` objects and (re-)label nodes accordingly.

**Why is this needed**:

I see multiple benefits
- make features available for other apps/users
    - users can easily see everything that was actually discovered (makes writing/debugging `NodeFeatureRules` easier
    - other apps can use the data
- reduce network traffic
    - no need for periodically submitting unchanged data over gPRC
- get rid of TLS and rely on RBAC in authentication/authorization
    - reduced LOC
    - drop cert-manager support
- (almost) immediate response to changes in `NodeFeatureRule` objects - currently they take effect only when nfd-worker sends the (re-)labeling request

**Comment by zvonkok** [comment]
LGTM like the idea, we can even filter on such events in the operator.

**Comment by marquiz** [comment]
I try to squeeze this in the next release as an optional feature at least (turned off by default). We'd support both gRPC and CRD with an option control what to use, smth like `-nfd-api={grpc,crd,all}`...

**Comment by fmuyassarov** [comment]
We probably still want this at some point
/remove-lifecycle stale

**Comment by marquiz** [comment]
Implemented in #986, #903, #1001 and others
/close
