### ISSUE TITLE
the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)

### ISSUE THREAD

**Issue by JaredTan95** [kubernetes-sigs/node-feature-discovery#850]
**What happened**:
I deployed NFD using helm chart as following:
```bash
export NFD_NS=node-feature-discovery
helm repo add nfd https://kubernetes-sigs.github.io/node-feature-discovery/charts
helm repo update
helm install nfd/node-feature-discovery --namespace $NFD_NS --create-namespace --generate-name
```
but I found `node-feature-discovery-master` and `node-feature-discovery-worker` pod always `CrashLoopBackOff` and restart due to the `node-feature-discovery-master` errors :
```bash
I0712 02:57:15.850417       1 nfd-master.go:170] Node Feature Discovery Master v0.11.1
I0712 02:57:15.851284       1 nfd-master.go:174] NodeName: "runner-master"
I0712 02:57:15.851299       1 nfd-master.go:185] starting nfd LabelRule controller
W0712 02:57:16.058358       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
E0712 02:57:16.058737       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.NodeFeatureRule: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
I0712 02:57:16.255825       1 nfd-master.go:226] gRPC server serving on port: 8080
W0712 02:57:17.354229       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
E0712 02:57:17.354305       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.NodeFeatureRule: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
W0712 02:57:20.467604       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
E0712 02:57:20.467672       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.NodeFeatureRule: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
W0712 02:57:25.798492       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
E0712 02:57:25.798563       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.NodeFeatureRule: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
W0712 02:57:35.007158       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
E0712 02:57:35.007314       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: Failed to watch *v1alpha1.NodeFeatureRule: failed to list *v1alpha1.NodeFeatureRule: the server could not find the requested resource (get nodefeaturerules.nfd.k8s-sigs.io)
```

**What you expected to happen**:
how could I solve this issue? thx.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
   - Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
   - Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
  NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`): `Linux skoala-runner 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: helm

**Comment by mythi** [comment]
I tried this and it was working without errors. Can you run `helm install` with `--debug --dry-run` to see if you actually get the CRDs?

**Comment by JaredTan95** [comment]
> I tried this and it was working without errors. Can you run `helm install` with `--debug --dry-run` to see if you actually get the CRDs?

thx, I found the reason, I set `nodeFeatureRule.createCRD` to `false` when helm install.
