### ISSUE TITLE
Config option to disable hooks

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#859]
**What would you like to be added**:

Add a config file option to disable hooks of the `local` feature source, e.g.
```
sources:
  local:
    hooksEnabled: true  # true by default at this point
``` 

Also, add a disclaimer in docs and logs that hooks are now deprecated and will be disabled in a future release (and eventually removed alltogether).

**Why is this needed**:

First step of #856.

**Comment by marquiz** [comment]
/cc @zvonkok
ping @mythi

**Comment by fmuyassarov** [comment]
I'm interested to work on this issue
/assign

**Comment by marquiz** [comment]
> I'm interested to work on this issue

That would be great! 😊
