### ISSUE TITLE
Disable enableServiceLinks feature in NFD master pod

### ISSUE THREAD

**Issue by eero-t** [kubernetes-sigs/node-feature-discovery#883]
**What would you like to be added**:

`spec.enableServiceLinks: false` to _nfd-master_ service pod spec.

**Why is this needed**:

See: https://github.com/kubernetes/kubernetes/issues/92615

(Kubernetes itself is not going to default that to false as that would break its core API compatibility, so each service pod should set that option when service is accessed by its "<service>[.<namespace>]" DNS name instead of env var IP address.)

**Comment by marquiz** [comment]
Why not. Even though we're not expecting to see thousands of services in the nfd namespace
