### ISSUE TITLE
Allow changing master port in helm chart

### ISSUE THREAD

**Issue by stek29** [kubernetes-sigs/node-feature-discovery#884]
**What would you like to be added**:
A Value in helm chart to change port nfd master listens on

**Why is this needed**:
In some setups network policies and firewalls also consider `port` after service translation, so `service.port` is not enough

**Comment by stek29** [comment]
this is still an issue.

**Comment by AhmedGrati** [comment]
Still new to the project, but can I take care of this? It's suitable for new contributors.

**Comment by marquiz** [comment]
@AhmedGrati sure, help is appreciated! Thanks for reaching out. It's yours as I don't think anybody's working on this 👍

**Comment by AhmedGrati** [comment]
Sorry for the dumb question guys, but can you specify please what port you want to customize (the pod port or the service one)? @marquiz @stek29 😅

**Comment by marquiz** [comment]
I think @stek29 means the "target port" i.e. the port that the container exposes

**Comment by AhmedGrati** [comment]
Isn't the master nfd running on `8080`, how should we allow to change it? wouldn't that break the deployment?

**Comment by marquiz** [comment]
how should we allow to change it? wouldn't that break the deployment?

It wouldn't dynamically change. You can pass the port to nfd-master with the `-port` flag

**Comment by AhmedGrati** [comment]
Got it, much appreciated @marquiz 🙏
