### ISSUE TITLE
nfd-worker constantly spams log & nfd-master on feature discovery errors

### ISSUE THREAD

**Issue by eero-t** [kubernetes-sigs/node-feature-discovery#896]
**What happened**:
    
NFD worker spams its log and _nfd-master_ **30 times per second** (at 30ms interval):
```
I0919 09:37:44.111409       1 nfd-worker.go:472] starting feature discovery...
I0919 09:37:44.111533       1 nfd-worker.go:484] feature discovery completed
I0919 09:37:44.111551       1 nfd-worker.go:565] sending labeling request to nfd-master
E0919 09:38:44.136006       1 kernel.go:132] failed to read kconfig: failed to read kernel config from [ /proc/config.gz ...]
I0919 09:38:44.142277       1 nfd-worker.go:472] starting feature discovery...
I0919 09:38:44.142436       1 nfd-worker.go:484] feature discovery completed
I0919 09:38:44.142441       1 nfd-worker.go:565] sending labeling request to nfd-master
E0919 09:39:44.167595       1 kernel.go:132] failed to read kconfig: failed to read kernel config from [ /proc/config.gz ...]
```

**What you expected to happen**:

NFD outputs logs and communicates label changes only when things actually change. Or at least at some reasonable interval.

(Kernel config cannot change without reboot, or modprobe/rmmod for "configs" kernel module, and that's not going to happen multiple times per second.)

**How to reproduce it (as minimally and precisely as possible)**:

Boot with a kernel that does not provide its config information, or mask relevant host paths out with NFD worker pod spec.

In my case it was enough to boot with a manually built kernel using `CONFIG_IKCONFIG=m` option.  I.e. having `/proc/config.gz` would require manually running `sudo modprobe configs` after boot.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23
- Cloud provider or hardware configuration: Intel
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.4
- Kernel (e.g. `uname -a`): 6.0.0-rc5-CI
- Others:
  - NFD version: v0.11.1

**Comment by eero-t** [comment]
Could not reproduce this, so I'm not sure what exactly are all the triggering conditions.  But it has not happened on nodes (with older kernels) where `/proc/config.gz` is present, and that's the only error still visible in NFD logs, so it must be at least one of the conditions.  I.e. cause needs to be found, and fix verified, with code inspection...

**Comment by eero-t** [comment]
Potentially related: #805

(I did not `strace` nfd-worker when it was busy-polling for feature updates, so it's possible that some inotify things was acting weird without me noticing.)

**Comment by marquiz** [comment]
nfd-worker tries multiple different locations:
https://github.com/kubernetes-sigs/node-feature-discovery/blob/8199cb3f13c421f7b316d3092d207c3456e45d7e/source/kernel/kconfig.go#L71
(rather limited set of locations if it's unable to determine the kernel version).

However, this error has nothing to do with continuous "spamming". NFD is stateless, simple and stupid and does full re-discovery every 60s by default. That can be changed with the `core.sleepInterval` config option. Of course, communication to nfd-master could be optimized but we want to do full pass at certain periods. Also, #828 (ditching gRPC) will change this. Patches are of welcome if you want to work on this 😉

**Comment by eero-t** [comment]
Spamming part was it doing this constantly at 0.03s interval (on node missing `config.gz`), not at the expected 60s interval (like all other nodes). There was kernel config file on disk, but not at the locations checked. `core.sleepInterval` was not changed.

After modprobing `configs` module + restarting `nfd-worker`, the issue disappeared.  It did not come back although `configs` module was removed and `nfd-worker` was restarted (both tested separately).

I guess there's some particular condition that triggers `sleepInterval` to be skipped on errors?

**Comment by marquiz** [comment]
> Spamming part was it doing this constantly at 0.03s interval (on node missing `config.gz`), not at the expected 60s interval (like all other nodes). There was kernel config file on disk, but not at the locations checked. `core.sleepInterval` was not changed.

Hmm, thanks for the clarification. 0.03s was not seen in the log snippet you attached. That really shouldn't happen and I can't immediately figure out how that could happen. But that needs to be investigated

**Comment by marquiz** [comment]
> [1] Why updates are normally done at 1 min + 0.03 secs interval, instead of at exact 1min interval? Is the next deadline (incorrectly) calculated only after the update, instead of before it?

It only re-wires the timer after the labeling has been completed. So 30ms in this case is the time it takes to re-discover/re-label. I think that could be easily changed by using e.g. `time.Tick` instead if that matters

**Comment by eero-t** [comment]
I think it would be surprising to user if e.g. with features taking 50% of the interval, query interval would be 150% of the specified.

IMHO NFD should output an error if queries take longer than the specified interval.  And maybe a warning, if they take more than half of it.

**Comment by eero-t** [comment]
The kernel I was using (drm-tip 6.0.0-rc5) had a bug (splice() semantics change e.g. messing disk writes) that's fixed in in newer RC release, which may have been causing this issue => Feel free to close this issue if you think code is fine.

**Comment by marquiz** [comment]
> The kernel I was using (drm-tip 6.0.0-rc5) had a bug (splice() semantics change e.g. messing disk writes) that's fixed in in newer RC release, which may have been causing this issue => Feel free to close this issue if you think code is fine.

K, thanks for the update. I'm closing this for now as by reading the code I cannot figure out how this could happen in NFD. We can re-open if we ever see this again.

Feel free to submit new issues about the improvements in sleep-interval you suggested 😊 

/close
