### ISSUE TITLE
topology-updater: NRT CRD resourses are not cleaned up, on node deletion(scale-in)

### ISSUE THREAD

**Issue by nmathew** [kubernetes-sigs/node-feature-discovery#928]
Node Resource Topology node specific CRD resources are not cleaned up on node deletion(scale-in).
I think this should be part of nfd worker/updater.

**Comment by nmathew** [comment]
@fromanirh

**Comment by fromanirh** [comment]
yes, this is a gap. Besides littering the cluster, there is any other impact?

**Comment by nmathew** [comment]
No functional impact...

**Comment by marquiz** [comment]
NFD-Master could have a garbage-collection loop to delete NRT objects for non-existing nodes
/help

**Comment by PiotrProkop** [comment]
I have created PR to address this issue: https://github.com/kubernetes-sigs/node-feature-discovery/pull/1024
