### ISSUE TITLE
Network feature detection fails

### ISSUE THREAD

**Issue by lishaokai1995** [kubernetes-sigs/node-feature-discovery#931]
**What happened**:
When detecting network features, some files in the `/sys` directory are accessed in the code, but the `yaml` deployment file mounts the system's `/sys` directory to the `/host-sys` directory, which disables the network feature detection. I don't know if this has any effect on other features.
**What you expected to happen**:
The network features can be detected successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I suggest that `pathPrefix` should be read from the configuration file
**Environment**:
- Kubernetes version (use `kubectl version`):v1.20.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

https://github.com/kubernetes-sigs/node-feature-discovery/issues/931#tasklist-block-c10ba75e-e70e-4952-ba68-d01c83c3e7bd

**Comment by lishaokai1995** [comment]
I am using version `0.11.2`

**Comment by marquiz** [comment]
What deployment mechanism are you using. NFD container is supposed to mount host sysfs under /host-sys. I don't think there's need to make that a dynamic configuration option

**Comment by lishaokai1995** [comment]
This is how I deploy:`kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.11.2`
I mean that even though NFD mounts host sysfs under /host-sys, the code still uses /sys

**Comment by fmuyassarov** [comment]
> This is how I deploy:`kubectl apply -k https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref=v0.11.2` I mean that even though NFD container mounts host sysfs under /host-sys, the code still uses /sys

I don't think that's is right. The network features source code [reads](https://github.com/kubernetes-sigs/node-feature-discovery/blob/cab617c42e76719159edb96d63e57a9058613b00/source/network/network.go#L116) from /host-sys, example log...
```
I1024 08:18:58.612581       1 local.go:115] starting hooks...
I1024 08:18:58.612714       1 network.go:117] network features direcotry is:/host-sys
I1024 08:18:58.631620       1 nfd-worker.go:459] starting feature discovery...
I1024 08:18:58.632001       1 nfd-worker.go:471] feature discovery completed
I1024 08:18:58.632021       1 nfd-worker.go:552] sending labeling request to nfd-master
```

**Comment by marquiz** [comment]
> don't think this is right.

Yeah, I don't think it's right, either. `network` source reads from '/host-sys` on the released image

**Comment by fmuyassarov** [comment]
@lishaokai1995 may I ask what network features are you expecting to see as node labels ?

**Comment by marquiz** [comment]
BTW, I accidentally spotted one hardcoded sysfs path though: #933

**Comment by marquiz** [comment]
> @lishaokai1995 may I ask what network features are you expecting to see as node labels ?

Yes, and what error are you seeing in logs

**Comment by lishaokai1995** [comment]
> > @lishaokai1995 may I ask what network features are you expecting to see as node labels ?
> 
> Yes, and what error are you seeing in logs
No errors were reported in the log. It's just that the nodes aren't labeled as I expected: `network-sriov.capable=true`.Through debugging, I found that it went to the /sys directory, which is why I raised the issue. But now it turns out it might be me.

**Comment by fmuyassarov** [comment]
I would suggest to check if virtualization is enabled on the node. Perhaps it is disabled...

**Comment by marquiz** [comment]
> I found that it went to the /sys directory,

If you build it non-containerized (i.e. `make build`) then it looks at `/sys`. That's for easier debugging/development.

**Comment by lishaokai1995** [comment]
> > I found that it went to the /sys directory,
> 
> If you build it non-containerized (i.e. `make build`) then it looks at `/sys`. That's for easier debugging/development.

I've found the problem now. I will close this issue, thank you.
