### ISSUE TITLE
Support for the Future Intel Xeon (SFR and GNR) Instructions

### ISSUE THREAD

**Issue by msivosuo** [kubernetes-sigs/node-feature-discovery#947]
**What would you like to be added**:
Labeling of new instructions introduced by Intel Xeon Sierra Forest and Granite Rapids platforms: https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf

**Why is this needed**:
Allows workloads to utilize all the latest node specific hardware features.

**Comment by fmuyassarov** [comment]
Granite Rapids instructions were added and it is available in v0.12.0 release of NFD. Sierra Forest instructions are also added to the CPUID and will be available in the NFD once https://github.com/kubernetes-sigs/node-feature-discovery/pull/1023 merged.
Sierra Forest has introduced 6 new instructions, where 2 of those could not be tested successfully. As such, we will add them in the near future once we have validated them in our local tests.
